### ISSUE TITLE
Multiple servers under a single domain

### ISSUE THREAD

**Issue by remy** [dokku/dokku-letsencrypt#101]
I'm using dokku-letsencrypt with AWS' Route 53 and latency based DNS.

Somehow getting the LE to work was fine for the first 3 servers, but now the 4th it never completes and I'm at a loss as to what to do (hoping there might be an answer here or I can be pointed in the right direction).

After I've added the mysite.com domain to the app, it reports:

```
=====> Let's Encrypt iptotax
-----> Updating letsencrypt docker image...
latest: Pulling from dokkupaas/letsencrypt-simp_le
Digest: sha256:398e9173f8e9662df66cb6d0dfa6c6ac07f1e3d65b7994177d487d36eb9b10be
Status: Image is up to date for dokkupaas/letsencrypt-simp_le:latest
       done updating
-----> Enabling ACME proxy for iptotax...
-----> Getting letsencrypt certificate for iptotax...
        - Domain 'mysite.com'
darkhttpd/1.12, copyright (c) 2003-2016 Emil Mikulic.
listening on: http://0.0.0.0:80/
2017-02-16 22:07:30,370:INFO:__main__:1211: Generating new account key
2017-02-16 22:07:36,677:INFO:__main__:1305: mysite.com was successfully self-verified
2017-02-16 22:07:36,948:INFO:__main__:1313: Generating new certificate private key
2017-02-16 22:07:43,921:ERROR:__main__:1271: CA marked some of the authorizations as invalid, which likely means it could not access http://example.com/.well-known/acme-challenge/X. Did you set correct path in -d example.com:path or --default_root? Is there a warning log entry about unsuccessful self-verification? Are all your domains accessible from the internet? Failing authorizations: https://acme-v01.api.letsencrypt.org/acme/authz/[token-removed]
Challenge validation has failed, see error log.

Debugging tips: -v improves output verbosity. Help is available under --help.
-----> Certificate retrieval failed!
-----> Disabling ACME proxy for iptotax...
       done
```

(I wasn't sure if it was right or not to share the LE failure URL, so I've removed it, but can easily replicate it to be viewed).

When I check the LE log, it reports:

```
  "challenges": [
    {
      "type": "http-01",
      "status": "invalid",
      "error": {
        "type": "urn:acme:error:connection",
        "detail": "Could not connect to mysite.com:443",
        "status": 400
      },
      "uri": "https://acme-v01.api.letsencrypt.org/acme/challenge/<token>/661528160",
      "token": "<token>",
      "keyAuthorization": "<token>",
      "validationRecord": [
        {
          "url": "http://mysite.com/.well-known/acme-challenge/<token>",
          "hostname": "mysite.com",
          "port": "80",
          "addressesResolved": [
            "<IP-ADDRESS-OF-DIFFERENT-MACHINE>"
          ],
          "addressUsed": "<IP-ADDRESS-OF-DIFFERENT-MACHINE>"
        },
```

Some people have suggested that I have a custom `location` handler in my nginx config (similarly to what dokku-letsencrypt does under the hood) that points to something like le.mysite.com, but then a) wouldn't that require something on le.mysite.com to be always running (to allow for renewals) and b) the tokens won't match up anyway (though I'm not sure I fully understand the challenge so this could be entirely wrong).

I appreciate any advice or help!

Thank you.

**Comment by larose** [comment]
@remy Is `<IP-ADDRESS-OF-DIFFERENT-MACHINE>` the expected ip address of your domain (and server) or it's a completely unrelated ip address?

Also, can you paste your `/home/dokku/<app>/nginx.conf`?

**Comment by remy** [comment]
The IP is typically *not* the IP of the machine that triggered the LE process.

Below is the nginx.conf - note that I don't have any local configuration either:

```
server {
  listen      [::]:80;
  listen      80;
  server_name mysite.com;
  access_log  /var/log/nginx/mysite-access.log;
  error_log   /var/log/nginx/mysite-error.log;

  location    / {

    gzip on;
    gzip_min_length  1100;
    gzip_buffers  4 32k;
    gzip_types    text/css text/javascript text/xml text/plain text/x-component application/javascript application/x-javascript application/json application/xml  application/rss+xml font/truetype application/x-font-ttf font/opentype application/vnd.ms-fontobject image/svg+xml;
    gzip_vary on;
    gzip_comp_level  6;

    proxy_pass  http://mysite-5000;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_set_header Host $http_host;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Forwarded-For $remote_addr;
    proxy_set_header X-Forwarded-Port $server_port;
    proxy_set_header X-Request-Start $msec;
  }
  include /home/dokku/mysite/nginx.conf.d/*.conf;

}

upstream mysite-5000 {

  server 172.17.0.4:5000;
}
```

**Comment by larose** [comment]
When you try to validate your certificate to you see the request from the validation server in `/var/log/nginx/mysite-access.log`?

Something similar to:

```
66.133.109.36 - - [18/Feb/2017:09:58:25 -0500] "GET /.well-known/acme-challenge/<token> HTTP/1.1" 200 87 "-" "Mozilla/5.0 
(compatible; Let's Encrypt validation server; +https://www.letsencrypt.org)"
```

**Comment by remy** [comment]
Yeah, I do. I'll re-run now and paste in here.

**Comment by remy** [comment]
Oh no, sorry, I don't get anything in the logs. But then, actually if the IP doesn't match the machine, then it shouldn't appear at all right.

**Comment by larose** [comment]
Right. I just read about Route 53 Latency-Based Routing (LBR). So it looks like the ip resolved by LE's validation server is not the same as the ip of the server that triggered the validation process. I see two solutions: add a routing policy in LBR for LE's validation server so it resolves to the right ip (I don't know if it's possible) or use the DNS challenge (http://serverfault.com/questions/750902/how-to-use-lets-encrypt-dns-challenge-validation) instead of the HTTP challenge. I don't think this plugin supports DNS challenge though.

**Comment by remy** [comment]
Yeah, the first option will work for a first time, but it won't work for renewals as it's automated and the site will be fully live by then.

Re: DNS challenge - I'm really not sure how to pull this off, or what would be required to change this plugin to support the DNS-01 challange.

**Comment by joshmanders** [comment]
How does DNS challenge work exactly? From my understanding with http, and how this plugin works is it's done instantly, but with DNS it needs time to update.

If anyone has more info on how the DNS challenge works, we can look into supporting it in this plugin.

**Comment by joshmanders** [comment]
Looks like our [`simp_le`](https://github.com/dokku/simp_le) script does not support DNS challenge, and I'm not quite that advanced in Python or the inner workings of Lets Encrypt to add support for that. :/

**Comment by mholt** [comment]
@joshmanders The DNS challenge is unique in that it's the only challenge which does not contact the server that is obtaining a certificate; the CA's ACME server only contacts the DNS server. In order to complete the challenge in an automated way, the server that is obtaining a certificate (the ACME client) must be able to update the DNS records on its own. [lego](https://github.com/xenolf/lego) is one of the only ones I know that does this. The rest just require you to do it manually I think.

**Comment by joshmanders** [comment]
Ah, I see... So we won't be able to put it in this plugin as we do not manage dns in dokku (afaik)

**Comment by remy** [comment]
Yeah, I'm inclined to close this question and I think I need to find
another way to get the certs updated. It's likely I'll end up generating a
single cert, then pushing it across all the Dokku instances (not sure how
yet though!).

Thanks all the same.

**Comment by joshmanders** [comment]
I haven't used the cert module by itself (only through this letsencrypt) but I think you can pull a cert locally using certbot, and then put that cert on all apps using the cert plugin.

cc @josegonzalez

**Comment by josegonzalez** [comment]
I normally use ansible to configure my Dokku hosts, and push out the certificate that way (using custom ansible modules).

Closing as there isn't really anything we can do here, since managing DNS isn't even something that major config management tools do the same for common providers.
