### ISSUE TITLE
Add alias for or rename ls command

### ISSUE THREAD

**Issue by markelog** [dokku/dokku-letsencrypt#103]
Most dokku plugin call this command `list` not a `ls`, like `mongo`, `mysql`, `redis` and etc, that's a bit inconsistent, so I would like to propose to either change the name or add alias.

I know that have different plugins have different functions and therefore can't represent the same interface, but this command looks universal enough to me to be make more consistent?

**Comment by fwolfst** [comment]
Might be related: https://github.com/dokku/dokku-postgres/issues/102 , I also favor consistency - In the same direction letsencrypt should behave when no subcommand is given - as @josegonzalez is pretty `doc` I guess there will be some words about plugin command conventions soon :)

**Comment by markelog** [comment]
> I guess there will be some words about plugin command conventions soon :)

That would be nice, I also think that command consistency should became a cornerstone for dokku plugins interface
