### ISSUE TITLE
bind: address already in use error after renaming an app

### ISSUE THREAD

**Issue by mspanc** [dokku/dokku-letsencrypt#107]
I am not sure if that may be caused by the fact I have renamed the app prior to calling letsencrypt but today I got the following error:

```
$ dokku003 letsencrypt time-prod
=====> Let's Encrypt time-prod
-----> Updating letsencrypt docker image...
latest: Pulling from dokkupaas/letsencrypt-simp_le
Digest: sha256:398e9173f8e9662df66cb6d0dfa6c6ac07f1e3d65b7994177d487d36eb9b10be
Status: Image is up to date for dokkupaas/letsencrypt-simp_le:latest
       done updating
-----> Enabling ACME proxy for time-prod...
-----> Getting letsencrypt certificate for time-prod...
        - Domain 'time-prod.dokku-ovh1-003.radiokitsrv.org'
        - Domain 'time.radiokitapp.org'
docker: Error response from daemon: driver failed programming external connectivity on endpoint nifty_elion (c002607cba31602a29085323f439ec579b76fcb8069ca8e24d15c79e3a00021d): Error starting userland proxy: listen tcp 0.0.0.0:51784: bind: address already in use.
-----> Certificate retrieval failed!
-----> Disabling ACME proxy for time-prod...
       done
```

**Comment by josegonzalez** [comment]
Strange, I'm guessing it picked a bad port? I haven't been able to replicate this myself :(

Do you know if anything was listening on that port?

**Comment by mspanc** [comment]
Nope, no chance that something was there.

**Comment by josegonzalez** [comment]
Were you able to eventually get this working?

**Comment by mspanc** [comment]
Yes, I retried and it worked.

**Comment by josegonzalez** [comment]
Alright well I can't really fix this without logging output or a way to replicate, so closing. If you get this to occur again, please retry it after running `dokku trace on`. Thanks :)

**Comment by sman591** [comment]
Just saw this same error happen. Doing a `sudo systemctl restart docker` and trying again resolved it, but was strange
