### ISSUE TITLE
New LE setup error on DO similar to #54

### ISSUE THREAD

**Issue by vfulco** [dokku/dokku-letsencrypt#110]
Dokku Version 0.9.4, Dokku-letsencrypt Version Latest, Ubuntu 16.04

Good working version on DO with a toy Node.js app and two URLS: foo.asia and *.foo.asia.  Thought I was following the setup "rules" closely.  

When I do a certificate signup, I get the error message "invalid character" and it shows my app hello.#*.foo.asia and hello.foo.asia.  I am pretty certain LE does not like wildcard certs.  

If I remove the wildcard domain, I get the error message "CA marked some of the authorizations as invalid, which likely means it could not access http://example.com/.well-known/acme-challenge/X".  Any words of wisdom would be appreciated.  Have grubbed around all the typical help sites.

**Comment by joshmanders** [comment]
Yes, your first assumption is correct, LE does not support wild card certificates. You'll have to add all domains that you want to have secured to your app and then run `dokku letsencrypt` to encrypt them all with the same certificate.

The second half is probably something to do with nginx thinking valid cert or something so http is no longer accessible or something. Make sure all apps ssl is disabled and try running it again.
