### ISSUE TITLE
Multiple encrypted apps on same dokku instance

### ISSUE THREAD

**Issue by Rhjulskov** [dokku/dokku-letsencrypt#111]
Is it possible to run multiple encrypted apps on the same droplet?

When trying to encrypt the second app, the second app can't be loaded: :ERR_CERT_COMMON_NAME_INVALID

It's trying to match on the first encrypted apps domain.

Am I missing something completely?

**Comment by joshmanders** [comment]
You have to encrypt both apps by running `dokku letsencrypt <app>` for each.

**Comment by Rhjulskov** [comment]
@joshmanders I am.

I have the two app "domain" and "domain-admin", which each have the single domain attach:
admin.domain.com & domain.com.

When running `dokku letsencrypt` on both, the second domain always fails because the names not matching as stated above ^^

**Comment by joshmanders** [comment]
How are you setting the domains?

**Comment by Rhjulskov** [comment]
`dokku domains:add app1 sub.domain.com`
`dokku domains:add app2 domain.com`

before running letsencrypt of any of them.
I also tried with other apps on the same droplet, which didn't share the domain as above. And it still mismatch the name for the second app encrypted.

**Comment by fruitl00p** [comment]
@Rhjulskov I've had issues before when trying to letsencrypt the apex (i.e. `domain.com`) but eventually this was caused by my own DNS issues (and having multiple domains set for the app etc)

Are you sure you're only trying to issue a cert for the specified domain?

**Comment by Friss** [comment]
I just started hitting this same problem as well. 

I have `appA.com` working perfectly with lets encrypt and then when I try to add `appB.com`, `appB.com works perfectly but `appA.com` tries to send `appB.com`'s certificate. 

I _think_ there is something that is overriding the sym links inside the containers and pointing them at the same file. (Whichever is created last)

**Comment by jamiepenney** [comment]
Just chiming in, I'm having the same problem now with different domains. Does anyone have a resolution for this? It used to work on my old server, but it won't work on a fresh install of dokku 0.10.3.

**Comment by joshmanders** [comment]
This plugin uses the certs core plugin on dokku... If you'd like to dig into that and see if something changed that could be causing this issue, that'd be appreciated.

**Comment by josegonzalez** [comment]
This issue was closed 8 years ago. Please file a new one.
