### ISSUE TITLE
Generating/renewing certificate for a single domain

### ISSUE THREAD

**Issue by mrvautin** [dokku/dokku-letsencrypt#114]
I have a SaaS product which will run many domains, including subdomains. I'm wondering if I've missed something or is there no way to only generate/renew one single domain?

Eg: 
dokku letsencrypt myapp test.domain.com
dokku letsencrypt myapp test1.domain.com

I'm trying to ensure rate limiting doesn't come into play by attempting to generate/renew ALL domains on my dokku app. I will be adding domains to dokku and generating the certificate programatically when a new customer signs up to my SaaS product. I'd hate to generate/renew all domains each time a new customer signs up.

Edit: On reading further, am I asking the same question as issue #48?

**Comment by joshmanders** [comment]
Lets Encrypt does not have support for wildcard certificates right now. You'll have to buy a certificate and use the dokku certs command to add it to your app.
