### ISSUE TITLE
Getting a certificate for the default app

### ISSUE THREAD

**Issue by mikebaldry** [dokku/dokku-letsencrypt#115]
My default app is called 00-rootapp, if I use letsencrypt command to generate it, I get a certificate for `00-rootapp.my.domain`, how would I make it get one for `my.domain` and `00-rootapp.my.domain`? 

Thanks

**Comment by mikebaldry** [comment]
Nevermind, realised you can add root domain to the app as a domain to get this functionality. Great plugin! Thanks :)

**Comment by rwieruch** [comment]
For anyone who runs into this. According to the mentioned case, you would have to add the root domain to dokku: `dokku domains:add 00-rootapp my.domain` and then run `dokku letsencrypt 00-rootapp` again.

**Comment by joshmanders** [comment]
Probably be good idea to put in the docs about having a cert generated for multiple domains.

**Comment by rwieruch** [comment]
I would love to open up a PR if you don't mind :)

**Comment by joshmanders** [comment]
@rwieruch go ahead, ping me and I'll review it. :)

**Comment by rwieruch** [comment]
https://github.com/dokku/dokku-letsencrypt/pull/124 @joshmanders
