### ISSUE TITLE
After letsencrypt my HTTPS domain always times out

### ISSUE THREAD

**Issue by newbreedofgeek** [dokku/dokku-letsencrypt#118]
Hello,

I have a Dokku app (e.g. my-app-api-service) hosted in a EC2 instance available via a public domain (e.g. myappapi.com)

The DNS setup for myappapi.com is:
A -> @ -> points to EC2's Public IP
A -> * -> points to EC2's Public IP
CNAME -> www -> points to @

I have set the Dokku domains config as so:
=====> Global Domain Name
myappapi.com
=====> my-app-api-service Domain Names
myappapi.com

* Probably did not have to set a global and local domain to myappapi.com but I may add more app in future.

Everything was fine and I can access my Dokku app on http://myappapi.com and http://www.myappapi.com

I then wanted to "letsencrypt" my Dokku app and followed the instructions in the README.

So I ran:
`dokku config:set --no-restart my-app-api-service DOKKU_LETSENCRYPT_EMAIL=my-email@gmail.com
`

And then:
`dokku letsencrypt my-app-api-service`

I got this log back:
```
=====> Let's Encrypt my-app-api-service
-----> Updating letsencrypt docker image...
latest: Pulling from dokkupaas/letsencrypt-simp_le
Digest: sha256:398e9173f8e9662df66cb6d0dfa6c6ac07f1e3d65b7994177d487d36eb9b10be
Status: Image is up to date for dokkupaas/letsencrypt-simp_le:latest
       done updating
-----> Enabling ACME proxy for my-app-api-service...
-----> Getting letsencrypt certificate for my-app-api-service...
        - Domain 'myappapi.com'
darkhttpd/1.12, copyright (c) 2003-2016 Emil Mikulic.
listening on: http://0.0.0.0:80/
2017-06-17 01:23:09,239:INFO:__main__:1211: Generating new account key
2017-06-17 01:23:14,267:INFO:__main__:1305: myappapi.com was successfully self-verified
2017-06-17 01:23:14,940:INFO:__main__:1313: Generating new certificate private key
2017-06-17 01:23:18,926:INFO:__main__:391: Saving account_key.json
2017-06-17 01:23:18,926:INFO:__main__:391: Saving fullchain.pem
2017-06-17 01:23:18,926:INFO:__main__:391: Saving chain.pem
2017-06-17 01:23:18,926:INFO:__main__:391: Saving cert.pem
2017-06-17 01:23:18,927:INFO:__main__:391: Saving key.pem
-----> Certificate retrieved successfully.
-----> Installing let's encrypt certificates
-----> Unsetting my-app-api-service
-----> Unsetting DOKKU_NGINX_PORT
-----> Setting config vars
       DOKKU_PROXY_PORT_MAP: http:80:5000
-----> Setting config vars
       DOKKU_PROXY_PORT_MAP: http:80:5000 https:443:5000
-----> Setting config vars
       DOKKU_NGINX_PORT: 80
-----> Setting config vars
       DOKKU_NGINX_SSL_PORT: 443
-----> Configuring my-app-api-service...(using built-in template)
-----> Creating https nginx.conf
-----> Running nginx-pre-reload
       Reloading nginx
-----> Configuring my-app-api-service...(using built-in template)
-----> Creating https nginx.conf
-----> Running nginx-pre-reload
       Reloading nginx
-----> Disabling ACME proxy for my-app-api-service...
       done
```

I then visit http://myappapi.com and it automatically redirects (as intended) to https://myappapi.com. But it times out and I get "myappapi.com took too long to respond."

I have followed this exact steps for another domain and Dokku app I host in another Digital Ocean machine and it works fine.

Any ideas why it's timing out? Am I missing a step?

letsencrypt  v0.8.6
dokku 0.8.0

**Comment by fruitl00p** [comment]
Have you checked the ec2 security groups and allowed 443 incoming into the instance/network? The cert got verified successfully

**Comment by newbreedofgeek** [comment]
@fruitl00p Thanks for that! it was the exact issue... its all working now 👍
