### ISSUE TITLE
Add renew for specific domain in app

### ISSUE THREAD

**Issue by sonic182** [dokku/dokku-letsencrypt#126]
Hi, I have a app with multiple domains, It's possible to do renew of just 1 domain o this app? I don't find how to do it

**Comment by AubreyHewes** [comment]
afaik.. it is not possible.. an app has a (multiple) domain/host config.. the app domain config is used for the le certs (i.e. all configured app domains/hosts are on one cert). You renew the cert (for all domains/hosts) at the same time. 

To automatically renew an app cert (i.e. all configured domains/hosts) you need to set a cron to auto renew the cert see the README section on ` letsencrypt:cron-job`...

**Comment by josegonzalez** [comment]
That is a limit of how we handle domains in Dokku. Lets Encrypt will support wildcard certificates soon - which will partially fix this issue - but supporting ssl certificates for multiple domains is trickier. At this time, the Dokku project is focused on the 80% case, and as such we will not be implementing this functionality.

Hope that makes sense.
