### ISSUE TITLE
can't access app

### ISSUE THREAD

**Issue by J77J** [dokku/dokku-letsencrypt#127]
Hi there,

I'm looking to add this to an app, I have tried running `dokku certs:generate <app> DOMAIN` to make the app accessible in the first place before I add letsencrypt, however, the app is still not accessible in chrome or firefox. It looks like this is due to chrome and firefox no longer trusting self signed certs, so, before I burn through my quota of letsencrypt certs - will I still be able to add letsencrypt ok with this temp certificate? Or do they not trust the self signed cert either?

Any advice appreciated!

Johnny.

**Comment by fruitl00p** [comment]
@J77J I'd suggest cleaning up any previous certs added and only after that use the letsencrypt plugin for the `<app>`. That way you won't have any conflicts in configuration et al. The LetsEncrypt certificates are trusted by all major browser vendors, so self-signing isn't an issue.

**Comment by J77J** [comment]
@fruitl00p the only thing is I need the app to be accessible for letsencrypt plugin to work I think:

> Note: Your app must already be deployed and accessible in the browser in order to add letsencrypt to your app. Your app just being created is not enough. If you need to, add a temporary certificate to your app prior to adding letsencrypt by running dokku certs:generate <app> DOMAIN to make your app accessible.

or would I be able to do it when the app is not accessible? (due to no certificate at all)

**Comment by fruitl00p** [comment]
@J77J letsencrypt will generate everything for you... thus having a 'standard' http-only app will be converted to https... You dont have to have a certificate beforehand

**Comment by fruitl00p** [comment]
@J77J the note is a bit vague (I smell a PR coming up) but it only means that the app should be accessible from outside of the server via 'regular' HTTP... (thus a url pointing to your app)

**Comment by J77J** [comment]
@fruitl00p  ok - my setup forces all http requests to https, probably I'd need to change that first then?

**Comment by fruitl00p** [comment]
Indeed you might have to.

The way it works is that letsencrypt servers will contact the app from their site to hit a special (prepared) url to verify ownership. Once thats done the new certificate will be granted, installed and activated on your application. (thus removing previously defined custom certificates)

This also explains why the app should be accessible from across the internet :smile:
