### ISSUE TITLE
TOS update

### ISSUE THREAD

**Issue by robacarp** [dokku/dokku-letsencrypt#133]
Perhaps related to #132.  With the lastest version installed (`dokku plugin:update letsencrypt`), enabling letsencrypt on a new application fails due to a TOS mismatch: 

```
$ dokku letsencrypt <app>
=====> Let's Encrypt <app>
-----> Updating letsencrypt docker image...
latest: Pulling from dokkupaas/letsencrypt-simp_le
Digest: sha256:398e9173f8e9662df66cb6d0dfa6c6ac07f1e3d65b7994177d487d36eb9b10be
Status: Image is up to date for dokkupaas/letsencrypt-simp_le:latest
       done updating
-----> Enabling ACME proxy for <app>...
-----> Getting letsencrypt certificate for <app>...
        - Domain '<app>'
darkhttpd/1.12, copyright (c) 2003-2016 Emil Mikulic.
listening on: http://0.0.0.0:80/
2017-11-18 03:34:37,467:INFO:__main__:1211: Generating new account key
TOS hash mismatch. Found: cc88d8d9517f490191401e7b54e9ffd12a2b9082ec7a1d4cec6101f9f1647e7b.

Debugging tips: -v improves output verbosity. Help is available under --help.
-----> Certificate retrieval failed!
-----> Disabling ACME proxy for <app>...
       done
```

**Comment by sman591** [comment]
Just saw this as well - I'm sure this is exactly what caused #132 as well.

**Comment by Wareing** [comment]
I used the same workaround from #73 to sort this out for myself basically changing the LE Command in /var/lib/dokku/plugins/available/letsencrypt/functions to use a environment variable instead of the hardcoded value so I can dynamically change it in my apps .env file if i get the same error again in future.

**Comment by fronbasal** [comment]
What is the new hash of the ToS? Can't seem to find it :-1:

**Comment by robacarp** [comment]
@fronbasal I haven't tried the solution proposed in #73, but my guess from the error included above would be `cc88d8d9517f490191401e7b54e9ffd12a2b9082ec7a1d4cec6101f9f1647e7b`

**Comment by fronbasal** [comment]
I have tried that hash, @robacarp. Apparently LE is in the mood of changing the ToS. Uhm, I am currently using hash ```cc88d8d9517f490191401e7b54e9ffd12a2b9082ec7a1d4cec6101f9f1647e7b``` and it is not working (the error: ```TOS hash mismatch. Found: cc88d8d9517f490191401e7b54e9ffd12a2b9082ec7a1d4cec6101f9f1647e7b.```). Hopefully someone can sort this out.

**Comment by fronbasal** [comment]
Fixed by changing the value in ```/var/lib/dokku/plugins/available/letsencrypt/functions```. Did not see that file before :+1:

**Comment by gauravmehla** [comment]
but i am confused, what to change in `/var/lib/dokku/plugins/available/letsencrypt/functions` ? @fronbasal what is the new TOS Hash ?

**Comment by sman591** [comment]
@gauravmehla Line 152:
```
local config="--server $server --email $DOKKU_LETSENCRYPT_EMAIL --tos_sha256 HASH $domain_args"
```

Where HASH should should be whatever `dokku letsencrypt`'s error message says. E.g, if the message is `TOS hash mismatch. Found: XYZ`, use XYZ. I'm using `cc88d8d9517f490191401e7b54e9ffd12a2b9082ec7a1d4cec6101f9f1647e7b` at the time of this comment, though it could change again if the TOS changes.

**Comment by gauravmehla** [comment]
It worked! Thankyou @sman591 🙂

**Comment by dmr** [comment]
Worked for me, thank you! 👍

**Comment by elahmo** [comment]
This issue seems to pop up always when there is a TOS update. Is it possible to solve it long-term, to avoid hardcoding the hash?

**Comment by Wareing** [comment]
Writing a script into the image to fetch the latest TOS hash would probably work.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by dimitriacosta** [comment]
Is this issue related only to the `.xyz` domains or is it a general issue?

**Comment by elahmo** [comment]
I used .io and .com, and it failed, so its not just for .xyz.

**Comment by AubreyHewes** [comment]
@dimitriacosta  @elahmo the hardcoded TOS is no longer valid. see https://github.com/dokku/dokku-letsencrypt/issues/133#issuecomment-345729770 .. edit the  `/var/lib/dokku/plugins/available/letsencrypt/functions` with the new TOS  (see previous comments)

The best fix see PR #134 (which adds a dokku command to update the TOS hash)

**Comment by dimitriacosta** [comment]
Cool, it's working now, thanks @AubreyHewes

**Comment by AubreyHewes** [comment]
#134 is now merged! hopefully a `plugin:update letsencrypt` gits the new code? @joshmanders ?
This alleviates the problem of changing (hopefully) controlled code and adds the possibility of possible future tos changes via the global config #134 @robacarp

**Comment by dimitriacosta** [comment]
I've updated the plugin it's working fine now, thanks

**Comment by joshmanders** [comment]
Yes plugins are just cloned, so if you update your plugins any new merges to `master` should be pulled in since last update.
