### ISSUE TITLE
Someone needs to check the issues... or close them with an answer

### ISSUE THREAD

**Issue by AubreyHewes** [dokku/dokku-letsencrypt#136]
@joshmanders Or is the project unimportant? ( as you are one of the only ;-P )

**Comment by joshmanders** [comment]
There is a couple of us who have access to merge on this repo, but we're all just volunteers. I unfortunately have been busy with my actual day job and haven't had much time for open source.

Maybe @josegonzalez can help out by adding another person to this repo who can help maintain it.

**Comment by josegonzalez** [comment]
@AubreyHewes if you want to go around and comment on all the issues with a fix or mark them as duplicate, that would be great.

Unfortunately, no one is paid to work on this, so whether it gets done is up in the air.

If you'd like to pay my hourly wage so I can take time off paid work - my cat has to eat - let me know via email and we'll figure it out.

**Comment by josegonzalez** [comment]
I mean if you can find solutions to the problems, I'll see a notification and I can either close or merge a fix. Otherwise, we're going to leave them open.

**Comment by joshmanders** [comment]
I have had to unfollow a bunch of non-work related repos as they were spamming my notifications, drowning out repos I need to follow, so if there are any PR's just ping me in one and I will look at it if I have time too.
