### ISSUE TITLE
how to test / dev this plugin?

### ISSUE THREAD

**Issue by AubreyHewes** [dokku/dokku-letsencrypt#137]
My IP is blocked? how do you do it, without blocking your ip?

**Comment by znz** [comment]
I think that you can use `DOKKU_LETSENCRYPT_SERVER=staging` for test / dev.

**Comment by josegonzalez** [comment]
This is documented in the readme, but if you set the `DOKKU_LETSENCRYPT_SERVER=staging` environment variable for your application, then the plugin will run in test mode.

**Comment by AubreyHewes** [comment]
@josegonzalez 

Yeah `DOKKU_LETSENCRYPT_SERVER`

I was thinking more along the lines of a contained dev env (i.e. docker or such)..
Currently development requires installing on the dev's host.

how do others dev this?

**Comment by josegonzalez** [comment]
I would setup the local Dokku VM and work on the plugin there. Thats how I do development of all other plugins.
