### ISSUE TITLE
TOS problem

### ISSUE THREAD

**Issue by denisviklov** [dokku/dokku-letsencrypt#138]
root@ultro-dev-instance:/home/denis# dokku letsencrypt ultro-backend-dev
=====> Let's Encrypt ultro-backend-dev
-----> Updating letsencrypt docker image...
latest: Pulling from dokkupaas/letsencrypt-simp_le
Digest: sha256:398e9173f8e9662df66cb6d0dfa6c6ac07f1e3d65b7994177d487d36eb9b10be
Status: Image is up to date for dokkupaas/letsencrypt-simp_le:latest
       done updating
-----> Enabling ACME proxy for ultro-backend-dev...
-----> Getting letsencrypt certificate for ultro-backend-dev...
- Domain 'dev-api.ultro.io'
darkhttpd/1.12, copyright (c) 2003-2016 Emil Mikulic.
listening on: http://0.0.0.0:80/
2017-12-12 10:46:17,105:INFO:__main__:1211: Generating new account key
TOS hash mismatch. Found: cc88d8d9517f490191401e7b54e9ffd12a2b9082ec7a1d4cec6101f9f1647e7b.

Debugging tips: -v improves output verbosity. Help is available under --help.
-----> Certificate retrieval failed!
-----> Disabling ACME proxy for ultro-backend-dev...
       done

**Comment by danhawkes** [comment]
https://github.com/dokku/simp_le/pull/2
https://github.com/dokku/simp_le/issues/1

**Comment by rwieruch** [comment]
Ran into the same issue today. Anything we can do to merge the PR? :)

**Comment by denisviklov** [comment]
just reinstall letsencrypt plugin something like dokku plugins:destroy letsencrypt && dokku plugins install letsencrypt (see help on plugin remove not sure)

**Comment by rwieruch** [comment]
Did it work for you this way @denisviklov ? Just asking to be cautious here.

**Comment by denisviklov** [comment]
@rwieruch try that one dokku config:set --global DOKKU_LETSENCRYPT_TOS_SHA=cc88d8d9517f490191401e7b54e9ffd12a2b9082ec7a1d4cec6101f9f1647e7b

**Comment by rwieruch** [comment]
Thank you @denisviklov 👍  I am just waiting for the new version here, because I don't want to mess around with my Dokku config. At some point I will forget that I set this manually and it's kinda a crucial application stack for me.

**Comment by diegocastro** [comment]
@denisviklov Tried that and it does not work.

**Comment by josegonzalez** [comment]
Closed by #134.

**Comment by babarinde** [comment]
Hi,
@josegonzalez , does @diegocastro  recommendation fix this? or will we also have to redo this for anoother upgrade?

**Comment by beydogan** [comment]
@babarinde 

Update dokku-letsencrypt first with;

```
dokku plugin:update letsencrypt
```

then 

```
dokku config:set --global DOKKU_LETSENCRYPT_TOS_SHA=cc88d8d9517f490191401e7b54e9ffd12a2b9082ec7a1d4cec6101f9f1647e7b
```

It should fix the issue.
