### ISSUE TITLE
Can't renew app

### ISSUE THREAD

**Issue by mikeyp** [dokku/dokku-letsencrypt#141]
I'm on 0c2b00b0b2085bed6a06f8a1b964ff503ea0dcac (which is reported in the admin UI as 0.8.6) and when I try to run auto-renew, I get the following:

```
root@platform:~# dokku letsencrypt:auto-renew
=====> Auto-renewing all apps...
-----> minutiae-marketing needs renewal
=====> Let's Encrypt minutiae-marketing
/var/lib/dokku/plugins/available/letsencrypt/functions: line 171: export: --: invalid option
export: usage: export [-fn] [name[=value] ...] or export -p
```

**Comment by kurtlewis** [comment]
Hey @mikeyp did you ever figure out a workaround to this issue?

**Comment by josegonzalez** [comment]
Can you show the output of the following command:

```
dokku --trace letsencrypt:auto-renew
```

Sounds like maybe an invalid environment variable or a change in how we need to call the `config_export` command.

**Comment by kurtlewis** [comment]
I did that, and I'll exclude the output because it led me to this: https://github.com/dokku/dokku/issues/3036

It was a bad `--no-restart` environment variable.

I manually edited my app's ENV file and restarted the container and it fixed it. Thanks!

**Comment by josegonzalez** [comment]
You definitely should update dokku, thats fixed in newer versions :)
