### ISSUE TITLE
Question: wildcard certificates

### ISSUE THREAD

**Issue by woudsma** [dokku/dokku-letsencrypt#144]
In 10 days (27-02-2018) Let's Encrypt will support wildcard certificates. 👏 
Article: [Looking forward to 2018](https://letsencrypt.org/2017/12/07/looking-forward-to-2018.html)

Are you planning to update `dokku-letsencrypt` to support wildcard certificates?
I'm curious about your thoughts!

**Comment by josegonzalez** [comment]
Once the underlying libraries we use support it, we would be happy to take pull requests for it.

**Comment by nelsonic** [comment]
GOTO: https://github.com/dokku/dokku-letsencrypt/issues/148
