### ISSUE TITLE
When should we expect dokku let's encrypt wildcard certificate plugin

### ISSUE THREAD

**Issue by aadags** [dokku/dokku-letsencrypt#148]
Hi Everyone, 

I use dokku and i would like to know when to expect the wildcard certificate.

Thanks in advance.

**Comment by joshmanders** [comment]
It's a pretty tough thing to do because wildcard support requires dns validation.

**Comment by josegonzalez** [comment]
The official answer is "Whenever someone contributes a pull request for wildcard support".

As has been mentioned, letsencrypt will now require dns validation for wildcard certificates. As such, this won't be a simple thing to add, and the implementor needs to think about the workflow changes necessary.

If anyone is interested in contributing this change, please do so! I'm happy to review any pull requests related to this and other features :)

**Comment by nahtnam** [comment]
I have almost zero experience with this but one interesting thing I noticed was that with the certbot cli, it shows you what DNS settings to add, and will check only once you hit enter. Would using the certbot CLI be something that Dokku can do?

**Comment by josegonzalez** [comment]
Probably. Pull requests welcome.
