### ISSUE TITLE
Getting NET::ERR_CERT_INVALID After installation

### ISSUE THREAD

**Issue by Virviil** [dokku/dokku-letsencrypt#151]
After installing certificates for app get NET::ERR_CERT_INVALID

May be something changed in lets encrypt service?

**Comment by joshmanders** [comment]
Can we get more information?

**Comment by Virviil** [comment]
Just tell me, what to do - I’ll provide you whatever you need

**Comment by agungyuliaji** [comment]
I hope there are people here with the god eyes, to get information about dokku version, logs, os version and etc to reproduce and fix this problem 😉

**Comment by josegonzalez** [comment]
Closing. The initial issue is either already fixed or the user isn't using this anymore.

If you are having this issue, please open a new ticket.
