### ISSUE TITLE
CA marks authorization invalid after successful self-verify

### ISSUE THREAD

**Issue by benlachman** [dokku/dokku-letsencrypt#154]
I have a functioning dokku flask deploy that is accessible via a fully qualified subdomain. However, I'm having no luck getting the letsencrypt plugin working for HTTPS.

Setup:

```
$ dokku plugin:install https://github.com/dokku/dokku-letsencrypt.git
$ dokku config:set match-tracks DOKKU_LETSENCRYPT_EMAIL=my@email
$ dokku domains:add match-tracks match-tracks.service.my.tld
```

Then: 

`$ dokku letsencrypt match-tracks`

Output:

```
=====> Let's Encrypt match-tracks
-----> Updating letsencrypt docker image...
latest: Pulling from dokkupaas/letsencrypt-simp_le
Digest: <sha256>
Status: Image is up to date for dokkupaas/letsencrypt-simp_le:latest
       done updating
-----> Enabling ACME proxy for match-tracks...
-----> Getting letsencrypt certificate for match-tracks...
        - Domain 'match-tracks.service.my.tld'
darkhttpd/1.12, copyright (c) 2003-2016 Emil Mikulic.
listening on: http://0.0.0.0:80/
2018-09-04 16:01:12,769:INFO:__main__:1211: Generating new account key
2018-09-04 16:01:14,626:INFO:__main__:1305: match-tracks.service.nicemohawk.com was 
successfully self-verified
2018-09-04 16:01:14,743:INFO:__main__:1313: Generating new certificate private key
2018-09-04 16:01:16,054:ERROR:__main__:1271: CA marked some of the authorizations as 
invalid,which likely means it could not access 
http://example.com/.well-known/acme-challenge/X. 
Did you set correct path in -d example.com:path or --default_root? 
Is there a warning log entry about unsuccessful self-verification? 
Are all your domains accessible from the internet? 
Failing authorizations: <auth url>
Challenge validation has failed, see error log.

Debugging tips: -v improves output verbosity. Help is available under --help.
-----> Certificate retrieval failed!
-----> Disabling ACME proxy for match-tracks...
       done
```

I haven't been able to find the location of the logs in question, despite poking around in `/var/logs`, `/home/dokku`, etc.

I have however verified that a request is coming in for the `/.well-known/acme-challenge/XXX` path and is served with a `200` response.

Any thoughts on why this is failing after a successful self-verify?

**Comment by fruitl00p** [comment]
have you checked the url on LE itself... most of the times they publish a pretty comprehensive log of the verification....

**Comment by benlachman** [comment]
@fruitl00p I'm not 100% sure how to do that. I'm not seeing a `/etc/letsencrypt/accounts/acme-v01.api.letsencrypt.org/directory/*/regr.json` file that has the account id mentioned [here](https://letsencrypt.org/docs/account-id/).

Can you point me in the right direction?

**Comment by fruitl00p** [comment]
do you see a link to the site of LE in the output somewhere..  I'm currently recalling from memory but if I'm correct there should be some link to LE in there that shows the full certification process logs from their pov

**Comment by benlachman** [comment]
The `Failing authorizations: <auth url>` section from the output above is what I was looking for. I was thinking I'd tried to curl the url before, but I guess not. If you access it, you get a mess of json that describes their view of the cert process like you said. Mine looked like: 
```json
{
  "identifier": {
    "type": "dns",
    "value": "match-tracks.service.my.tld"
  },
  "status": "invalid",
  "expires": "2018-09-11T19:34:25Z",
  "challenges": [
    {
      "type": "tls-alpn-01",
      "status": "invalid",
      "uri": "https://acme-v01.api.letsencrypt.org/acme/challenge/XXX",
      "token": "some token"
    },
    {
      "type": "dns-01",
      "status": "invalid",
      "uri": "https://acme-v01.api.letsencrypt.org/acme/challenge/XXX",
      "token": "some token"
    },
    {
      "type": "http-01",
      "status": "invalid",
      "error": {
        "type": "urn:acme:error:dns",
        "detail": "DNS problem: SERVFAIL looking up CAA for match-tracks.service.my.tld",
        "status": 400
      },
      "uri": "https://acme-v01.api.letsencrypt.org/acme/challenge/XXX",
      "token": "some token",
      "keyAuthorization": "some key",
      "validationRecord": [
        {
          "url": "http://match-tracks.service.my.tld/.well-known/acme-challenge/XXX",
          "hostname": "match-tracks.service.my.tld",
          "port": "80",
          "addressesResolved": [
            "x.x.x.x"
          ],
          "addressUsed": "x.x.x.x"
        }
      ]
    }
  ],
<snip>
```
The issue was the lack of a `CAA` DNS record for my subdomain. You can check this directly using one of the many CAA checking tools like [this one](https://dnsspy.io/labs/caa-validator). Let's Encrypt fails if you get a `SERVFAIL` response for the domain in question. Here's a [link to the relevant docs](https://letsencrypt.org/docs/caa/) on how they handle CAA records.

I added a CAA record for my subdomain and once it propagated, everything worked like a charm. Thanks for the help.

**Comment by carlosbensant** [comment]
> The `Failing authorizations: <auth url>` section from the output above is what I was looking for. I was thinking I'd tried to curl the url before, but I guess not. If you access it, you get a mess of json that describes their view of the cert process like you said. Mine looked like:
> 
> ```json
> {
>   "identifier": {
>     "type": "dns",
>     "value": "match-tracks.service.my.tld"
>   },
>   "status": "invalid",
>   "expires": "2018-09-11T19:34:25Z",
>   "challenges": [
>     {
>       "type": "tls-alpn-01",
>       "status": "invalid",
>       "uri": "https://acme-v01.api.letsencrypt.org/acme/challenge/XXX",
>       "token": "some token"
>     },
>     {
>       "type": "dns-01",
>       "status": "invalid",
>       "uri": "https://acme-v01.api.letsencrypt.org/acme/challenge/XXX",
>       "token": "some token"
>     },
>     {
>       "type": "http-01",
>       "status": "invalid",
>       "error": {
>         "type": "urn:acme:error:dns",
>         "detail": "DNS problem: SERVFAIL looking up CAA for match-tracks.service.my.tld",
>         "status": 400
>       },
>       "uri": "https://acme-v01.api.letsencrypt.org/acme/challenge/XXX",
>       "token": "some token",
>       "keyAuthorization": "some key",
>       "validationRecord": [
>         {
>           "url": "http://match-tracks.service.my.tld/.well-known/acme-challenge/XXX",
>           "hostname": "match-tracks.service.my.tld",
>           "port": "80",
>           "addressesResolved": [
>             "x.x.x.x"
>           ],
>           "addressUsed": "x.x.x.x"
>         }
>       ]
>     }
>   ],
> <snip>
> ```
> 
> The issue was the lack of a `CAA` DNS record for my subdomain. You can check this directly using one of the many CAA checking tools like [this one](https://dnsspy.io/labs/caa-validator). Let's Encrypt fails if you get a `SERVFAIL` response for the domain in question. Here's a [link to the relevant docs](https://letsencrypt.org/docs/caa/) on how they handle CAA records.
> 
> I added a CAA record for my subdomain and once it propagated, everything worked like a charm. Thanks for the help.

WOW! This helped me a lot. I added a CAA DNS record for my subdomain ```staging.domain.tld``` to allow LetsEncrypt Certificate Authority to issue certificates.

Thank you!
