### ISSUE TITLE
Making this an official plugin

### ISSUE THREAD

**Issue by josegonzalez** [dokku/dokku-letsencrypt#16]
@sseemayer this plugin is super legit and I'd like to make it official, similar to how we handle the datastores etc.

Up to you, but would you be open to moving it into the dokku org? You obviously still get full admin access to the plugin :)

**Comment by sseemayer** [comment]
I'd be honored if this became official!

Even though this probably doesn't affect the moving of the repo, I wanted to mention that I'm working on some major changes to increase reliability at the moment that will make the plugin more reliable that will bring some changes to the usage, too. What are the expectations on API stability for official plugins?

**Comment by josegonzalez** [comment]
Basically follow semver. So whenever you release a stable 1.0.0, thats the api you need to follow until 2.0.0. New features can be added, so long as you don't break bc. That's about it.

I added you to the org, so transfer away!

**Comment by sseemayer** [comment]
Sounds good! I'll finish up my changes over the weekend and will do the transfer after.

**Comment by sseemayer** [comment]
I found some time after all and got the changes plus the move done early :smile:

**Comment by josegonzalez** [comment]
:)
