### ISSUE TITLE
Phoenix app: you must set at least one -d/--vhost

### ISSUE THREAD

**Issue by VSidhArt** [dokku/dokku-letsencrypt#160]
I'm trying to install a certificate on the phoenix application, the application is closed according to this [instruction](https://medium.com/@jonlunsford/elixir-up-and-running-with-dokku-on-digital-ocean-ce332d64224c) and this app is available at chat.example.ai. But when I'm trying `dokku letsencrypt chat
` it falls with an error
```
root@server:~# dokku letsencrypt chat                                                                                                                                                                   
=====> Let's Encrypt chat
-----> Updating letsencrypt docker image...
latest: Pulling from dokkupaas/letsencrypt-simp_le
Digest: sha256:95681f7cd659f23f451738121df9efe42ffc919e93a969781c40e936258fea72
Status: Image is up to date for dokkupaas/letsencrypt-simp_le:latest
       done updating
-----> Enabling ACME proxy for chat...
-----> Getting letsencrypt certificate for chat...
        - Domain 'chat.example.ai'
darkhttpd/1.12, copyright (c) 2003-2016 Emil Mikulic.
listening on: http://0.0.0.0:80/
You must set at least one -d/--vhost

Debugging tips: -v improves output verbosity. Help is available under --help.
-----> Certificate retrieval failed!
-----> Disabling ACME proxy for chat...
       done
```
on this server, there is also a rails application to which there is no such problem.
```
root@server:~# dokku domains:report
=====> chat domains information
       Domains app enabled:           true                     
       Domains app vhosts:            chat.example.ai              
       Domains global enabled:        false                    
       Domains global vhosts:                                  
=====> radar domains information
       Domains app enabled:           true                     
       Domains app vhosts:            rails.example.ai             
       Domains global enabled:        false                    
       Domains global vhosts:   
```

**Comment by fruitl00p** [comment]
@VadimSergeevich is this still an issue? It seems that the registraton of the URL / domain went wrong somewhere... ? (based on the error message)

**Comment by teodorlu** [comment]
Hello! I just hit this problem while using a [plugin for monorepos][1]. I checked out my `domains:report`, and found that vhosts wasn't set (but the app was still available on the subdomain clj-hellopg). I think I found a workaround.

### State before workaround

```
$ dokku domains:report clj-hellopg
=====> clj-hellopg domains information
       Domains app enabled:           false                    
       Domains app vhosts:                                     
       Domains global enabled:        false                    
       Domains global vhosts:                                  
```

### Workaround: set the domain manually

Somehow, the "automatic vhost configuration" didn't work. Perhaps the monorepo plugin would have to do that. Dunno. Regardless, I set the domain manually:

```
dokku domains:set clj-hellopg clj-hellopg.MY_DOKKU_HOST.com
```

After that, the domains report looked right:

```
$ dokku domains:report clj-hellopg
=====> clj-hellopg domains information
       Domains app enabled:           true                     
       Domains app vhosts:            clj-hellopg.MY_DOKKU_HOST.no
       Domains global enabled:        false                    
       Domains global vhosts:                                  
```

And after a `dokku letsencrypt clj-hellopg`, I've got my HTTPS. Nice!

### Conclusion

This seems unrelated to the letsencrypt plugin. Perhaps the domains plugin is a better fit?

Hope that helps!

[1]: https://github.com/notpushkin/dokku-monorepo

**Comment by josegonzalez** [comment]
Not sure what the initial problem was, but I am unable to replicate this problem now. Please feel free to make a new issue if you are still seeing this.
