### ISSUE TITLE
How to get secure websocket working

### ISSUE THREAD

**Issue by DominicTobias** [dokku/dokku-letsencrypt#162]
Thanks for this plugin it worked great, however I have no idea how to get a secure websocket working, I opened up the port and it looks like it can connect to the non-secure one, but `wss://` gives `Error in connection establishment: net::ERR_SSL_PROTOCOL_ERROR`.

I know dokku uses nginx, but in NodeJS at least it seems like people had success by using the `ca` part separately instead of bundling it into the `cert` so I'm wondering what this plugin does?

```js
app = https.createServer({
    key: fs.readFileSync(config.ssl.key),
    cert: fs.readFileSync(config.ssl.cert),
}, processRequest).listen(config.port);
```

becomes

```js
app = https.createServer({
    key: fs.readFileSync(config.ssl.key),
    cert: fs.readFileSync(config.ssl.cert),
    ca: fs.readFileSync(config.ssl.ca),
}, processRequest).listen(config.port);
```

**Comment by DominicTobias** [comment]
Nervermind, this was an issue with my Node app I've now fixed

**Comment by ismardantas** [comment]
> Nervermind, este foi um problema com o meu aplicativo Node que eu já consertei

Can you help with this?
