### ISSUE TITLE
rate limit and default domain

### ISSUE THREAD

**Issue by knzudgt** [dokku/dokku-letsencrypt#163]
As suggested in your documentation, I would like to remove the default dokku domain for my single application (still to be deployed), to avoid rate limit issues. Supposing I call my application `awesome_app`, what is the default domain added by dokku? Is it a standard domain such as `dokku.org` or instead would be `awesome_app.dokku.org`? How can I get this information? <br> (As far as I understood `dokku domains awesome_app` would list only the custom domains, while `dokku domains:report awesome_app` does not report the list of associated domains.) 

Also, what [in your documentation](https://github.com/dokku/dokku-letsencrypt#dealing-with-rate-limit) you call "default domain" is the same as the "global domain" defined in the [dokku documentation](http://dokku.viewdocs.io/dokku/configuration/domains/#customizing-hostnames)? Are you suggesting to remove the global domain?

**Comment by fruitl00p** [comment]
@knzudgt I personally have never run into the ratelimits in production, so if you're only currently using a single (new) app, this shouldnt be an issue. As for the default domain, this indeed falls back to the global domain of the dokku installation.
