### ISSUE TITLE
TLS-SNI-01 validation is reaching end-of-life

### ISSUE THREAD

**Issue by archy-bold** [dokku/dokku-letsencrypt#164]
Hi there. I recently received an email warning that some of my certificates might break as they're using TLS-SNI-01 validation, which is reaching end-of-life. Here's the key information that was sent in the email:

> TLS-SNI-01 validation is reaching end-of-life. It will stop working
temporarily on February 13th, 2019, and permanently on March 13th, 2019.
Any certificates issued before then will continue to work for 90 days
after their issuance date.
>
> You need to update your ACME client to use an alternative validation
method (HTTP-01, DNS-01 or TLS-ALPN-01) before this date or your
certificate renewals will break and existing certificates will start to
expire.

Will the `auto-renew` command handle renewing without issue or do I need to change the validation type manually?

**Comment by fruitl00p** [comment]
@archy-bold are you using the [latest version of the plugin](https://github.com/dokku/dokku-letsencrypt/#upgrading-from-previous-versions) ?

TLS-SNI-01 hasn't actively been supported by LE since 2018 (IIRC) and AFAIK this plugin has been using HTTP-01 for a while now... ?

**Comment by archy-bold** [comment]
Thanks for the response @fruitl00p; I should really have checked that first. I was on version 0.8.6 and updated to 0.8.8.

Is there a way to check the validation method used for a certificate?

**Comment by fruitl00p** [comment]
@archy-bold if you can see the output, it should show a link to letsencrypt where you can see the full logs for the request / transaction...

**Comment by archy-bold** [comment]
@fruitl00p Ok thanks, no issues so I'm assuming everything is ok now.
