### ISSUE TITLE
`TOS hash mismatch` when adding SSL to app.

### ISSUE THREAD

**Issue by jonatkinson** [dokku/dokku-letsencrypt#165]
Hello. I'm seeing a `TOS hash mismatch` when adding SSL to my appliction `www`. Yes, then naming seems confusing, but my application really is called 'www', and I've mounted it at 'www.jonatkinson.co.uk'. I'm using Dokku 0.4.15.

```user@platform:~# dokku letsencrypt www -v
=====> Let's Encrypt www...
-----> Updating letsencrypt docker image...
latest: Pulling from dokkupaas/letsencrypt-simp_le
Digest: sha256:95681f7cd659f23f451738121df9efe42ffc919e93a969781c40e936258fea72
Status: Image is up to date for dokkupaas/letsencrypt-simp_le:latest
       done
-----> Enabling ACME proxy for www...
-----> Getting letsencrypt certificate for www...
        - Domain 'www.jonatkinson.co.uk'
darkhttpd/1.12, copyright (c) 2003-2016 Emil Mikulic.
listening on: http://0.0.0.0:80/
2019-01-29 11:39:54,319:INFO:__main__:1211: Generating new account key
TOS hash mismatch. Found: cc88d8d9517f490191401e7b54e9ffd12a2b9082ec7a1d4cec6101f9f1647e7b.

Debugging tips: -v improves output verbosity. Help is available under --help.
-----> Certificate retrieval failed!
-----> Disabling ACME proxy for www...
       done
```

I assume this refers to the LetsEncrypt terms of service agreement?

**Comment by jonatkinson** [comment]
On further inspection, it looks like that error is being generated in the letsencrypt docker container itself. I'm going to keep investigating.

**Comment by fruitl00p** [comment]
@jonatkinson This seems to be an old issue that was fixed a while ago. Are you sure you're using the [latest version of dokku-letsencrypt](https://github.com/dokku/dokku-letsencrypt/#upgrading-from-previous-versions)?

**Comment by rorykoehler** [comment]
Did you resolve this?

**Comment by josegonzalez** [comment]
This should be fixed if you update your dokku-letsencrypt plugin.
