### ISSUE TITLE
On cloning app, cloned certificate results in invalid nginx.conf

### ISSUE THREAD

**Issue by robinwo** [dokku/dokku-letsencrypt#166]
When app gets cloned, it also clones letsencrypt certificates. These certificates are however linked to a different domain. On trying to build the app, this results in an invalid nginx.conf file (unable to complete build).

`nginx: [emerg] BIO_new_file("/home/dokku/<app>/tls/server.crt") failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/home/dokku/<app>/tls/server.crt','r') error:2006D080:BIO routines:BIO_new_file:no such file)
nginx: configuration file /etc/nginx/nginx.conf test failed`

Steps to repro are:
1. Create app
2. Assign certificate
3. Clone app (php/apache2 my case)
4. Try to build

**Comment by josegonzalez** [comment]
This should be fixed in upstream now, as we delete the tls directory and nginx conf for new clones.
