### ISSUE TITLE
Unhandled error if the domain includes uppercase letter

### ISSUE THREAD

**Issue by Schlepptop** [dokku/dokku-letsencrypt#168]
Letsencrypt excepts with
```UnexpectedUpdate: AuthorizationResource(body=Authorization(status=Status(pending), etc...)``` 
if there are uppercase letters in the domain to be used.

In my case it was fixed by correcting the domain to be lowercase with `dokku domains:set`.

**Comment by fruitl00p** [comment]
I can understand that it's weird from a user POV but domainnames by definition are lowercased (IIRC) So i would've expected dokku to normalize the domain used to always be lowercased anyway... 

@josegonzalez does dokku internally normalize the used / requested domain anywhere? (and/or should it?)

**Comment by josegonzalez** [comment]
Dokku does not. I think we'll probably fuck up something like... unicode domains or something.

I wonder if the new lego integration will fix this?

**Comment by josegonzalez** [comment]
Yeah, looks like it normalizes the domain.

**Comment by josegonzalez** [comment]
Closing as there is a pull request open.
