### ISSUE TITLE
The client sent an unacceptable anti-replay nonce

### ISSUE THREAD

**Issue by muenzel** [dokku/dokku-letsencrypt#171]
Hello together,

today I got an strange error which states:

`ACME server returned an error: urn:acme:error:badNonce :: The client sent an unacceptable anti-replay nonce :: JWS has invalid anti-replay nonce Jm-GbtiefbZYxTe64UUAOlhTVWJqWq1IVbks_98-fjY`

It tried it several times the last 6 hours, removed the certificate and did a `letsencrypt:cleanup ` nothing works. The strange thing is, when I switch to staging, everything works as expected.

If anyone has an idea, I would really appreciate that :)

Btw. Thank you for your awesome work on Dokku.

**Comment by fruitl00p** [comment]
@muenzel Based on public forums from LetsEncrypt and others this is most likely a network error between them and yourself (proxy, DNS outages and other causes) Have you looked at the public LetsEncrypt page for your certificate request? This allows you to see the verification / communication process and where the problem might lie... 

Hope this helps

(if you can't find anything, make sure you have the latest version of the plugin to rule out version issues)

**Comment by muenzel** [comment]
@fruitl00p Thank you for your fast response. No, I don't think we changed something recently, as there are a couple of apps running in production. The issue first occurred today, and in staging environment it works.

What do you mean with "Have you looked at the public LetsEncrypt page for your certificate request?" I wasn't aware that I can do this, but also haven't found anything on their site. Do you have a link?

**Comment by fruitl00p** [comment]
@muenzel IIRC the output usually shows some url to LetsEncrypt's site... (where the request is logged) and you should be able to hit that url to take a look at the `logs`... 

However i can't find any examples...  In my experience if something went wrong i could see the 'validation' url (or something like it) which would point me to a page / json feed by LE where i could see how the domain got validated in the first place... Too bad I just can't find any history of that anywhere...

**Comment by muenzel** [comment]
No there isn't such a link in the logs. However after 8 hours it seems to work again, as I could get the cert without an issue. Directly after the success, I tried to pull a cert for another new app and got the bad nonce error again, 5 minutes alter it works. Strange, but certainly nothing to do with this plugin. So I can close this issue here. @fruitl00p  Thanks again for your help.

**Comment by fruitl00p** [comment]
@muenzel glad to hear it helped. I've been looking through the various output on my side as well and it seems LE isnt publishing the data anymore (at least where i can find it...)

As it `worked magically` for you now, the original guess (network/dns/proxy) might still be the culprit...
