### ISSUE TITLE
letsencrypt stop working

### ISSUE THREAD

**Issue by Rigo85** [dokku/dokku-letsencrypt#172]
- dokku version: 0.16.0.
- OS: "18.04.2 LTS (Bionic Beaver)"

Hi there!, the command `dokku letsencrypt app` was working, I have 2 apps with SSL, but now just stop working, don't know why.

```
=====> Let's Encrypt demo-ssl
-----> Updating letsencrypt docker image...
latest: Pulling from dokkupaas/letsencrypt-simp_le
Digest: sha256:95681f7cd659f23f451738121df9efe42ffc919e93a969781c40e936258fea72
Status: Image is up to date for dokkupaas/letsencrypt-simp_le:latest
       done updating
-----> Enabling ACME proxy for demo-ssl...
-----> Getting letsencrypt certificate for demo-ssl...
        - Domain 'demo-ssl.services.asescomrj.com'
darkhttpd/1.12, copyright (c) 2003-2016 Emil Mikulic.
listening on: http://0.0.0.0:80/
2019-05-09 22:02:54,333:INFO:__main__:1211: Generating new account key
2019-05-09 22:05:09,026:ERROR:acme.challenges:324: Unable to reach http://demo-ssl.services.asescomrj.com/.well-known/acme-challenge/gaGpiJjgjmbgdJ3lWCQWys_Hcztg1XUJPCR_WOIUXIk: HTTPConnectionPool(host='demo-ssl.services.asescomrj.com', port=80): Max retries exceeded with url: /.well-known/acme-challenge/gaGpiJjgjmbgdJ3lWCQWys_Hcztg1XUJPCR_WOIUXIk (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1bcf4f3d50>: Failed to establish a new connection: [Errno 110] Operation timed out',))
2019-05-09 22:05:09,027:WARNING:__main__:1303: demo-ssl.services.asescomrj.com was not successfully self-verified. CA is likely to fail as well!
ACME server returned an error: urn:acme:error:badNonce :: The client sent an unacceptable anti-replay nonce :: JWS has invalid anti-replay nonce 9Pofl3o_FVq8v6ubFib9-q_tWI_DLpsnsfncWXTlgbY


Debugging tips: -v improves output verbosity. Help is available under --help.
-----> Certificate retrieval failed!
-----> Disabling ACME proxy for demo-ssl...
       done
```

**Comment by fruitl00p** [comment]
@Rigo85 this seems to be a connection issue between LE and your server to verify the SSL request. Could be caused by a  number of issues (most likely from my experience: DNS)

**Comment by Rigo85** [comment]
Hi, there are some command to check different step of letsencrypt process? just to narrow where the issue is coming from. I can connect to the apps in the dokku server, I can resolve domains name inside dokku server, I don't know where to look.

**Comment by Rigo85** [comment]
`dokku letsencrypt app` create this file `cat /home/dokku/<app>/letsencrypt/certs/<id>/config`:

`--server https://acme-v01.api.letsencrypt.org/directory --email <email> --tos_sha256 <sha256>  -d <app>.example.com`.

There is any manually check that I can do with this file?

**Comment by muenzel** [comment]
I have the same issue: badNonce. After a lot of retries I managed to get certs for 3 apps, but after that tiny window where I could pull certs, it have this badNonce error again and no idea what to do. This issue persists for over a week now.

In the letsencrypt forum, there are also a couple of issues related to the badNonce error, e.g. https://community.letsencrypt.org/t/jws-has-invalid-anti-replay-nonce/93100

It gets suggested there, that "a client SHOULD retry the request using the new nonce." But I have no idea how to archive this and/or if this is even possible through the plugin.

**Comment by muenzel** [comment]
I am using this plugin for over 3 year now, having 50+ apps running and never experienced a problem before. No changes in environment either. Simply stopped working for me with this persisting badNonce error.

**Comment by muenzel** [comment]
Worked once today after 4 failures for the same app.

**Comment by Rigo85** [comment]
> Worked once today after 4 failures for the same app.

I'm happy for you, I'm still looking the issue.

**Comment by muenzel** [comment]
I am pretty sure that this has nothing to do with the server settings, DNS or whatsoever. I would bet if you set the environment to staging you can pull a cert without an issue. But that doesn't help you much.

**Comment by Rigo85** [comment]
> I am pretty sure that this has nothing to do with the server settings, DNS or whatsoever. I would bet if you set the environment to staging you can pull a cert without an issue. But that doesn't help you much.

I will try the staging, the odd it's I have at least 3 app with SSL working.

**Comment by Rigo85** [comment]
Hi there, just to close this issue, i will give a little explanation, my dokku server is behind a firewall with some NAT rules for the ports, so after activate `dokku trace on` and get the full docker command for example: `docker run --rm -p <random port>:80 -v /path/xxx etc etc`, I check the [ACME port](https://github.com/dokku/dokku/blob/c786b9e45eaaa2d2aacedf215cab2f45900ff425/plugins/common/functions#L727), I just needed to ask to open the range 1025-65535, now work like a charm!

**Comment by muenzel** [comment]
@Rigo85 Thanks for your explanation. Glad that it worked for you. I checked my config and realized that indeed that port range isn't open or being forwarded. So I changed the firewall accordingly and check that the range is open by created an dokku app which listens to a port in that range. (Didn't work before changing firewall, did work afterwards ... so I assume that the port range is now open).

Sadly that doesn't change anything for me. Same error: badNonce. I would have wondered anyway how this fits the behavior that I observe:

- It worked before without change in environment till day X
- After day X it works sometimes after a lot of retries
- Also it works in staging environment

Hope opening port range fixed this issue permanently for you, but I assume that you just hit a lucky spot where it works.

As I have 12 apps where the certs expires next week I have to do it manually via sslforfree.com :/

**Comment by Rigo85** [comment]
> @Rigo85 Thanks for your explanation. Glad that it worked for you. I checked my config and realized that indeed that port range isn't open or being forwarded. So I changed the firewall accordingly and check that the range is open by creating a dokku app which listens to a port in that range. (Didn't work before changing firewall, did work afterwards ... so I assume that the port range is now open).
> 
> Sadly that doesn't change anything for me. Same error: badNonce. I would have wondered anyway how this fits the behavior that I observe:
> 
> * It worked before without change in environment till day X
> * After day X it works sometimes after a lot of retries
> * Also it works in staging environment
> 
> Hope opening port range fixed this issue permanently for you, but I assume that you just hit a lucky spot where it works.
> 
> As I have 12 apps where the certs expire next week I have to do it manually via sslforfree.com :/

Hi @muenzel , after reading your reply I felt intrigued so I test dokku letsencrypt again and it's work, so:

- do a double check to your DNS A-record that resolve ok *.yourdomain.com.
- I recommend you to do `dokku trace on`, get the full docker command line for simp_le and run it again manually, that can give you a localized issue.
- use the same random port used by simp_le(you need trace on to see the full command line), try to connect to a webapp listening in that port from internet.
- I have open these ports too: 80, 443, 22, 5000, 5432, 6379.

Please do all this checks and tell me about it.

**Comment by muenzel** [comment]
I've successfully pulled 10 certs last week and 6 today, without a single issue. Again, with no change in environment. So it seems that all systems are back to normal. But what remains is the uncomfortable feeling that problems can emerge from nowhere at any time again.
