### ISSUE TITLE
The plugin has stopped working and returns the following error

### ISSUE THREAD

**Issue by ismardantas** [dokku/dokku-letsencrypt#181]
ACME server returned an error: urn:acme:error:unauthorized :: The client lacks sufficient authorization :: Account creation on ACMEv1 is disabled. Please upgrade your ACME client to a version that supports ACMEv2 / RFC 8555. See https://community.letsencrypt.org/t/end-of-life-plan-for-acmev1/88430 for details.

**Comment by germanp** [comment]
Anyone figured out a workaround?

**Comment by nabati** [comment]
Any thoughts on a solution @sseemayer or @josegonzalez ?

**Comment by nabati** [comment]
I guess this is also a relevant thread with more information related to the issue; https://github.com/dokku/dokku-letsencrypt/issues/147

**Comment by dean1012** [comment]
Work was done here @nabati https://github.com/dokku/dokku-letsencrypt/issues/183#issuecomment-541274696

**Comment by josegonzalez** [comment]
Duplicate of #183 (and fixed by @dean1012).

**Comment by germanp** [comment]
Thanks, I updated and it works ok.
