### ISSUE TITLE
Nginx Error After Running letsencrypt

### ISSUE THREAD

**Issue by bendangelo** [dokku/dokku-letsencrypt#182]
I just ran the letsencrypt command and got this error. I have no global host set, only a vhost if that helps. Running the latest dokku version.

```
-----> Creating https nginx.conf
-----> Running nginx-pre-reload
       Reloading nginx
nginx: [emerg] PEM_read_bio_DHparams("/etc/nginx/dhparam.pem") failed (SSL: error:0909006C:PEM routines:get_name:no start line:Expecting: DH PARAMETERS)
nginx: configuration file /etc/nginx/nginx.conf test failed
-----> Configuring sub.app.com...(using built-in template)
-----> Creating https nginx.conf
-----> Running nginx-pre-reload
       Reloading nginx
nginx: [emerg] PEM_read_bio_DHparams("/etc/nginx/dhparam.pem") failed (SSL: error:0909006C:PEM routines:get_name:no start line:Expecting: DH PARAMETERS)
nginx: configuration file /etc/nginx/nginx.conf test failed
```

**Comment by josegonzalez** [comment]
Do you have a valid `/etc/nginx/dhparam.pem` file? That seems like an nginx error, not a letsencrypt issue.

**Comment by bendangelo** [comment]
How can I check that?

**Comment by bendangelo** [comment]
Ok I just shelled into the container. There is no `/etc/nginx` directory. What do you think is happening?

**Comment by almereyda** [comment]
In Dokku, nginx is run directly from the host system. Please check http://dokku.viewdocs.io/dokku/configuration/nginx/ and associated configuration.

Do generate `dhparam.pem` run

    sudo openssl dhparam -out /etc/ssl/certs/dhparam.pem 2048

I suppose this is not a `dokku-letsencrypt` issue and can therefore be closed.

**Comment by bendangelo** [comment]
Thanks I will try this out.
