### ISSUE TITLE
Can not locate config

### ISSUE THREAD

**Issue by dean1012** [dokku/dokku-letsencrypt#186]
@josegonzalez unintended issue here...

`/var/lib/dokku/plugins/enabled/letsencrypt/subcommands/default: line 6: /var/lib/dokku/plugins/enabled/letsencrypt/subcommands/config: No such file or directory`

I'll submit a pull request fixing this really quickly.

**Comment by dean1012** [comment]
Until this is merged, the `letsencrypt` and `letsencrypt:revoke` commands will cause an error.

**Comment by josegonzalez** [comment]
Closed by #187 and released in 0.9.1.
