### ISSUE TITLE
Release tagging

### ISSUE THREAD

**Issue by dean1012** [dokku/dokku-letsencrypt#188]
Is there a particular reason we still have v0.8.7 marked as latest release?

I believe we should mark 0.9.1 as latest release to encourage adoption of the newest version and ACME v2.

**Comment by dean1012** [comment]
On a side note, we may want to pull release 0.9.0 completely as it was inoperable without the latest hotfix.

**Comment by phillipmalboeuf** [comment]
I would agree, especially now that account creation on ACMEv1 is disabled. Took me a little while to figure out what was wrong.

**Comment by josegonzalez** [comment]
0.9.1 was updated in the GH ui as a release.
