### ISSUE TITLE
Add command to clean up stale certificates / keys

### ISSUE THREAD

**Issue by sseemayer** [dokku/dokku-letsencrypt#19]
Since 68a53caf08dae960ab4438b820e3665fc890fa5d, account keys, private keys and certificates are stored in a subdirectory whose name is generated from the parameters that are passed to the simp_le client. Since every configuration change will thus result in a new folder being created, it would be nice to have a command to remove all old certificates that are not linked to by the `$APP_ROOT/letsencrypt/certs/current` symlink.

**Comment by michaelgold** [comment]
I found a related issue:
If the certificate is revoked and recreated the folder `$APP_ROOT/letsencrypt` needs to be removed manually. Otherwise the plugin will fail with an error like this:

```
ERROR:__main__:1260: CA marked some of the authorizations as invalid, which likely means it could not access http://example.com/.well-known/acme-challenge/X. Did you set correct path in -d example.com:path or --default_root? Is there a warning log entry about unsuccessful self-verification? Are all your domains accessible from the internet? Failing authorizations: https://acme-v01.api.letsencrypt.org/acme/authz/lEjwlqp1xLt8lqao6ZMRsL0Is7TguG7zBI4W847BaCg
Challenge validation has failed, see error log.
```

**Comment by sseemayer** [comment]
This is very strange, normally [this code in letsencrypt_acme_revoke](https://github.com/dokku/dokku-letsencrypt/blob/master/functions#L310-L317) should take care of moving revoked certificates out of the way. Could you include steps to reproduce this and possibly a gist of the `dokku letsencrypt:revoke myapp` and `dokku letsencrypt myapp` commands running with `dokku trace` enabled?

**Comment by haywirez** [comment]
Getting the same error :cry:

**Comment by sseemayer** [comment]
@michaelgold and @haywirez , this issue is to add a feature to dokku-letsencrypt - can you please create a new issue? 

To help me debug this, please include a gist of the `dokku letsencrypt myapp` command output **with `dokku trace on`** enabled.
