### ISSUE TITLE
Account creation on ACMEv1 is disabled

### ISSUE THREAD

**Issue by diogocaetano** [dokku/dokku-letsencrypt#191]
deployer@telemrpa-production:~$ dokku letsencrypt front
=====> Let's Encrypt front
-----> Updating letsencrypt docker image...
latest: Pulling from dokkupaas/letsencrypt-simp_le
Digest: sha256:95681f7cd659f23f451738121df9efe42ffc919e93a969781c40e936258fea72
Status: Image is up to date for dokkupaas/letsencrypt-simp_le:latest
       done updating
-----> Enabling ACME proxy for front...
-----> Getting letsencrypt certificate for front...
        - Domain 'telemrpa.capyba.com'
        - Domain 'app.telemrpa.com.br'
        - Domain 'app.telemrpa.com'
darkhttpd/1.12, copyright (c) 2003-2016 Emil Mikulic.
listening on: http://0.0.0.0:80/
2019-11-11 18:04:33,084:INFO:__main__:1211: Generating new account key
ACME server returned an error: urn:acme:error:unauthorized :: The client lacks sufficient authorization :: Account creation on ACMEv1 is disabled. Please upgrade your ACME client to a version that supports ACMEv2 / RFC 8555. See https://community.letsencrypt.org/t/end-of-life-plan-for-acmev1/88430 for details.

Debugging tips: -v improves output verbosity. Help is available under --help.
-----> Certificate retrieval failed!
-----> Disabling ACME proxy for front...
       done

Anyone can help?

**Comment by kbuilds** [comment]
I am getting this as well.

Usually @josegonzalez is the guy who knows how to get things done for Dokku. Hopefully he is around.

**Comment by kbuilds** [comment]
Looks like they officially ended production support of ACMEv1 on 11/08/2019:

![Screenshot from 2019-11-11 15-44-43](https://user-images.githubusercontent.com/7346571/68619858-42c67b00-049a-11ea-9c27-e2bbd178ece2.png)

**Comment by josegonzalez** [comment]
Is there a pull request for this?

**Comment by kbuilds** [comment]
Dammit, @josegonzalez, you're totally right. #184 should fix this. I should have looked there.

@diogocaetano To fix the issue:

On the Dokku box: `sudo dokku plugin:update letsencrypt`

**Comment by josegonzalez** [comment]
Closing. Please upgrade to 0.9.1 to get the fix.

**Comment by diogocaetano** [comment]
That's works! Thanks @kbuilds and @josegonzalez. You're awesome.
