### ISSUE TITLE
TLS 1.3 is not working

### ISSUE THREAD

**Issue by jankeesvw** [dokku/dokku-letsencrypt#192]
Sorry if I'm opening an issue in the wrong repository, but I have an issue I can't figure out. 

I deployed an application with Dokku using the Digital Ocean one click droplet. Everything seems to work fine, but some people tell me that the certificate is invalid. It seems that TLS 1.3 is not working, I also see that when I run a scan on: 

https://www.ssllabs.com/ssltest/analyze.html?d=rssmailer.app

![image](https://user-images.githubusercontent.com/167882/69479679-45ad5e00-0e00-11ea-8a6b-bb520b3590ae.png)

I tried looking this up on StackOverflow but I can't figure out what's going on.

**Comment by josegonzalez** [comment]
The SSL Ciphers that Dokku provisions may not work with those devices. Dokku recently updated them [here](https://github.com/dokku/dokku/pull/3662).

This can be changed by modifying the `/etc/nginx/conf.d/dokku.conf` file, but that must be changed on every deploy. See https://github.com/dokku/dokku/issues/3674 for an issue tracking the potential to change it once.

You can get around this by adding your cipher list to `/home/dokku/APP/nginx.conf.d/ciphers.conf` - where `APP` is your app name - and reloading nginx.

Closing as this isn't a bug with dokku-letsencrypt and there is an issue upstream to track cipher changing.

**Comment by jankeesvw** [comment]
Thanks @josegonzalez, with your comment I was able to fix the issue. 

I did a [dokku-update](http://dokku.viewdocs.io/dokku/getting-started/upgrading/#security-updates) which upgraded from:

```
$ dokku -v
dokku version 0.17.9
```

to:
```
$ dokku -v
dokku version 0.19.9
```

That solved my issue. TLS 1.3 now works!
