### ISSUE TITLE
"dokku plugin:update letsencrypt" not working

### ISSUE THREAD

**Issue by CruelMoney** [dokku/dokku-letsencrypt#194]
This issue might belong in the dokku repo, but I haven't experienced this issue with other plugins.

I'm trying to update the letsencrypt plugin from v0.8.6 to v0.9.1, but the command finishes without any response and the version stays the same. Also tried to uninstall and install the plugin again, but plugin:uninstall command does not work either.

Running dokku v0.18.3.

Any way to uninstall manually or something?

**Comment by CruelMoney** [comment]
Oh and I did run it as sudo

**Comment by josegonzalez** [comment]
What is the output of the command with the `--trace` flag? As in:

```
sudo dokku --trace plugin:update letsencrypt
```

Also, can you show the output of:

```
git -C /var/lib/dokku/plugins/enabled/letsencrypt status
```

**Comment by CruelMoney** [comment]
@josegonzalez thanks for the incredible support as always 


`
sudo dokku --trace plugin:update letsencrypt

+ source /var/lib/dokku/core-plugins/available/common/functions
++ set -eo pipefail
++ [[ -n 1 ]]
++ set -x
+ [[ ! -n '' ]]
+ source /var/lib/dokku/core-plugins/available/common/functions
++ set -eo pipefail
++ [[ -n 1 ]]
++ set -x
+ [[ plugin:update =~ (ssh-keys:add|ssh-keys:remove) ]]
+ source /var/lib/dokku/plugins/available/plugin/internal-functions
++ set -eo pipefail
++ [[ -n 1 ]]
++ set -x
++ source /var/lib/dokku/core-plugins/available/common/functions
+++ set -eo pipefail
+++ [[ -n 1 ]]
+++ set -x
+ plugin_update_cmd plugin:update letsencrypt
+ declare 'desc=updates plugin to optional committish and calls update plugin trigger via command line'
+ local cmd=plugin:update
+ [[ -n letsencrypt ]]
+ local PLUGIN=letsencrypt
+ local PLUGIN_COMMITTISH=
+ plugn update letsencrypt ''
`

`
it -C /var/lib/dokku/plugins/enabled/letsencrypt status

On branch master
Your branch is behind 'origin/master' by 22 commits, and can be fast-forwarded.
  (use "git pull" to update your local branch)
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

        modified:   functions

no changes added to commit (use "git add" and/or "git commit -a")
`

**Comment by josegonzalez** [comment]
Looks like you have a modified file - `functions` - so the git command isn't doing anything. You probably want to checkout the changes in that repo and then run the update.

```
git -C /var/lib/dokku/plugins/enabled/letsencrypt checkout -- functions
```

I would also open a bug in `dokku/plugn` to surface an error if a git repository has unstaged changes and a user wants to update/uninstall. Not sure why uninstall would fail.

**Comment by CruelMoney** [comment]
Also 

```
/var/lib/dokku/plugins/enabled/letsencrypt$ git diff functions
diff --git a/functions b/functions
index faef153..dadc4e2 100755
--- a/functions
+++ b/functions
@@ -149,7 +149,7 @@ letsencrypt_configure_and_get_dir() {
     domain_args="$domain_args -d $domain"
   done
 
-  local config="--server $server --email $DOKKU_LETSENCRYPT_EMAIL --tos_sha256 <HIDDEN_HASH_1>  $domain_args"
+  local config="--server $server --email $DOKKU_LETSENCRYPT_EMAIL --tos_sha256 <HIDDEN_HASH_2> $domain_args"
 
   local config_hash=$(echo "$config" | sha1sum | awk '{print $1}')
   local config_dir="$le_root/certs/$config_hash"; mkdir -p "$config_dir"
```

**Comment by CruelMoney** [comment]
Yup, worked to checkout the changes, thanks a lot @josegonzalez !

**Comment by rasenderhase** [comment]
I think, some people might have this issue, because they changed `functions` locally. See #204
