### ISSUE TITLE
error 20 at 0 depth lookup: unable to get local issuer certificate

### ISSUE THREAD

**Issue by chriso0710** [dokku/dokku-letsencrypt#199]
Hi there,

the letsencrypt plugin is fantastic! 
But I have a small issue with dokku's cert check. This is the message I get for every installed letsencrypt certificate:

```
$ dokku certs:report

CN = www.XXX.de
error 20 at 0 depth lookup: unable to get local issuer certificate
=====> XXX ssl information
       Ssl dir:                       /home/dokku/XXX/tls
       Ssl enabled:                   true                     
       Ssl hostnames:                 www.XXX.de        
       Ssl expires at:                Jul  1 19:00:29 2020 GMT 
       Ssl issuer:                    C = US, O = Lets Encrypt, CN = Lets Encrypt Authority X3
       Ssl starts at:                 Apr  2 19:00:29 2020 GMT 
       Ssl subject:                   subject=CN = www.XXX.de
       Ssl verified:                  self signed              
CN = www.XXXYYY.de
error 20 at 0 depth lookup: unable to get local issuer certificate
...
```

I'm using dokku 0.20.0 with the latest letsencrypt plugin on a fresh DO server with ubuntu 18.04. 
The error does not seem to be a real problem. SSL and the certs work without any problems in the browsers. As I understand openssl outputs this error message, maybe because of a missing intermediate cert? Any ideas? Thank you!

**Comment by Stivaros** [comment]
I'm having the same issue but I think it's having an effect. I could access the server via http but now that I've installed the certs it redirects to https, which times out.

**Comment by juniovitorino** [comment]
+1

> I'm having the same issue but I think it's having an effect. I could access the server via http but now that I've installed the certs it redirects to https, which times out.

**Comment by josegonzalez** [comment]
The error message has nothing to do with blocking requests to your app. My guess is we aren't being sent a full chain or something, and the command we're using to verify via openssl doesn't take that into account.

Make sure you have allowed port 443 on your server (ufw/iptables, as well as any cloud provider you might be using).

**Comment by Stivaros** [comment]
Yes, sorry, I should have updated. I am using AWS Lightsail which enables HTTP (80) & SSH (22) traffic by default but not HTTPS (443). Upon checking everything twice and then entirely deleting and recreating my entire instance, I noticed and enabled it. Sometimes you've got to learn the hard way 😁

**Comment by josegonzalez** [comment]
Closing as there is a fix upstream. Please post a new issue if you have troubles after we merge/release the above and you've updated Dokku.
