### ISSUE TITLE
Cannot get certificate for wildcard subdomain

### ISSUE THREAD

**Issue by murbanowicz** [dokku/dokku-letsencrypt#203]
I am hitting issue while trying to get SSL from LE for my app:

```
new order :: Cannot issue for ".mydomain.com": Domain name can not have two dots in a row (a│
nd 1 more problems. Refer to sub-problems for more information.)   
```

This is the notation required by dokku  and it works without LE, but I cannot get SSL for this domain :/

**Comment by josegonzalez** [comment]
Wildcard certificate retrieval cannot be done at this time with this plugin. There is some _general_ support for it - we've upgraded underlying libraries - but it requires DNS integration which isn't done at this time.

**Comment by murbanowicz** [comment]
Thank you for information. Do you expect it to be done soon or not likely to happen?

**Comment by josegonzalez** [comment]
It'll happen when someone gets to it (I don't have a use-case so I won't be working on it).

I believe there is a community user that is interested and actively working on it, I just merged a PR from them on the docker-letsencrypt repo to support the underlying tool for wildcard support.

**Comment by josegonzalez** [comment]
If you are interested in sponsoring the work, see [this document for more details](https://github.com/dokku/.github/blob/master/SPONSORING.md).
