### ISSUE TITLE
SSL Broken only Safari Desktop and iOS all browsers 

### ISSUE THREAD

**Issue by juniovitorino** [dokku/dokku-letsencrypt#206]
## Description of problem

- Digital Ocean Droplet (Ubuntu Dokku 0.17.9 on 18.04)
- WordPress
- Dokku Let's Encrypt Plugin

### How reproducible

Access https://store.prod.panere.com.br

### Steps to Reproduce

1. Open browser Safari on desktop or Chrome/Safari on iOS
2. Hit the URL https://store.prod.panere.com.br
3. Unloaded App
4. Open Chrome
5. Hit the same URL URL https://store.prod.panere.com.br

#### Actual Results

![Screen Shot 2020-07-02 at 08 53 27](https://user-images.githubusercontent.com/22594/86355746-8c3e2300-bc41-11ea-972b-0e50801d6cbd.png)

#### Expected Results

![Screen Shot 2020-07-02 at 08 54 25](https://user-images.githubusercontent.com/22594/86355829-aa0b8800-bc41-11ea-9170-f8758da14a1c.png)

## Environment Information

dokku apps:report
Will connect to dokku@prod.panere.com.br:store
apps:report store
=====> store app information
       App dir:                       /home/dokku/store
       Git sha:                       3fc42803
       Deploy source:                 git
       Locked:                        false

### CERTS Output

dokku certs:report
Will connect to dokku@prod.panere.com.br:store
certs:report store
CN = store.prod.panere.com.br
error 20 at 0 depth lookup: unable to get local issuer certificate
=====> store ssl information
       Ssl dir:                       /home/dokku/store/tls
       Ssl enabled:                   true
       Ssl hostnames:                 store.prod.panere.com.br
       Ssl expires at:                Sep 30 10:44:03 2020 GMT
       Ssl issuer:                    C = US, O = Lets Encrypt, CN = Lets Encrypt Authority X3
       Ssl starts at:                 Jul  2 10:44:03 2020 GMT
       Ssl subject:                   subject=CN = store.prod.panere.com.br
       Ssl verified:                  self signed

I'm not really seeing what's is wrong. 

This report says "No trusted Certificate".

https://check-your-website.server-daten.de/?q=store.prod.panere.com.br

**Error - Certificate isn't trusted, RemoteCertificateNameMismatch**

**Comment by JuergenAuer** [comment]
> This report says "No trusted Certificate".
> 
> https://check-your-website.server-daten.de/?q=store.prod.panere.com.br
> 
> Error - Certificate isn't trusted, RemoteCertificateNameMismatch

That's because your DNS has www defined, but your certificate has only the non-www version.

Check

https://megamorf.gitlab.io/2019/08/27/safari-nsposixerrordomain-100-error-with-nginx-and-apache.html

to see if that helps.

**Comment by juniovitorino** [comment]
> > This report says "No trusted Certificate".
> > https://check-your-website.server-daten.de/?q=store.prod.panere.com.br
> > Error - Certificate isn't trusted, RemoteCertificateNameMismatch
> 
> That's because your DNS has www defined, but your certificate has only the non-www version.
> 
> Check
> 
> https://megamorf.gitlab.io/2019/08/27/safari-nsposixerrordomain-100-error-with-nginx-and-apache.html
> 
> to see if that helps.

Interestingly I previously tried with www and non-www and didn't work also. I disabled http2 module and it works now, but I gonna give it a try again following this article. Thanks so much @JuergenAuer.

**Comment by juniovitorino** [comment]
> > This report says "No trusted Certificate".
> > https://check-your-website.server-daten.de/?q=store.prod.panere.com.br
> > Error - Certificate isn't trusted, RemoteCertificateNameMismatch
> 
> That's because your DNS has www defined, but your certificate has only the non-www version.
> 
> Check
> 
> https://megamorf.gitlab.io/2019/08/27/safari-nsposixerrordomain-100-error-with-nginx-and-apache.html
> 
> to see if that helps.

It works! Thanks so much. 🤘🏽
