### ISSUE TITLE
Docs: optional step?

### ISSUE THREAD

**Issue by guettli** [dokku/dokku-letsencrypt#212]
README:

> If you need the application to only be deployed via SSL, add a temporary certificate to your app prior to adding letsencrypt 
> by running dokku certs:generate <app> DOMAIN to make your app accessible via SSL. This is mostly a optional step as 
> the letsencrypt plugin will upgrade non-SSL apps when successful.

Somehow this is confusing for newcomers: Why should I do an optional step?

What is the simplest way if I don't have any app in Dokku yet?

Please tell us in the README. I guess today most people want to run a https only.

**Comment by josegonzalez** [comment]
You need to deploy the app. Thats a limitation of the plugin.
