### ISSUE TITLE
letsencrypt <app> fails: no "ssl_certificate" is defined for the "listen ... ssl"

### ISSUE THREAD

**Issue by rdmchr** [dokku/dokku-letsencrypt#213]
## Description of problem
I'm trying to secure my app, but the command `dokku letsencrypt <app>` throws this error:
```
nginx: [emerg] no "ssl_certificate" is defined for the "listen ... ssl" directive in /home/dokku/api/nginx.conf:2
nginx: configuration file /etc/nginx/nginx.conf test failed
```
### How reproducible
I think that I'm the only one who has this problem and its unlikely that you can easily reproduce it.

### Steps to Reproduce

1. Create an app using dokku
2. Install the Let's encrypt plugin & setup your email
3. Use dokku letsencryp <app>

#### Actual Results
It fails and throws this error:
```
nginx: [emerg] no "ssl_certificate" is defined for the "listen ... ssl" directive in /home/dokku/api/nginx.conf:2
nginx: configuration file /etc/nginx/nginx.conf test failed
```
The certificate is not deployed.
#### Expected Results
I expected it to just work and create a certificate for me.
## Environment Information
I'm deployed Dokku using the Digitalocean marketplace.

### `dokku report APP_NAME` output
https://gist.github.com/iam-moe/95db123bede46fc4f657f583be6288f1

### How (deb/make/rpm) and where (AWS, VirtualBox, physical, etc.) was Dokku installed?:
I deployed Dokku using the Digitalocean marketplace.

### Additional information

- App container inspect output (if applicable) via `dokku ps:inspect APP_NAME`
https://gist.github.com/iam-moe/ddb0ce21e786e976863fce7428c8b784
- The nginx configuration (if applicable) via `dokku nginx:show-config APP_NAME`
https://gist.github.com/iam-moe/2d61ffee4e1702541e3cff4b0422529d
- Link to the exact repository being deployed (if possible/applicable):
https://gitlab.com/octotime/api/
- Output of failing Dokku commands after running `dokku trace:on`
Please let me know if you need this information.

**Comment by kenny1har** [comment]
dokku proxy:ports-remove yourapp http:443:443

removing the http proxy for 443 should fix the error.

hope it helps.

**Comment by rdmchr** [comment]
Oh, thank you very much!

**Comment by benlachman** [comment]
Just for anyone else running into this error on v0.35.15 or later: For me, this was caused by not having a port mapping to port `80` (my app is serving http on port `3000`). 

```bash
dokku ports:add {app-name} http:80:3000
```

This allowed letsencrypt to generate a cert and adds a `https:443:3000` port mapping to the app. A rebuild of the app then successfully completed.
