### ISSUE TITLE
Crontab job lost everytime dokku is updated

### ISSUE THREAD

**Issue by Dave3of5** [dokku/dokku-letsencrypt#225]
## Description of problem

I upgrade dokku automatically through the command line on my server (apt upgrade). When this occurs the cron job is lost.

### How reproducible

Upgrade dokku via apt

### Steps to Reproduce

1.install old version of dokku via apt
2.Setup cron job
3.Upgrade dokku
4.Cron job is gone

## Environment Information

Ubuntu Bionic Beaver (18.04 LTS) (GNU/Linux 4.15.0-140-generic x86_64 )
dokku version 0.24.3

### Additional information

I think the problem is that during the upgrade process the system actually removes the dokku user.

**Comment by fruitl00p** [comment]
Which version of the letsencrypt plugin are you using?

**Comment by fruitl00p** [comment]
You might want to upgrade the plugin using ​`sudo dokku plugin:update letsencrypt` as the latest release specifically addressed this issue

**Comment by Dave3of5** [comment]
@fruitl00p ok done I'll check back later thanks.
