### ISSUE TITLE
Apps in "list", but if i tried auto-renew app it says Letsencrypt not enabled for app

### ISSUE THREAD

**Issue by Trysystems** [dokku/dokku-letsencrypt#229]
After last update plugin see apps with activated letsencrypt in "list" command, but don't see at "auto-renew". 

letsencrypt  0.11.4

**Comment by josegonzalez** [comment]
Mind trying out 0.11.6 and seeing if this is still the case?

**Comment by ifree92** [comment]
@josegonzalez unfortunately, `0.11.6` crashed for me everything so even enable some application, I don't see it in the output from list command (actually whatever I would do, the list is always empty :( )

**Comment by josegonzalez** [comment]
0.11.7 should fix the issue with list. Mind trying that out?

**Comment by ifree92** [comment]
@josegonzalez I have updated to `0.11.7`.
Now I see the list of already added applications that I made on 0.11.2 version. But unable to add a new one.

So, if I execute `dokku letsencrypt:enable some-new-app`, that is not appearing in output from `dokku letsencrypt:list`.

**Comment by michaelyork** [comment]
I'm having the same exact issue. Keep enabling apps for letsencrypt via `dokku letsencrypt:enable <app>` but they don't appear in the `list` command right after and don't survive a restart.

**Comment by josegonzalez** [comment]
Combining this into #224.
