### ISSUE TITLE
Setting up HTTP/2

### ISSUE THREAD

**Issue by dydx** [dokku/dokku-letsencrypt#23]
Heya,

I'm trying to experiment with HTTP/2, and Dokku seems like a good path to work down, but I have a question about setting this up.

The nginx template that comes with this plugin looks to add in a custom location section, though from my tinkering around locally I have some further configurations in the server block like this:

```nginx
server {
    listen                     443 ssl http2;
    server_name                localhost;

    ssl                        on;
    ssl_protocols              TLSv1 TLSv1.1 TLSv1.2;
    ssl_certificate            cert.pem;
    ssl_certificate_key        cert.key;

    location / {
        proxy_pass          http://localhost:8080;
        proxy_set_header    Host      $host;
        proxy_set_header    X-Real-IP $remote_addr;
        proxy_set_header    X-HTTPS   'True';
    }
}
```

I feel like I don't really understand this is being set up in the end, so I could be overthinking this or underthinking it.... but any help with this would be really appreciated!

Thanks for the cool software.

**Comment by sseemayer** [comment]
Thanks for giving the plugin a try! I've written up an [explanation of how the plugin and ACME validation works in my blog](https://blog.semicolonsoftware.de/securing-dokku-with-lets-encrypt-tls-certificates/) if you want to understand things better. 

Looks like you're trying to combine [this tutorial](https://medium.com/@maxbarry/http-2-let-s-encrypt-dokku-how-to-do-all-three-7de94a0028fb#.iorqq9kh4) with dokku-letsencrypt. I'd propose one of two options:

a) If all you want to do is set up HTTP/2 with dokku and let's encrypt, keeping everything else the default, the easiest way to do this (after making sure you have an appropriate nginx version) is to copy the config template from `/var/lib/dokku/plugins/avaliable/nginx-vhosts/templates/nginx.ssl.conf.template` to `/home/dokku/<myapp>/nginx.ssl.conf.template` and replacing the `spdy` in the `listen` directive with `http2`. After that, rerun `dokku nginx:build-config <myapp>`.

b) Alternatively, if you want to keep your current config, you will need to add the `include` directive after the end of the `location` block like so:

```
include $DOKKU_ROOT/$APP/nginx.conf.d/*.conf;
```

This will allow nginx to load any additional configuration entries for your app such as could be provided by `dokku-letsencrypt` or e.g. the [dokku-http-auth plugin](https://github.com/dokku/dokku-http-auth). If the include line fails, nginx will not configure the proxy needed to handle ACME requests and all ACME verification requests will instead by passed to your app that probably won't know what to do with them.

**Comment by dydx** [comment]
Excellent!

I went with path 'a' and included the modified template. I did have to upgrade my nginx installation, though nothing seems to have broken.

Thanks!

**Comment by sseemayer** [comment]
No problem! Glad you got things working.

**Comment by haywirez** [comment]
With the [SPDY decprecation on May 15](http://blog.chromium.org/2016/02/transitioning-from-spdy-to-http2.html) looming, is there any plan to make this a default?

**Comment by sseemayer** [comment]
dokku-letsencrypt isn't doing any nginx configuration but just installs the certificates at the correct position. You'd have to ask again in dokku/dokku about this.

My guess would be we're still using SPDY instead of HTTP/2 because the recommended distro Ubuntu 14.04 [still runs nginx 1.4.6](http://packages.ubuntu.com/trusty/nginx) while [HTTP/2 support only arrived in nginx 1.9.5](https://www.nginx.com/blog/nginx-1-9-5/). Good news is that there will be [a new Ubuntu LTS release landing very soon (tomorrow)](https://wiki.ubuntu.com/XenialXerus/ReleaseSchedule) which [will contain nginx 1.9.14](http://packages.ubuntu.com/xenial/nginx).
