### ISSUE TITLE
Moving Certs Between Servers

### ISSUE THREAD

**Issue by odscjames** [dokku/dokku-letsencrypt#233]
Is it possible to move certs between servers?

**Use Case:**
I have an app on one server, with an existing Lets Encrypt cert. I want to move it to another server with no downtime.

I can:

1. create app on new sever
1. change DNS to route traffic to new server
2. wait for DNS to propagate
3. get cert on new server 

BUT for a while the app will have only HTTP and no HTTPS option, and this would count as downtime.

**Previously without Dokku**

On servers without Dokku the certbot stores it's data files, including the certs, in /etc/letsencrypt - so it's possible to grab the ones you need and move them before changing DNS.

I can't find where this plugin stores it's cert info?

**Question/request**

Where does this plugin stores it's cert info?

If it's easily accessible, can this be documented somewhere in the readme?

If it's not accessible, can there be an export / import sub command, like other extensions like Redis have?

Thanks, and sorry if I've missed something obvious.

James

**Comment by l3d00m** [comment]
You can find them under `/home/dokku/APP_NAME/letsencrypt/certs/current/` if i'm not mistaken (also `/home/dokku/APP_NAME/tls/` exists, but I'm not sure how they relate)

**Comment by odscjames** [comment]
Oh, /home/dokku - I was looking under /var/lib/dokku - thank you!

I'll try and do a test on moving them soon - it would be good if there was a process noted in the readme, maybe?

**Comment by l3d00m** [comment]
No problem! I have been looking for the same thing just yesterday and found the location by reverse engineering the scripts (https://github.com/dokku/dokku-letsencrypt/blob/master/subcommands/enable#L54) because I wasn't able to find docs either. I'm still not sure why `/home/dokku/APP_NAME/tls/` exists.

**Comment by odscjames** [comment]
Setup:

* I have a live app with SSL cert and DNS points to it
* On another Dokku server, I have same app, same domain name, but DNS does NOT point to it

Process:

* Get current stuff from live/source server. (Note this must be done in a way that preserves symlinks!)

    ssh ...
    cd /home/dokku/$APP_NAME
    tar -cf ssl.tar letsencrypt

* Move that file to new server
* Extract file, put in correct place

    ssh ...
    tar -xf ssl.tar
    mv letsencrypt /home/dokku/$APP_NAME

* Fix broken sym-link in certs/current, if the app name is different!!! 

    cd /home/dokku/$APP_NAME
    rm letsencrypt/certs/current 
    ln -s /home/dokku/$APP_NAME/letsencrypt/certs/$WHATEVER_OLD_SYMLINK_WAS_TO/ letsencrypt/certs/current

* Try and enable LE!

    dokku letsencrypt:enable $APP_NAME

* Ok, it wants an email first, fine - 

    dokku config:set --no-restart $APP_NAME DOKKU_LETSENCRYPT_EMAIL=....

* Try and enable LE again!

    dokku letsencrypt:enable $APP_NAME

**FAIL FAIL FAIL**

It tries to get a cert and of course fails, as the DNS does not point to the new server and so the challenge fails:


Code path in https://github.com/dokku/dokku-letsencrypt/blob/master/subcommands/enable :

* cmd-letsencrypt-enable() runs
* always calls fn-lentsencrypt-enable() 
* that always calls letsencrypt_acme()
* that always calls the lets encrypt docker run

I was HOPING that the code would look on disk, go "oh, we already have a cert and it's recent, we'll just use this, hurray" and it would all be fine.

Sadly not - it looks like something is always forcing a renew, and that fails :cry:

**Comment by odscjames** [comment]
I even tried:

    vi /var/lib/dokku/plugins/enabled/letsencrypt/subcommands/enable 

In letsencrypt_acme function, comment out docker run command, comment out `local exit_code=$?`, add `local exit_code=0` instead ...

Now enable ....

    dokku letsencrypt:enable $APP_NAME

Doesn't work - something rewrites the "current" symlink to a new folder that is missing crucial files, and I can't see what is doing that. [ Well, letsencrypt_link function is, but I can't work out what is calling letsencrypt_link before the error comes up ]

In any case, this is getting far far to hacky to be recognised as a safe and reliable procedure.

It looks like we need some kind of official support in the plugin - import and export methods would be great!

**Comment by josegonzalez** [comment]
Thanks @erickedji for posting that. The process for moving an app between servers should include that `tls` directory. That also goes for regular ssl certificates.

If you want to re-enable letsencrypt on the new isntall, you can do so via the normal method of enabling letsencrypt on the app (which should be documented in the readme).

**Comment by odscjames** [comment]
> (which should be documented in the readme)

Can this be reopened for this?

**Comment by josegonzalez** [comment]
Enabling a letsencrypt on a server _is_ documented though?

We currently copy the certificates out of the letsencrypt folder into the `tls` directory, so as long as you also restored the port mapping data for the app (which is stored in /var/lib/dokku/config) and the nginx config, your app should have ssl enabled. The Dokku backup docs say to backup the `/home/dokku` dir as well as the var lib paths, so if you restore that, your app should continue to have ssl.

**Comment by odscjames** [comment]
Oh, sorry, should have been clearer - can we document the moving process? I've just had to do it again and here's my first attempt. If others think this would be helpful, I'm happy to clean up and submit a M.R.

---



## Moving apps between Servers, with no SSL downtime

If you want to move a Dokku app between 2 Dokku servers, but have no period where SSL is not available, follow this process:

* Install app on new server, with same app name
* Use the "dokku domains" functions to make sure the correct domain names are set up on the new server
* On the old server, run:

    export APP_NAME=yourappname
    tar -czf /root/$APP_NAME.certs.tar.gz /home/dokku/$APP_NAME/tls
    
* Copy the resulting file from the old server to the new server (put it in /root)
* On the new server, run:

    export APP_NAME=yourappname
    tar -xf /root/$APP_NAME.certs.tar.gz --directory /
    rm /root/$APP_NAME.certs.tar.gz
    dokku proxy:ports-add $APP_NAME https:443:80
    
* At this point, the new server should be serving the app with SSL. Edit your machine's /etc/hosts file to manually point the domain to the new IP and check.
* You can now change the DNS to point to the new server
* Wait for the DNS changes to propograte fully
* On the new server, run:

    export APP_NAME=yourappname
    dokku letsencrypt:enable $APP_NAME

Finally,

* Disable Lets Encrypt on app on old server (To avoid renewal errors, as the challenge will now not work)

Problems: 

Can't get a new cert? Check "dokku proxy:ports" - you need both port 80 and 443 to be enabled.

**Comment by josegonzalez** [comment]
Are you doing a partial restore of an app? I think if you're restoring a backup of a dokku install, it should include all the information you're asking to backup/restore here. I'd rather not document the individual backup/restore process of a plugin when the intent is to backup/restore a server.

**Comment by odscjames** [comment]
Yes, we are moving just one app from server to server. We are not just backup'ing and restoring a whole server. 

This may be done for server capacity management reasons (eg you have to many apps on one dokku server and want to split those apps across 2 servers) as well as backup/restore reasons, so I would find it helpful to have anything tricky documented. 

Most plugins this is pretty clear (eg postgres and redis has export/import commands ) but this one is a bit more fiddly.

**Comment by erickedji** [comment]
@josegonzalez I had the same use case as @odscjames : capacity management, meaning only a single app is being moved.

**Comment by odscjames** [comment]
Another use case: I'm moving an app from a non-Dokku server into a Dokku server. Can we re-open this and document the process?
