### ISSUE TITLE
letsencrypt:cron-job --add not creating a crontab entry 

### ISSUE THREAD

**Issue by m-z-b** [dokku/dokku-letsencrypt#234]
## Description of problem
Creating a cronjob to autorenew 

### How reproducible
It's on a production site: every time for me, but as it's live I can't perform many tests.

Worked around the problem with a manually created crontab file.

### Steps to Reproduce

1. Install Dokku 0.21.4 on Ubuntu 20.04 with letsecncrypt, and redirect plugins
2. Push app www with domains and redirects
3. run dokku letsencrypt:enable www
4. run dokku letsencrypt:cron-job --add
5. sudo -u dokku crontab -l 

#### Actual Results
An empty file. No crontab entries created in either dokku or root account.

#### Expected Results
A dokku letsencrypt:auto-renew entry in the dokku crontab

### `dokku report APP_NAME` output

-----> uname: Linux arl-black 5.4.0-52-generic #57-Ubuntu SMP Thu Oct 15 10:57:00 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
-----> memory: 
                     total        used        free      shared  buff/cache   available
       Mem:            981         427          98          15         454         384
       Swap:          2047          79        1968
-----> docker version: 
       Client: Docker Engine - Community
        Version:           19.03.13
        API version:       1.40
        Go version:        go1.13.15
        Git commit:        4484c46d9d
        Built:             Wed Sep 16 17:02:52 2020
        OS/Arch:           linux/amd64
        Experimental:      false
       
       Server: Docker Engine - Community
        Engine:
         Version:          19.03.13
         API version:      1.40 (minimum version 1.12)
         Go version:       go1.13.15
         Git commit:       4484c46d9d
         Built:            Wed Sep 16 17:01:20 2020
         OS/Arch:          linux/amd64
         Experimental:     false
        containerd:
         Version:          1.3.7
         GitCommit:        8fba4e9a7d01810a393d5d25a3621dc101981175
        runc:
         Version:          1.0.0-rc10
         GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
        docker-init:
         Version:          0.18.0
         GitCommit:        fec3683
-----> docker daemon info: 
       Client:
        Debug Mode: true
       
       Server:
        Containers: 15
         Running: 3
         Paused: 0
         Stopped: 12
        Images: 21
        Server Version: 19.03.13
        Storage Driver: overlay2
         Backing Filesystem: extfs
         Supports d_type: true
         Native Overlay Diff: true
        Logging Driver: json-file
        Cgroup Driver: cgroupfs
        Plugins:
         Volume: local
         Network: bridge host ipvlan macvlan null overlay
         Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
        Swarm: inactive
        Runtimes: runc
        Default Runtime: runc
        Init Binary: docker-init
        containerd version: 8fba4e9a7d01810a393d5d25a3621dc101981175
        runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
        init version: fec3683
        Security Options:
         apparmor
         seccomp
          Profile: default
        Kernel Version: 5.4.0-52-generic
        Operating System: Ubuntu 20.04.1 LTS
        OSType: linux
        Architecture: x86_64
        CPUs: 1
        Total Memory: 981.3MiB
        Name: arl-black
        ID: PEEB:CHZO:EMP7:XJR5:2ZB7:QM5F:TPDW:PHRP:MO73:X7YR:V5PN:LJDA
        Docker Root Dir: /var/lib/docker
        Debug Mode: false
        Registry: https://index.docker.io/v1/
        Labels:
        Experimental: false
        Insecure Registries:
         127.0.0.0/8
        Live Restore Enabled: false
       
-----> sigil version: 0.6.0
-----> herokuish version: 
       herokuish: 0.5.18
       buildpacks:
         heroku-buildpack-multi     v1.0.0
         heroku-buildpack-ruby      v218
         heroku-buildpack-nodejs    v175
         heroku-buildpack-clojure   v85
         heroku-buildpack-python    v177
         heroku-buildpack-java      v66
         heroku-buildpack-gradle    v31
         heroku-buildpack-scala     v87
         heroku-buildpack-play      v26
         heroku-buildpack-php       v179
         heroku-buildpack-go        v145
         buildpack-nginx            v14
-----> dokku version: dokku version 0.21.4
-----> dokku plugins: 
       plugn: 0.5.0
         00_dokku-standard    0.21.4 enabled    dokku core standard plugin
         20_events            0.21.4 enabled    dokku core events logging plugin
         app-json             0.21.4 enabled    dokku core app-json plugin
         apps                 0.21.4 enabled    dokku core apps plugin
         builder-dockerfile   0.21.4 enabled    dokku core builder-dockerfile plugin
         builder-herokuish    0.21.4 enabled    dokku core builder-herokuish plugin
         buildpacks           0.21.4 enabled    dokku core buildpacks plugin
         certs                0.21.4 enabled    dokku core certificate management plugin
         checks               0.21.4 enabled    dokku core checks plugin
         common               0.21.4 enabled    dokku core common plugin
         config               0.21.4 enabled    dokku core config plugin
         docker-options       0.21.4 enabled    dokku core docker-options plugin
         domains              0.21.4 enabled    dokku core domains plugin
         enter                0.21.4 enabled    dokku core enter plugin
         git                  0.21.4 enabled    dokku core git plugin
         letsencrypt          0.11.9 enabled    Automated installation of let's encrypt TLS certificates
         logs                 0.21.4 enabled    dokku core logs plugin
         network              0.21.4 enabled    dokku core network plugin
         nginx-vhosts         0.21.4 enabled    dokku core nginx-vhosts plugin
         plugin               0.21.4 enabled    dokku core plugin plugin
         postgres             1.12.0 enabled    dokku postgres service plugin
         proxy                0.21.4 enabled    dokku core proxy plugin
         ps                   0.21.4 enabled    dokku core ps plugin
         redirect             0.7.1 enabled    Plugin for managing application redirects
         repo                 0.21.4 enabled    dokku core repo plugin
         resource             0.21.4 enabled    dokku core resource plugin
         scheduler-docker-local 0.21.4 enabled    dokku core scheduler-docker-local plugin
         shell                0.21.4 enabled    dokku core shell plugin
         ssh-keys             0.21.4 enabled    dokku core ssh-keys plugin
         storage              0.21.4 enabled    dokku core storage plugin
         tags                 0.21.4 enabled    dokku core tags plugin
         tar                  0.21.4 enabled    dokku core tar plugin
         trace                0.21.4 enabled    dokku core trace plugin
=====> www app information
       App deploy source:             
       App dir:                       /home/dokku/www
       App locked:                    false
=====> www buildpacks information
       Buildpacks list:               
=====> www ssl information
       Ssl dir:                       /home/dokku/www/tls      
       Ssl enabled:                   true                     
       Ssl hostnames:                 REDACTED1.com REDACTED2.ca REDACTED4.com REDACTED3.com www.REDACTED1.com www.REDACTED2.ca www.REDACTED4.com www.REDACTED3.com
       Ssl expires at:                Aug 25 19:13:27 2021 GMT 
       Ssl issuer:                    C = US, O =              
       Ssl starts at:                 May 27 19:13:27 2021 GMT 
       Ssl subject:                   subject=CN = REDACTED1.com
       Ssl verified:                  self signed              
=====> www checks information
       Checks disabled list:          none                     
       Checks skipped list:           none                     
=====> www docker options information
       Docker options build:          --link dokku.postgres.REDACTED6:dokku-postgres-REDACTED6 
       Docker options deploy:         --link dokku.postgres.REDACTED6:dokku-postgres-REDACTED6 --restart=on-failure:10 
       Docker options run:            --link dokku.postgres.REDACTED6:dokku-postgres-REDACTED6 
=====> www domains information
       Domains app enabled:           true                     
       Domains app vhosts:            REDACTED1.com www.REDACTED1.com REDACTED3.com www.REDACTED3.com REDACTED4.com www.REDACTED4.com REDACTED2.ca www.REDACTED2.ca
       Domains global enabled:        true                     
       Domains global vhosts:         REDACTED5-black                
=====> www git information
       Git deploy branch:             master                   
       Git global deploy branch:      master                   
       Git keep git dir:              false                    
       Git rev env var:               GIT_REV                  
       Git sha:                       f1959ab                  
       Git last updated at:                                    
=====> www network information
       Network attach post create:    
       Network attach post deploy:    
       Network bind all interfaces:   false
       Network web listeners:         172.17.0.3:5000
=====> www nginx information
       Nginx access log path:         /var/log/nginx/www-access.log
       Nginx bind address ipv4:                                
       Nginx bind address ipv6:       ::                       
       Nginx error log path:          /var/log/nginx/www-error.log
       Nginx hsts:                    true                     
       Nginx hsts include subdomains: true                     
       Nginx hsts max age:            15724800                 
       Nginx hsts preload:            false                    
       Nginx proxy read timeout:      60s                      
       Nginx last visited at:         1622157061               
=====> www proxy information
       Proxy enabled:                 true
       Proxy port map:                http:80:5000 https:443:5000
       Proxy type:                    nginx
=====> www ps information
       Processes:                     1                        
       Deployed:                      true                     
       Running:                       true                     
       Restore:                       true                     
       Restart policy:                on-failure:10            
       Ps can scale:                  false                    
       Status web.1:                  running    (CID: b42cba477c11)
=====> www scheduler-docker-local information
       Scheduler docker local disable chown:                          
=====> www storage information
       Storage build mounts:                                   
       Storage deploy mounts:                                  
       Storage run mounts:

**Comment by josegonzalez** [comment]
Please upgrade Dokku to the latest version, which will fix crontab support for external plugins.

**Comment by m-z-b** [comment]
That may take a while... I'm using the most recent DigitalOcean marketplace version. 

Is it worth using an earlier version of the letsencrypt plugin to better match it. 
(It's only this feature that's not working)

(Sneaky feature request. Provide a crontab --list option to review the entries...)

**Comment by josegonzalez** [comment]
The upgrade process for Dokku is:

```
apt update
apt upgrade
```

Shouldn't take too long.
