### ISSUE TITLE
Unable to Auto Renew certificate

### ISSUE THREAD

**Issue by tarikmiljkovic** [dokku/dokku-letsencrypt#238]
Hi, 

do you know how to setup auto-renew on my existing certificate?

I tried this command, but did not worked.
`dokku letsencrypt:auto-renew app`

Thank you
![Uploading Screenshot 2021-07-28 at 18.13.31.png…]()

**Comment by josegonzalez** [comment]
@tarikmiljkovic repost the screenshot? It didn't finish uploading.

Additionally, can you add the output of `dokku report`?

**Comment by josegonzalez** [comment]
Closing as there hasn't been any update.
