### ISSUE TITLE
Why is public key size only 256 bytes?

### ISSUE THREAD

**Issue by GORGES** [dokku/dokku-letsencrypt#249]
## Description of problem

Our Greenbone vulnerability assessment tool has flagged all our Dokku-enabled sites as being insecure because the public key size is 256 bytes. A review of the SSL certificates in a web browser confirm this:

![image](https://user-images.githubusercontent.com/4960583/144434170-40ba4a5f-834b-4e07-936c-ec6fafb5c3c8.png)

By comparison all our non-Dokku sites that use the LetsEncrypt certbot program have public key sizes of 2048, which are much more secure.

### How reproducible

The problem is 100% reproducible.

### Steps to Reproduce

1. Create a Dokku-based website
2. Add a LetsEncrypt certificate
3. Inspect the certificate in a web browser, view the certificate details

#### Actual Results

Actual result is "Key size: 256 bits"

#### Expected Results

Expected result is "Key size: 2,048 bits"

## Environment Information

Ubuntu 18.04.6 LTS

### `dokku report api` output

$ dokku report api
-----> uname: Linux ip-172-31-10-151 5.4.0-1057-aws #60~18.04.1-Ubuntu SMP Thu Sep 9 20:38:09 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
-----> memory: 
                     total        used        free      shared  buff/cache   available
       Mem:           3933         788         288          20        2856        2846
       Swap:          4095           4        4091
-----> docker version: 
       Client: Docker Engine - Community
        Version:           20.10.11
        API version:       1.41
        Go version:        go1.16.9
        Git commit:        dea9396
        Built:             Thu Nov 18 00:37:08 2021
        OS/Arch:           linux/amd64
        Context:           default
        Experimental:      true
       
       Server: Docker Engine - Community
        Engine:
         Version:          20.10.11
         API version:      1.41 (minimum version 1.12)
         Go version:       go1.16.9
         Git commit:       847da18
         Built:            Thu Nov 18 00:35:16 2021
         OS/Arch:          linux/amd64
         Experimental:     false
        containerd:
         Version:          1.4.12
         GitCommit:        7b11cfaabd73bb80907dd23182b9347b4245eb5d
        runc:
         Version:          1.0.2
         GitCommit:        v1.0.2-0-g52b36a2
        docker-init:
         Version:          0.19.0
         GitCommit:        de40ad0
-----> docker daemon info: 
       Client:
        Context:    default
        Debug Mode: true
        Plugins:
         app: Docker App (Docker Inc., v0.9.1-beta3)
         buildx: Build with BuildKit (Docker Inc., v0.6.3-docker)
         scan: Docker Scan (Docker Inc., v0.9.0)
       
       Server:
        Containers: 2
WARNING: No swap limit support
         Running: 2
         Paused: 0
         Stopped: 0
        Images: 24
        Server Version: 20.10.11
        Storage Driver: overlay2
         Backing Filesystem: extfs
         Supports d_type: true
         Native Overlay Diff: true
         userxattr: false
        Logging Driver: json-file
        Cgroup Driver: cgroupfs
        Cgroup Version: 1
        Plugins:
         Volume: local
         Network: bridge host ipvlan macvlan null overlay
         Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
        Swarm: inactive
        Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
        Default Runtime: runc
        Init Binary: docker-init
        containerd version: 7b11cfaabd73bb80907dd23182b9347b4245eb5d
        runc version: v1.0.2-0-g52b36a2
        init version: de40ad0
        Security Options:
         apparmor
         seccomp
          Profile: default
        Kernel Version: 5.4.0-1057-aws
        Operating System: Ubuntu 18.04.6 LTS
        OSType: linux
        Architecture: x86_64
        CPUs: 2
        Total Memory: 3.842GiB
        Name: ip-172-31-10-151
        ID: SYBA:GVWW:V2N3:TDPR:GKFY:OCPP:67PL:34IH:BAJW:QA2M:EKKF:6YMK
        Docker Root Dir: /var/lib/docker
        Debug Mode: false
        Registry: https://index.docker.io/v1/
        Labels:
        Experimental: false
        Insecure Registries:
         127.0.0.0/8
        Live Restore Enabled: false
       
-----> git version: git version 2.17.1
-----> sigil version: 0.7.1build+1ec3006
-----> herokuish version: 
       herokuish: 0.5.33
       buildpacks:
         heroku-buildpack-multi     v1.0.0
         heroku-buildpack-ruby      v232
         heroku-buildpack-nodejs    v189
         heroku-buildpack-clojure   v87
         heroku-buildpack-python    v204
         heroku-buildpack-java      v69
         heroku-buildpack-gradle    v35
         heroku-buildpack-scala     v91
         heroku-buildpack-play      v26
         heroku-buildpack-php       v201
         heroku-buildpack-go        v157
         heroku-buildpack-nginx     v15
         buildpack-null             v3
-----> dokku version: dokku version 0.26.6
-----> plugn version: plugn: 0.7.1build+9bf216b
-----> dokku plugins: 
         00_dokku-standard    0.26.6 enabled    dokku core standard plugin
         20_events            0.26.6 enabled    dokku core events logging plugin
         app-json             0.26.6 enabled    dokku core app-json plugin
         apps                 0.26.6 enabled    dokku core apps plugin
         apt                  0.12.0 enabled    Inject deb packages into dokku based on files in project
         builder              0.26.6 enabled    dokku core builder plugin
         builder-dockerfile   0.26.6 enabled    dokku core builder-dockerfile plugin
         builder-herokuish    0.26.6 enabled    dokku core builder-herokuish plugin
         builder-null         0.26.6 enabled    dokku core builder-null plugin
         builder-pack         0.26.6 enabled    dokku core builder-pack plugin
         buildpacks           0.26.6 enabled    dokku core buildpacks plugin
         certs                0.26.6 enabled    dokku core certificate management plugin
         checks               0.26.6 enabled    dokku core checks plugin
         common               0.26.6 enabled    dokku core common plugin
         config               0.26.6 enabled    dokku core config plugin
         cron                 0.26.6 enabled    dokku core cron plugin
         docker-options       0.26.6 enabled    dokku core docker-options plugin
         domains              0.26.6 enabled    dokku core domains plugin
         enter                0.26.6 enabled    dokku core enter plugin
         git                  0.26.6 enabled    dokku core git plugin
         http-auth            0.6.2 enabled    HTTP authentication for apps
         letsencrypt          0.12.1 enabled    Automated installation of let's encrypt TLS certificates
         logs                 0.26.6 enabled    dokku core logs plugin
         maintenance          0.5.1 enabled    Maintenance mode for apps
         mysql                1.18.0 enabled    dokku mysql service plugin
         network              0.26.6 enabled    dokku core network plugin
         nginx-vhosts         0.26.6 enabled    dokku core nginx-vhosts plugin
         plugin               0.26.6 enabled    dokku core plugin plugin
         proxy                0.26.6 enabled    dokku core proxy plugin
         ps                   0.26.6 enabled    dokku core ps plugin
         redirect             0.7.1 enabled    Plugin for managing application redirects
         registry             0.26.6 enabled    dokku core registry plugin
         repo                 0.26.6 enabled    dokku core repo plugin
         resource             0.26.6 enabled    dokku core resource plugin
         run                  0.26.6 enabled    dokku core run plugin
         scheduler            0.25.6 enabled    dokku core scheduler plugin
         scheduler-docker-local 0.26.6 enabled    dokku core scheduler-docker-local plugin
         scheduler-null       0.26.6 enabled    dokku core scheduler-null plugin
         shell                0.26.6 enabled    dokku core shell plugin
         ssh-keys             0.26.6 enabled    dokku core ssh-keys plugin
         storage              0.26.6 enabled    dokku core storage plugin
         trace                0.26.6 enabled    dokku core trace plugin
=====> api app-json information
       App json computed selected:    app.json
       App json global selected:      app.json
       App json selected:             
=====> api app information
       App created at:                1638384762
       App deploy source:             
       App deploy source metadata:    
       App dir:                       /home/dokku/api
       App locked:                    false
=====> api builder information
       Builder build dir:             
       Builder computed build dir:    
       Builder computed selected:     
       Builder global build dir:      
       Builder global selected:       
       Builder selected:              
=====> api builder-dockerfile information
       Builder dockerfile computed dockerfile path: Dockerfile               
       Builder dockerfile global dockerfile path: Dockerfile               
       Builder dockerfile dockerfile path:                          
=====> api builder-pack information
       Builder pack computed projecttoml path: project.toml             
       Builder pack global projecttoml path: project.toml             
       Builder pack projecttoml path:                          
=====> api buildpacks information
       Buildpacks computed stack:     gliderlabs/herokuish:latest-20
       Buildpacks global stack:       
       Buildpacks list:               https://github.com/heroku/heroku-buildpack-php
       Buildpacks stack:              
=====> api ssl information
       Ssl dir:                       /home/dokku/api/tls      
       Ssl enabled:                   true                     
       Ssl hostnames:                 api.wellcoaches.app      
       Ssl expires at:                Mar  1 14:45:33 2022 GMT 
       Ssl issuer:                    C = US, O = Let's Encrypt, CN = R3
       Ssl starts at:                 Dec  1 14:45:34 2021 GMT 
       Ssl subject:                   subject=CN = api.wellcoaches.app
       Ssl verified:                  self signed              
=====> api checks information
       Checks disabled list:          none                     
       Checks skipped list:           none                     
=====> api cron information
       Cron task count:               0
=====> api docker options information
       Docker options build:                                   
       Docker options deploy:         --restart=on-failure:10 -v /var/lib/dokku/data/storage/api/attachments:/app/attachments/ -v /var/lib/dokku/data/storage/api/runtime:/app/runtime/ 
       Docker options run:            -v /var/lib/dokku/data/storage/api/attachments:/app/attachments/ -v /var/lib/dokku/data/storage/api/runtime:/app/runtime/ 
=====> api domains information
       Domains app enabled:           true                     
       Domains app vhosts:            api.wellcoaches.app      
       Domains global enabled:        false                    
       Domains global vhosts:                                  
=====> api git information
       Git deploy branch:             master                   
       Git global deploy branch:      master                   
       Git keep git dir:              false                    
       Git rev env var:               GIT_REV                  
       Git sha:                       bd2e0be                  
       Git last updated at:           1634674291               
=====> api http-auth information
       Http auth enabled:             false                    
=====> api logs information
       Logs computed max size:        10m
       Logs global max size:          10m
       Logs global vector sink:       
       Logs max size:                 
       Logs vector sink:              
=====> api network information
       Network attach post create:           
       Network attach post deploy:           
       Network bind all interfaces:          false
       Network computed attach post create:  
       Network computed attach post deploy:  
       Network computed bind all interfaces: false
       Network computed initial network:     
       Network computed tld:                 
       Network global attach post create:    
       Network global attach post deploy:    
       Network global bind all interfaces:   false
       Network global initial network:       
       Network global tld:                   
       Network initial network:              
       Network static web listener:          
       Network tld:                          
       Network web listeners:                172.17.0.3:5000
=====> api nginx information
       Nginx access log format:                                
       Nginx access log path:         /var/log/nginx/api-access.log
       Nginx bind address ipv4:                                
       Nginx bind address ipv6:       ::                       
       Nginx client max body size:                             
       Nginx disable custom config:   false                    
       Nginx error log path:          /var/log/nginx/api-error.log
       Nginx global hsts:             true                     
       Nginx computed hsts:           true                     
       Nginx hsts:                                             
       Nginx hsts include subdomains: true                     
       Nginx hsts max age:            15724800                 
       Nginx hsts preload:            false                    
       Nginx proxy buffer size:       4096                     
       Nginx proxy buffering:         on                       
       Nginx proxy buffers:           8 4096                   
       Nginx proxy busy buffers size: 8192                     
       Nginx proxy read timeout:      60s                      
       Nginx last visited at:         1638453113               
       Nginx x forwarded for value:   $remote_addr             
       Nginx x forwarded port value:  $server_port             
       Nginx x forwarded proto value: $scheme                  
       Nginx x forwarded ssl:                                  
=====> api proxy information
       Proxy enabled:                 true
       Proxy port map:                http:80:5000 https:443:5000
       Proxy type:                    nginx
=====> api ps information
       Deployed:                      true
       Processes:                     1
       Ps can scale:                  true
       Ps computed procfile path:     Procfile
       Ps global procfile path:       Procfile
       Ps procfile path:              
       Ps restart policy:             on-failure:10
       Restore:                       true
       Running:                       true
       Status web 1:                  running (CID: f90ee17d65d)
=====> api registry information
       Registry computed image repo:      dokku/api
       Registry computed push on release: false
       Registry computed server:          
       Registry global push on release:   
       Registry global server:            
       Registry image repo:               
       Registry push on release:          
       Registry server:                   
       Registry tag version:              
=====> api resource information
=====> api scheduler information
       Scheduler computed selected:   docker-local
       Scheduler global selected:     docker-local
       Scheduler selected:            
=====> api scheduler-docker-local information
       Scheduler docker local disable chown:                          
       Scheduler docker local parallel schedule count:                          
=====> api storage information
       Storage build mounts:                                   
       Storage deploy mounts:         -v /var/lib/dokku/data/storage/api/attachments:/app/attachments/ -v /var/lib/dokku/data/storage/api/runtime:/app/runtime/ 
       Storage run mounts:            -v /var/lib/dokku/data/storage/api/attachments:/app/attachments/ -v /var/lib/dokku/data/storage/api/runtime:/app/runtime/ 

### How (deb/make/rpm) and where (AWS, VirtualBox, physical, etc.) was Dokku installed?:

Installation was on Ubuntu 18.04.6 LTS virtual server hosted by DigitalOcean.

### Additional information

$ dokku certs:report api
=====> api ssl information
       Ssl dir:                       /home/dokku/api/tls      
       Ssl enabled:                   true                     
       Ssl hostnames:                 api.wellcoaches.app      
       Ssl expires at:                Mar  1 14:45:33 2022 GMT 
       Ssl issuer:                    C = US, O = Let's Encrypt, CN = R3
       Ssl starts at:                 Dec  1 14:45:34 2021 GMT 
       Ssl subject:                   subject=CN = api.wellcoaches.app
       Ssl verified:                  self signed              

Also I took a look at the dokku-letsencrypt source code, and it appears to use the command "openssl" to generate the certificate (source file: functions). By default this should be 2048 bits, so I don't understand why the key is only 256 bits.

**Comment by josegonzalez** [comment]
We use the [`docker-letsencrypt`](https://github.com/dokku/docker-letsencrypt) image which wraps [simp_le](https://github.com/zenhack/simp_le) with [these arguments](https://github.com/dokku/dokku-letsencrypt/blob/d376aeaf4c648d040325354050428f0694dde775/functions#L182). Maybe something about zenhack is broken?

**Comment by josegonzalez** [comment]
Mind investigating simp_le to see if there is something upstream causing this?

**Comment by GORGES** [comment]
This is unfortunately pushing my knowledge limit since I know enough to create and use dokku containers, but not much about the docker system underneath. I explored the zenhack/simp_le repository a bit, but it seems like the default key sizes are nice and big (default is 4096 bits).

Do other people use the dokku-letsencrypt plugin? Before this week I thought it was running smoothly, but never checked the key size until the vulnerability scanner pointed out this problem.

I looked at the github.com/zenhack/simp_le code, and it seems very different from the dokku. I will explore more as time permits, but not sure how to help diagnose the problem.

**Comment by josegonzalez** [comment]
Are you sure this vulnerability scanner is correct? I get the same result for google.com...

<img width="469" alt="Screen Shot 2021-12-02 at 3 57 26 PM" src="https://user-images.githubusercontent.com/65675/144501881-e5b60513-7ed2-4afe-9d11-ce8e1e951ac9.png">

**Comment by GORGES** [comment]
That is a good point, and I can run the vulnerability scanner against other sites to check. Perhaps the Google.com site would also fail the Greenbone Vulnerability Scanner.

As a comparison I did run the scanner against non-Dokku sites with LetsEncrypt certificates installed via certbot (example: sustainablehealthsystems.biz) and they were OK. Here is a comparison screenshot:

![SSL-key-size-comparisons-dokku-vs-nondokku](https://user-images.githubusercontent.com/4960583/144502550-520dd981-ca97-4bbf-9b8e-b36513bc7e73.png)

**Comment by josegonzalez** [comment]
Does the algorithm here matter at all? If it also fails for the same reason, maybe that security scanner is bullshit and isn't properly parsing the key info?

**Comment by GORGES** [comment]
Again a good question, and I honestly don't know. I think the Greenbone scanner is pretty well used, as is LetsEncrypt and Dokku. Perhaps I give it a few days to see if others notice this potential issue. I find it a bit hard to believe I would be the first person to notice this, and it is so easy to reproduce which is to run a Greenbone scan against a dokku-letsencrypt-enabled site.

**Comment by GORGES** [comment]
Jose, you are correct and running the Greenbone assessment tool against Google.com showed the SAME security flaw of a 256-bit key. Something is definitely wrong, and it is probably the scanner unless Google.com truly messed up also.

I think my action is to pause and check back in a few days. I may post this behavior on the Greenbone scanning site also.

**Comment by GORGES** [comment]
And THANK YOU for your response and insight.

**Comment by JonasAlfredsson** [comment]
Hi, I just happened to stumble upon this, but to me it looks like the public key you are referring to is using the new Elliptic Curve Cryptography (ECC/ECDSA) instead of the old RSA algorithm. A 256 bit ECC key is roughly equal to a 3072 bit RSA key according to [this](https://sectigostore.com/blog/ecdsa-vs-rsa-everything-you-need-to-know/). So I would say that the scanner cannot differentiate between these two technologies and just think 256 is a small number.

**Comment by josegonzalez** [comment]
Great the scanner is a bullshit scanner! You should ask for you money back, and instead invest that in Dokku and @JonasAlfredsson :D

Closing as there is nothing to do here :)

**Comment by GORGES** [comment]
Thanks, Jose and Jonas. The scanner folks did confirm the issue, so I suspect that a patch will be done before too long. I'm a Dokku fan and paid supporter - great product.
