### ISSUE TITLE
Migrating Server

### ISSUE THREAD

**Issue by wonderer007** [dokku/dokku-letsencrypt#254]
I installed SSL certificate via `dokku-letsencrypt` and it worked fine. I moved my site to new server and then I started getting **ERR_SSL_VERSION_OR_CIPHER_MISMATCH** 

Do I first need to remove the certificate from old server ?

**Comment by patrickmillerson** [comment]
Hi there.
Did you get a solution for this?

I have now the same issue.
Stil stuck with it.
