### ISSUE TITLE
`letsencrypt` is not a dokku command.

### ISSUE THREAD

**Issue by emadzz** [dokku/dokku-letsencrypt#255]
> If you're using Dokku - especially for commercial purposes - consider donating to project development via [OpenCollective](https://opencollective.com/dokku) or [Patreon](https://www.patreon.com/dokku). Funds go to general development, support, and infrastructure costs.
>
> If you'd like to sponsor specific functionality, see the project's [Sponsoring](https://github.com/dokku/.github/blob/master/SPONSORING.md) document.
>
> If you need support for a version of Dokku that is more than a year old, your issue may be closed without an answer. Please upgrade to a recent version before filing an issue.

## Description of problem
After installing the dokku-letsencrypt the `dokku letsencrypt` is not found

### How reproducible / Steps to Reproduce

1.
  ```
  wget https://raw.githubusercontent.com/dokku/dokku/v0.27.0/bootstrap.sh
  sudo DOKKU_TAG=v0.27.0 bash bootstrap.sh
  ```
2. ```sudo dokku plugin:install https://github.com/dokku/dokku-letsencrypt.git```
3. ```dokku letsencrypt my-app```

#### Actual Results
```
 !     `letsencrypt` is not a dokku command.
 !     See `dokku help` for a list of available commands.
```

#### Expected Results
The letsencrypt certificate to be requested and installed for the target app

### `dokku report APP_NAME` output
I believe this issue isn't app-specific. Running `dokku letsencrypt` without specifying an app still yields the same result

### How (deb/make/rpm) and where (AWS, VirtualBox, physical, etc.) was Dokku installed?:
DigitalOcean - Ubuntu 21.04

### Additional information
* This was a fresh dokku installation, and an Nginx server already existed with enabled sites.
* `dokku version 0.27.0`
* The plugin `letsencrypt` appears at the end of the available dokku commands when running `dokku`.
```
Usage: dokku [--quiet|--trace|--force] COMMAND <app> [command-specific-options]

Primary help options, type "dokku COMMAND:help" for more details, or dokku help --all to see all commands.

Commands:

    app-json                 Manage app-json settings for an app
    apps                     Manage apps
    builder                  Manage builder settings for an app
    builder-dockerfile       Manage the dockerfile builder integration for an app
    builder-null             No-op builder plugin
    builder-pack             Manage the pack builder integration for an app
    buildpacks               Manage buildpack settings for an app
    certs                    Manage SSL (TLS) certs
    checks                   Manage zero-downtime settings
    cleanup                  Cleans up exited/dead Docker containers and removes dangling images
    config                   Manage global and app-specific config vars
    cron                     Manage scheduled cron tasks
    docker-options           Manage docker options for an app
    domains                  Manage domains used by the proxy
    enter                    Enter running app containers
    events                   Manage event logging
    git                      Manage app deploys via git
    help                     Print the list of commands
    logs                     Manage log integration for an app
    network                  Manage network settings for an app
    nginx                    Manage the nginx proxy
    plugin                   Manage installed plugins
    proxy                    Manage the proxy integration for an app
    ps                       Manage app processes
    registry                 Manage registry settings for an app
    repo                     Manage the app's repo
    resource                 Manage resource settings for an app
    run                      Run a one-off process inside a container
    scheduler                Manage scheduler settings for an app
    scheduler-docker-local   Manage the docker-local scheduler integration for an app
    scheduler-null           No-op scheduler plugin
    shell                    Interactive dokku prompt
    ssh-keys                 Manage public ssh keys used for deployment
    storage                  Manage mounted volumes
    trace                    Manage trace mode
    url                      Show the first URL for an application (compatibility)
    urls                     Show all URLs for an application
    version                  Print dokku's version

Community plugin commands:

    letsencrypt   Plugin for managing letsencrypt app integration
```

**Comment by JorgeOchoaReyes** [comment]
Ran across the same issue, I ran the config command: 

`dokku config:set --no-restart myapp DOKKU_LETSENCRYPT_EMAIL=your@email.tld`

and after setting the domain name ran: 

`dokku letsencrypt:enable myapp `

Hope this helps.
