### ISSUE TITLE
post-domains-update issue

### ISSUE THREAD

**Issue by stephenheron** [dokku/dokku-letsencrypt#264]
## Description of problem
We had an existing app that had letsencrypt enabled and we attempted to add another domain to this app. When doing this we continually got an error from letsencrypt saying: "acme: error: 403 :: urn:ietf:params:acme:error:unauthorized". 

It appears that the letsencrypt plugin now automatically attempts to get a cert when adding a new domain (https://github.com/dokku/dokku-letsencrypt/blob/master/post-domains-update). Unfortunately from my experience this fails as the domain has not yet been setup in nginx so the letsencrypt http validation check fails. 

To get my domain added I had to remove the 'post-domains-update' script and then add the domain. 

### Steps to Reproduce

1. Add App
2. Enable letsencrypt for app
3. Add domain 

#### Actual Results
LetsEncrypt will fail 

#### Expected Results
Domain is added and cert is generated

**Comment by AxelTheGerman** [comment]
I'm getting a similar error it seems - I just changed the domain for my dokku server and trying to enable letsencrypt for my test up is not working anymore:

```
~# dokku letsencrypt:enable test-rails
=====> Enabling letsencrypt for test-rails
-----> Enabling ACME proxy for test-rails...
-----> Getting letsencrypt certificate for test-rails...
        - Domain 'test-rails.my-new-host.com'
       2022/06/08 14:18:35 [INFO] [test-rails.my-new-host.com] acme: Obtaining bundled SAN certificate
       2022/06/08 14:18:35 [INFO] [test-rails.my-new-host.com] AuthURL: https://acme-v02.api.letsencrypt.org/acme/authz-v3/117453972956
       2022/06/08 14:18:35 [INFO] [test-rails.my-new-host.com] acme: Could not find solver for: tls-alpn-01
       2022/06/08 14:18:35 [INFO] [test-rails.my-new-host.com] acme: use http-01 solver
       2022/06/08 14:18:35 [INFO] [test-rails.my-new-host.com] acme: Trying to solve HTTP-01
       2022/06/08 14:18:41 [INFO] Deactivating auth: https://acme-v02.api.letsencrypt.org/acme/authz-v3/117453972956
       2022/06/08 14:18:41 Could not obtain certificates:
        error: one or more domains had a problem:
       [test-rails.my-new-host.com] acme: error: 403 :: urn:ietf:params:acme:error:unauthorized :: 52.128.23.153: Invalid response from http://test-rails.my-new-host.com/.well-known/acme-challenge/46vNc78PrheoRSAjhG_18xlJbpPUgu9xRXMuYrtyVXM: "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01//EN\" \"http://www.w3.org/TR/html4/strict.dtd\">\n<html>\n<head>\n<meta http-equiv=\"Conte"
-----> Certificate retrieval failed!
-----> Disabling ACME proxy for test-rails...
 !     Failed to setup letsencrypt
 !     Check log output for further information on failure
```

```
~# dokku -v
dokku version 0.27.2
```

Wondering if there is any manual workaround.

**Comment by stephenheron** [comment]
@josegonzalez Sorry I didn't save the log output unfortunately. I am off holiday this week from work but once I am back next week I will see if I can replicate and post some logs for you.

**Comment by josegonzalez** [comment]
@stephenheron any chance you have the logs for this again?

**Comment by josegonzalez** [comment]
The authorization link in the output (link here: https://acme-v02.api.letsencrypt.org/acme/authz-v3/124291999536) shows that it got a 403 forbidden. Do you have some redirect plugin or something enabled for the app? Mind posting the output of `dokku report $APP` for the app in question?

**Comment by stephenheron** [comment]
Ah doh! Yeah we do actually have the redirect plugin enabled (https://github.com/dokku/dokku-redirect) and a basic auth plugin (https://github.com/dokku/dokku-http-auth) both of which might be causing an issue.

Here is the report you asked for:

-----> uname: Linux web-1 5.11.0-1029-gcp #33~20.04.3-Ubuntu SMP Tue Jan 18 12:03:29 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
-----> memory:
                     total        used        free      shared  buff/cache   available
       Mem:           7949        4956         518         588        2475        2133
       Swap:             0           0           0
-----> docker version:
       Client: Docker Engine - Community
        Version:           20.10.12
        API version:       1.41
        Go version:        go1.16.12
        Git commit:        e91ed57
        Built:             Mon Dec 13 11:45:33 2021
        OS/Arch:           linux/amd64
        Context:           default
        Experimental:      true

       Server: Docker Engine - Community
        Engine:
         Version:          20.10.12
         API version:      1.41 (minimum version 1.12)
         Go version:       go1.16.12
         Git commit:       459d0df
         Built:            Mon Dec 13 11:43:42 2021
         OS/Arch:          linux/amd64
         Experimental:     false
        containerd:
         Version:          1.4.12
         GitCommit:        7b11cfaabd73bb80907dd23182b9347b4245eb5d
        runc:
         Version:          1.0.2
         GitCommit:        v1.0.2-0-g52b36a2
        docker-init:
         Version:          0.19.0
         GitCommit:        de40ad0
-----> docker daemon info:
       Client:
        Context:    default
        Debug Mode: true
        Plugins:
         app: Docker App (Docker Inc., v0.9.1-beta3)
         buildx: Docker Buildx (Docker Inc., v0.7.1-docker)
         scan: Docker Scan (Docker Inc., v0.12.0)

       Server:
        Containers: 29
         Running: 29
         Paused: 0
         Stopped: 0
        Images: 199
        Server Version: 20.10.12
        Storage Driver: overlay2
         Backing Filesystem: extfs
         Supports d_type: true
         Native Overlay Diff: true
         userxattr: false
        Logging Driver: json-file
        Cgroup Driver: cgroupfs
        Cgroup Version: 1
        Plugins:
         Volume: local
         Network: bridge host ipvlan macvlan null overlay
         Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
        Swarm: inactive
        Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
        Default Runtime: runc
        Init Binary: docker-init
        containerd version: 7b11cfaabd73bb80907dd23182b9347b4245eb5d
        runc version: v1.0.2-0-g52b36a2
        init version: de40ad0
        Security Options:
         apparmor
         seccomp
          Profile: default
        Kernel Version: 5.11.0-1029-gcp
        Operating System: Ubuntu 20.04.3 LTS
        OSType: linux
        Architecture: x86_64
        CPUs: 2
        Total Memory: 7.763GiB
        Name: web-1
        ID: KCA7:PO4Z:K3UM:CX5I:52NO:OXMA:52BB:OODU:UBME:LTLX:EC3L:LKRE
        Docker Root Dir: /var/lib/docker
        Debug Mode: false
        Registry: https://index.docker.io/v1/
        Labels:
        Experimental: false
        Insecure Registries:
         127.0.0.0/8
        Live Restore Enabled: false

-----> git version: git version 2.25.1
-----> sigil version: 0.7.1build+1ec3006
-----> herokuish version:
       herokuish: 0.5.33
       buildpacks:
         heroku-buildpack-multi     v1.0.0
         heroku-buildpack-ruby      v232
         heroku-buildpack-nodejs    v189
         heroku-buildpack-clojure   v87
         heroku-buildpack-python    v204
         heroku-buildpack-java      v69
         heroku-buildpack-gradle    v35
         heroku-buildpack-scala     v91
         heroku-buildpack-play      v26
         heroku-buildpack-php       v201
         heroku-buildpack-go        v157
         heroku-buildpack-nginx     v15
         buildpack-null             v3
-----> dokku version: dokku version 0.26.5
-----> plugn version: plugn: 0.7.1build+9bf216b
-----> dokku plugins:
         00_dokku-standard    0.26.5 enabled    dokku core standard plugin
         20_events            0.26.5 enabled    dokku core events logging plugin
         app-json             0.26.5 enabled    dokku core app-json plugin
         apps                 0.26.5 enabled    dokku core apps plugin
         builder              0.26.5 enabled    dokku core builder plugin
         builder-dockerfile   0.26.5 enabled    dokku core builder-dockerfile plugin
         builder-herokuish    0.26.5 enabled    dokku core builder-herokuish plugin
         builder-null         0.26.5 enabled    dokku core builder-null plugin
         builder-pack         0.26.5 enabled    dokku core builder-pack plugin
         buildpacks           0.26.5 enabled    dokku core buildpacks plugin
         certs                0.26.5 enabled    dokku core certificate management plugin
         checks               0.26.5 enabled    dokku core checks plugin
         common               0.26.5 enabled    dokku core common plugin
         config               0.26.5 enabled    dokku core config plugin
         cron                 0.26.5 enabled    dokku core cron plugin
         docker-options       0.26.5 enabled    dokku core docker-options plugin
         domains              0.26.5 enabled    dokku core domains plugin
         enter                0.26.5 enabled    dokku core enter plugin
         git                  0.26.5 enabled    dokku core git plugin
         http-auth            0.4.0 enabled    HTTP authentication for apps
         letsencrypt          0.14.2 enabled    Automated installation of let's encrypt TLS certificates
         logs                 0.26.5 enabled    dokku core logs plugin
         mysql                1.15.1 enabled    dokku mysql service plugin
         network              0.26.5 enabled    dokku core network plugin
         nginx-vhosts         0.26.5 enabled    dokku core nginx-vhosts plugin
         plugin               0.26.5 enabled    dokku core plugin plugin
         proxy                0.26.5 enabled    dokku core proxy plugin
         ps                   0.26.5 enabled    dokku core ps plugin
         redirect             0.7.1 enabled    Plugin for managing application redirects
         registry             0.26.5 enabled    dokku core registry plugin
         repo                 0.26.5 enabled    dokku core repo plugin
         resource             0.26.5 enabled    dokku core resource plugin
         run                  0.26.5 enabled    dokku core run plugin
         scheduler            0.25.6 enabled    dokku core scheduler plugin
         scheduler-docker-local 0.26.5 enabled    dokku core scheduler-docker-local plugin
         scheduler-null       0.26.5 enabled    dokku core scheduler-null plugin
         shell                0.26.5 enabled    dokku core shell plugin
         ssh-keys             0.26.5 enabled    dokku core ssh-keys plugin
         storage              0.26.5 enabled    dokku core storage plugin
         trace                0.26.5 enabled    dokku core trace plugin
=====> test-domain-prod app-json information
       App json computed selected:    app.json
       App json global selected:      app.json
       App json selected:
=====> test-domain-prod app information
       App created at:                1656343825
       App deploy source:             test-domain-prod
       App deploy source metadata:    test-domain-prod
       App dir:                       /home/dokku/test-domain-prod
       App locked:                    false
=====> test-domain-prod builder information
       Builder build dir:
       Builder computed build dir:
       Builder computed selected:
       Builder global build dir:
       Builder global selected:
       Builder selected:
=====> test-domain-prod builder-dockerfile information
       Builder dockerfile computed dockerfile path: Dockerfile
       Builder dockerfile global dockerfile path: Dockerfile
       Builder dockerfile dockerfile path:
=====> test-domain-prod builder-pack information
       Builder pack computed projecttoml path: project.toml
       Builder pack global projecttoml path: project.toml
       Builder pack projecttoml path:
=====> test-domain-prod buildpacks information
       Buildpacks computed stack:     gliderlabs/herokuish:latest-20
       Buildpacks global stack:
       Buildpacks list:
       Buildpacks stack:
=====> test-domain-prod ssl information
       Ssl dir:                       /home/dokku/test-domain-prod/tls
       Ssl enabled:                   true
       Ssl hostnames:                 test-domain-prod.clients.test.com test-domain.com testdomain.com www.test-domain.com www.testdomain.com www2.test-domain.com
       Ssl expires at:                Sep 25 14:30:04 2022 GMT
       Ssl issuer:                    C = US, O = Let's Encrypt, CN = R3
       Ssl starts at:                 Jun 27 14:30:05 2022 GMT
       Ssl subject:                   subject=CN = test-domain-prod.clients.test.com
       Ssl verified:                  self signed
=====> test-domain-prod checks information
       Checks disabled list:          none
       Checks skipped list:           none
=====> test-domain-prod cron information
       Cron task count:               0
=====> test-domain-prod docker options information
       Docker options build:          --link dokku.mysql.test-domain-prod-db:dokku-mysql-test-domain-prod-db
       Docker options deploy:         --link dokku.mysql.test-domain-prod-db:dokku-mysql-test-domain-prod-db --restart=on-failure:10
       Docker options run:            --link dokku.mysql.test-domain-prod-db:dokku-mysql-test-domain-prod-db
=====> test-domain-prod domains information
       Domains app enabled:           true
       Domains app vhosts:            test-domain-prod.clients.test.com test-domain.com www.test-domain.com testdomain.com www.testdomain.com www2.test-domain.com
       Domains global enabled:        true
       Domains global vhosts:         clients.test.com
=====> test-domain-prod git information
       Git deploy branch:             master
       Git global deploy branch:      master
       Git keep git dir:              false
       Git rev env var:               GIT_REV
       Git sha:                       f4448d4
       Git last updated at:
/var/lib/dokku/plugins/enabled/letsencrypt/report: line 2: /var/lib/dokku/plugins/available/letsencrypt/command-functions: No such file or directory
/var/lib/dokku/plugins/enabled/letsencrypt/report: line 6: cmd-letsencrypt-report-single: command not found
2022/06/28 09:16:43 exit status 127

**Comment by brylie** [comment]
I am having difficulty auto-renewing Dokku LetsEncrypt certificates. In our configuration, we removed the default proxy ports and added a mapping for port 443 to our backend server running on 8000:

`dokku proxy:ports-add caregiving-app https:443:8000`

I am getting errors when trying to renew the certificate with the proxy port mapping configuration:

```
error: one or more domains had a problem:
       [caregiving.geri.life] acme: error: 403 :: urn:ietf:params:acme:error:unauthorized :: 65.21.181.240: Invalid response from http://.../.well-known/acme-challenge/P7MiJYiHg3k6rPjnukE5Gi1ATShFk5txYUF98cOaUSc: 404
```

**Comment by josegonzalez** [comment]
@brylie you have a different issue from this. Please file a new ticket.

**Comment by brylie** [comment]
I'll open a different ticket, it just seems like the same issue since it is the same error.
