### ISSUE TITLE
Misaligned architectures: running `linux/amd64` pod on `linux/arm64/v8` machine.

### ISSUE THREAD

**Issue by c4lliope** [dokku/dokku-letsencrypt#278]
## Description of problem

I made a postgres database called "memory" on a Raspberry Pi 4 Arm64 machine.
I ran:

```bash
access@silicon:~$ sudo dokku postgres:create memory
       Waiting for container to be ready
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
exec /entrypoint: exec format error
```

Oddly, `sudo dokku postgres:list` does display "memory",
and I can link up a program's pod and use the database, no problems.

Is there a reason this "warning" is breaking and causing a non-zero code?
Can I run commands so I ensure `arm64`-based pods are used?

**Comment by josegonzalez** [comment]
I think this is the `wait` image that has to be re-released to support all architectures.

**Comment by c4lliope** [comment]
huh. non-breaking, in any case. only my bash command chains ended up bruised.
