### ISSUE TITLE
Broken network after reboot

### ISSUE THREAD

**Issue by jcalfee** [dokku/dokku-letsencrypt#280]
## Description of problem

My first install and deploy went well until I rebooted and discovered the VPS lost all network access.  I used a VPS at https://hostwinds.com/ .. It seems to be the `docker0` interface in `/etc/network/interfaces`.   Their VPS installs with an interface of `ens3` and, after the reboot (that is just when I noticed), two things changed: (1) the `ens3` interface was replaced with `docker` and the `dns-nameservers` line that had space separated DNS name server IP addresses went blank.  It appears that dokku needs to proxy the network to docker?  

Simply adding the dns-nameservers back did not fix the network. 

### How reproducible

Install `dokku` on a statically configured VPS like hostwinds and reboot.

## Environment Information

Debian 10

**Comment by jcalfee** [comment]
The networking was fixed when I set the interface back to `ens3` and had name server IPs listed again.

**Comment by jcalfee** [comment]
Sorry, wrong repo. Let me know if you want me to recreate this.. or maybe you have a move feature.

**Comment by josegonzalez** [comment]
I don't think this is a problem Dokku can fix. It seems like it's an issue with your hosting provider doing strange things to the base OS they install. Dokku doesn't manage network interfaces, so I'd imagine the hosting provider just breaks docker networking on reboot.

I would suggest filing a ticket with your hosting provider to see what they are doing on reboot (or maybe get a new hosting provider that doesn't break Docker networking).
