### ISSUE TITLE
Sharing certs..

### ISSUE THREAD

**Issue by jcalfee** [dokku/dokku-letsencrypt#281]
If I were to setup multiple dokku instances with the same app on them, is there an easy way to share the certs?  I suppose they could each get a cert as long as it is under the rate limit at LetsEncrypt.  If there is a way to share this through a mount or something and the code has a check to use one if it already exists, please let me know.  

Example: https://doc.traefik.io/traefik/v1.7/configuration/acme/#as-a-file

**Comment by josegonzalez** [comment]
Dokku itself manages a single server (though you can back it with a kubernetes or nomad cluster), so if you want to share files across servers, you will need to manually sync the files.

Alternative proxy implementations - such as traefik - may implement this on their own. By way of example, our Kubernetes integration supports Letsencrypt via the CertManager integration.

Dokku itself won't implement this sort of functionality, as it is best done at the proxy-layer.
