### ISSUE TITLE
README.md - Dokku documentation hyperlinks return 404

### ISSUE THREAD

**Issue by kmeyerhofer** [dokku/dokku-letsencrypt#282]
## Description of problem

There are 3 Dokku documentation hyperlinks in `README.md` that when redirected, return a 404 page. It looks like some links didn't survive the migration from `dokku.viewdocs.io/dokku` to `dokku.com/docs`.

These links are:

1. http://dokku.viewdocs.io/dokku/configuration/nginx/
2. http://dokku.viewdocs.io/dokku/configuration-management/
3. http://dokku.viewdocs.io/dokku/advanced-usage/proxy-management/#proxy-port-mapping

**Comment by josegonzalez** [comment]
Thanks for reporting!
