### ISSUE TITLE
Apple plugin by default 

### ISSUE THREAD

**Issue by weeebdev** [dokku/dokku-letsencrypt#284]
How can I run the plugin on each app by default? So that when I create an app, its automatically encrypted. Thanks

**Comment by Gys** [comment]
Your question is not very clear? Maybe this gives an answer: https://github.com/dokku/dokku-letsencrypt/issues/287#issuecomment-1326707574

**Comment by gleniat** [comment]
@weeebdev 
You may try a new plugin I have developed: https://github.com/gleniat/dokku-letsencrypt-auto-enable

Please test it and report any issues.

**Comment by josegonzalez** [comment]
This isn't functionality I want to add to the plugin at this time. A community plugin is likely a better fit.
