### ISSUE TITLE
unauthorized when using on a umami app

### ISSUE THREAD

**Issue by IgnisDa** [dokku/dokku-letsencrypt#286]
Hello, I tried to get [Umami](https://umami.is/) running with Dokku but was unsucessful in securing it with `https`. `dokku letsencrypt:enable umami` failed with this error:

<img width="1254" alt="image" src="https://user-images.githubusercontent.com/60938164/202208280-1837edd3-4670-4707-9cf0-3d1f904241cb.png">

Here are the steps to get to where I was

```bash
APPNAME="umami"
dokku apps:create "$APPNAME"
dokku postgres:create "$APPNAME"
dokku postgres:link "$APPNAME" "$APPNAME"
IMAGE_NAME="docker.umami.dev/umami-software/umami:postgresql-latest"
docker pull $IMAGE_NAME
image_sha="$(docker inspect --format='{{index .RepoDigests 0}}' $IMAGE_NAME)"
dokku git:from-image "$APPNAME" "$image_sha"
```

It was being tracked in https://github.com/umami-software/umami/issues/1655, but it seems like a dokku related error.

**Comment by josegonzalez** [comment]
This is by design. Due to how we handle ports for Dockerfile/Docker images that use an `EXPOSE` directive, you must manually manage your ports as documented [here](https://github.com/dokku/dokku-letsencrypt#dockerfile-deploys) in order to enable letsencrypt.
