### ISSUE TITLE
Automatically activate Lets Encrypt when a new app is created

### ISSUE THREAD

**Issue by gleniat** [dokku/dokku-letsencrypt#287]
## Description of problem
How to make Dokku automatically add Lets Encrypt plugin and obtain a certificate when a new app is created?

#### Actual Results
A newly created app is served by HTTP. I have to run `dokku letsencrypt:enable appname` manually each time a new app is created or cloned (even when the cloned app has HTTPS already activated).

#### Expected Results
Obtain LE cert to all new successfully built apps automatically.

**Comment by Gys** [comment]
This might be better solved at the Dokku level. Maybe with a kind of post deploy. For example using this plugin: https://github.com/baikunz/dokku-post-deploy-script

**Comment by gleniat** [comment]
Thank you Gys for mentioning a post-deploy hook.

I have developed two new plugins for this:
https://github.com/gleniat/dokku-letsencrypt-auto-enable
https://github.com/gleniat/dokku-letsencrypt-auto-enable-allow-list

**Comment by josegonzalez** [comment]
This isn't functionality I want to add to the plugin at this time. A community plugin is likely a better fit.

**Comment by gleniat** [comment]
Hi @josegonzalez, could you please clarify why you don't want to add it? Are there any technical reasons? Or you just don't have time to support a new functionality, or something else?

I was missing 2 dokku-letsencrypt commands during the development of my plugin (it currently feels a bit hacky). I was missing something like: 
```
dokku letsencrypt:enable --enable-if-not-enabled-already <appname> 
```

```
dokku letsencrypt:isenabled <appname> (prints True or False)
```

**Comment by Gys** [comment]
Regarding your missing commands:

`dokku letsencrypt:active <app>` is what you are looking for with 'isenabled' ?

So for 'enable-if-not-enabled-already' you can do:

`dokku letsencrypt:active <app> || dokku letsencrypt:enable <app>`

**Comment by josegonzalez** [comment]
I don't want to add the functionality because I don't want to add the functionality. More code == more for me to maintain. It's also easy enough for someone to just run that command when they create an app.

**Comment by gleniat** [comment]
> is what you are looking for with 'isenabled' ?

Great! Thanks. I was using a version from June that didn't have this so I missed the new feature.

> It's also easy enough for someone to just run that command

It's not that it's lot of work to run additional command during manual creation of the app. That's easy.

The issue is that CI doesn't preserve HTTPS for cloned apps. When I use [Dokku Github Action](https://github.com/dokku/github-action) for an app and its automatic creation of review apps (a new git branch => a new app), Let's Encrypt is not reenabled for the clones.

**Comment by josegonzalez** [comment]
For the github action, you can use the example at the bottom:

> Placing a shell script at bin/ci-pre-deploy can be used to reconfigure the app, as shown in [this example](https://github.com/dokku/github-action/blob/master/example-workflows/review-app/ci-pre-deploy).

And check if the review app has LE enabled, if not, enable it.
