### ISSUE TITLE
Error on adding cron job: new crontab file is missing newline before EOF, can't install

### ISSUE THREAD

**Issue by ivmirx** [dokku/dokku-letsencrypt#300]
## Description of problem
For some reason, cert autorenewal doesn't work for my apps and trying to add it manually with `dokku letsencrypt:cron-job --add` results in the error message "new crontab file is missing newline before EOF, can't install."

The cron file for Dokku at `/var/spool/cron/crontabs/dokku` definitely has some newlines:

	# DO NOT EDIT THIS FILE - edit the master and reinstall.
	# (/tmp/crontab.YnxTYv/crontab installed on Mon Feb 27 01:15:49 2023)
	# (Cron version -- $Id: crontab.c,v 2.13 1994/01/17 03:20:37 vixie Exp $)
	
	
	(last line here)

What could it be? Thanks in advance!

### Steps to Reproduce

1. run `dokku letsencrypt:cron-job --add`

#### Actual Results

Error message

#### Expected Results

Working command

## Environment Information

       -----> uname: Linux myusername 5.4.0-139-generic #156-Ubuntu SMP Fri Jan 20 17:27:18 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
       -----> memory:
                            total        used        free      shared  buff/cache   available
              Mem:            976         469         101          12         405         346
              Swap:             0           0           0
       -----> docker version:
              Client: Docker Engine - Community
               Version:           19.03.13
               API version:       1.40
               Go version:        go1.13.15
               Git commit:        4484c46d9d
               Built:             Wed Sep 16 17:02:52 2020
               OS/Arch:           linux/amd64
               Experimental:      false

              Server: Docker Engine - Community
               Engine:
                Version:          19.03.13
                API version:      1.40 (minimum version 1.12)
                Go version:       go1.13.15
                Git commit:       4484c46d9d
                Built:            Wed Sep 16 17:01:20 2020
                OS/Arch:          linux/amd64
                Experimental:     false
               containerd:
                Version:          1.6.18
                GitCommit:        2456e983eb9e37e47538f59ea18f2043c9a73640
               runc:
                Version:          1.1.4
                GitCommit:        v1.1.4-0-g5fd4c4d
               docker-init:
                Version:          0.18.0
                GitCommit:        fec3683
       -----> docker daemon info:
              Client:
               Debug Mode: true

              Server:
               Containers: 26
                Running: 6
                Paused: 0
                Stopped: 20
               Images: 36
               Server Version: 19.03.13
               Storage Driver: overlay2
                Backing Filesystem: extfs
                Supports d_type: true
                Native Overlay Diff: true
               Logging Driver: json-file
               Cgroup Driver: cgroupfs
               Plugins:
                Volume: local
                Network: bridge host ipvlan macvlan null overlay
                Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
               Swarm: inactive
               Runtimes: runc
               Default Runtime: runc
               Init Binary: docker-init
               containerd version: 2456e983eb9e37e47538f59ea18f2043c9a73640
               runc version: v1.1.4-0-g5fd4c4d
               init version: fec3683
               Security Options:
                apparmor
                seccomp
                 Profile: default
               Kernel Version: 5.4.0-139-generic
               Operating System: Ubuntu 20.04.5 LTS
               OSType: linux
               Architecture: x86_64
               CPUs: 1
               Total Memory: 976.8MiB
               Name: myusername
               ID: PEEB:CHZO:EMP7:XJR5:2ZB7:QM5F:TPDW:PHRP:MO73:X7YR:V5PN:LJDA
               Docker Root Dir: /var/lib/docker
               Debug Mode: false
               Registry: https://index.docker.io/v1/
               Labels:
               Experimental: false
               Insecure Registries:
                127.0.0.0/8
               Live Restore Enabled: false

       -----> sigil version: 0.9.0build+bc921b7
       -----> herokuish version:
              herokuish: v0.5.40
              buildpacks:
                heroku-buildpack-multi     v1.2.0
                heroku-buildpack-ruby      v244
                heroku-buildpack-nodejs    v202
                heroku-buildpack-clojure   v90
                heroku-buildpack-python    v223
                heroku-buildpack-java      v72
                heroku-buildpack-gradle    v38
                heroku-buildpack-scala     v96
                heroku-buildpack-play      v26
                heroku-buildpack-php       v227
                heroku-buildpack-go        v169
                heroku-buildpack-nginx     v22
                buildpack-null             v3
       -----> dokku version: dokku version 0.21.4
       -----> dokku plugins:
              plugn: 0.12.0build+3a27594
                00_dokku-standard    0.21.4 enabled    dokku core standard plugin
                20_events            0.21.4 enabled    dokku core events logging plugin
                app-json             0.21.4 enabled    dokku core app-json plugin
                apps                 0.21.4 enabled    dokku core apps plugin
                builder-dockerfile   0.21.4 enabled    dokku core builder-dockerfile plugin
                builder-herokuish    0.21.4 enabled    dokku core builder-herokuish plugin
                buildpacks           0.21.4 enabled    dokku core buildpacks plugin
                certs                0.21.4 enabled    dokku core certificate management plugin
                checks               0.21.4 enabled    dokku core checks plugin
                common               0.21.4 enabled    dokku core common plugin
                config               0.21.4 enabled    dokku core config plugin
                docker-options       0.21.4 enabled    dokku core docker-options plugin
                domains              0.21.4 enabled    dokku core domains plugin
                enter                0.21.4 enabled    dokku core enter plugin
                git                  0.21.4 enabled    dokku core git plugin
                letsencrypt          0.20.0 enabled    Automated installation of let's encrypt TLS certificates
                logs                 0.21.4 enabled    dokku core logs plugin
                mongo                1.21.0 enabled    dokku mongo service plugin
                network              0.21.4 enabled    dokku core network plugin
                nginx-vhosts         0.21.4 enabled    dokku core nginx-vhosts plugin
                plugin               0.21.4 enabled    dokku core plugin plugin
                postgres             1.24.0 enabled    dokku postgres service plugin
                proxy                0.21.4 enabled    dokku core proxy plugin
                ps                   0.21.4 enabled    dokku core ps plugin
                repo                 0.21.4 enabled    dokku core repo plugin
                resource             0.21.4 enabled    dokku core resource plugin
                scheduler-docker-local 0.21.4 enabled    dokku core scheduler-docker-local plugin
                shell                0.21.4 enabled    dokku core shell plugin
                ssh-keys             0.21.4 enabled    dokku core ssh-keys plugin
                storage              0.21.4 enabled    dokku core storage plugin
                tags                 0.21.4 enabled    dokku core tags plugin
                tar                  0.21.4 enabled    dokku core tar plugin
                trace                0.21.4 enabled    dokku core trace plugin

### How (deb/make) and where (AWS, VirtualBox, physical, etc.) was Dokku installed?:

[DigitalOcean one-click app](https://marketplace.digitalocean.com/apps/dokku)

### Additional information

Traced output for `dokku letsencrypt:cron-job --add`:

       + export DOKKU_HOST_ROOT=/home/dokku
       + DOKKU_HOST_ROOT=/home/dokku
       + export DOKKU_DISTRO
       ++ . /etc/os-release
       ++ echo ubuntu
       + DOKKU_DISTRO=ubuntu
       + export DOCKER_BIN=docker
       + DOCKER_BIN=docker
       + export DOKKU_IMAGE=gliderlabs/herokuish:latest
       + DOKKU_IMAGE=gliderlabs/herokuish:latest
       + export DOKKU_LIB_ROOT=/var/lib/dokku
       + DOKKU_LIB_ROOT=/var/lib/dokku
       + export PLUGIN_PATH=/var/lib/dokku/plugins
       + PLUGIN_PATH=/var/lib/dokku/plugins
       + export PLUGIN_AVAILABLE_PATH=/var/lib/dokku/plugins/available
       + PLUGIN_AVAILABLE_PATH=/var/lib/dokku/plugins/available
       + export PLUGIN_ENABLED_PATH=/var/lib/dokku/plugins/enabled
       + PLUGIN_ENABLED_PATH=/var/lib/dokku/plugins/enabled
       + export PLUGIN_CORE_PATH=/var/lib/dokku/core-plugins
       + PLUGIN_CORE_PATH=/var/lib/dokku/core-plugins
       + export PLUGIN_CORE_AVAILABLE_PATH=/var/lib/dokku/core-plugins/available
       + PLUGIN_CORE_AVAILABLE_PATH=/var/lib/dokku/core-plugins/available
       + export PLUGIN_CORE_ENABLED_PATH=/var/lib/dokku/core-plugins/enabled
       + PLUGIN_CORE_ENABLED_PATH=/var/lib/dokku/core-plugins/enabled
       + export DOKKU_SYSTEM_GROUP=dokku
       + DOKKU_SYSTEM_GROUP=dokku
       + export DOKKU_SYSTEM_USER=dokku
       + DOKKU_SYSTEM_USER=dokku
       + export DOKKU_API_VERSION=1
       + DOKKU_API_VERSION=1
       + export DOKKU_NOT_IMPLEMENTED_EXIT=10
       + DOKKU_NOT_IMPLEMENTED_EXIT=10
       + export DOKKU_VALID_EXIT=0
       + DOKKU_VALID_EXIT=0
       + export DOKKU_PID=43287
       + DOKKU_PID=43287
       + export DOKKU_LOGS_DIR=/var/log/dokku
       + DOKKU_LOGS_DIR=/var/log/dokku
       + export DOKKU_EVENTS_LOGFILE=/var/log/dokku/events.log
       + DOKKU_EVENTS_LOGFILE=/var/log/dokku/events.log
       + export DOKKU_CONTAINER_LABEL=dokku
       + DOKKU_CONTAINER_LABEL=dokku
       + export 'DOKKU_GLOBAL_BUILD_ARGS=--label=org.label-schema.schema-version=1.0 --label=org.label-schema.vendor=dokku --label=dokku'
       + DOKKU_GLOBAL_BUILD_ARGS='--label=org.label-schema.schema-version=1.0 --label=org.label-schema.vendor=dokku --label=dokku'
       + export 'DOKKU_GLOBAL_RUN_ARGS=--label=org.label-schema.schema-version=1.0 --label=org.label-schema.vendor=dokku --label=dokku'
       + DOKKU_GLOBAL_RUN_ARGS='--label=org.label-schema.schema-version=1.0 --label=org.label-schema.vendor=dokku --label=dokku'
       + source /var/lib/dokku/core-plugins/available/common/functions
       ++ set -eo pipefail
       ++ [[ -n 1 ]]
       ++ set -x
       + parse_args letsencrypt:cron-job --add
       + declare 'desc=top-level cli arg parser'
       + local next_index=1
       + local skip=false
       + args=("$@")
       + local args
       + local flags
       + for arg in "$@"
       + [[ false == \t\r\u\e ]]
       + case "$arg" in
       + [[ false == \t\r\u\e ]]
       + [[ letsencrypt:cron-job == \-\-\a\p\p ]]
       + [[ letsencrypt:cron-job =~ ^--.* ]]
       + next_index=2
       + for arg in "$@"
       + [[ false == \t\r\u\e ]]
       + case "$arg" in
       + [[ false == \t\r\u\e ]]
       + [[ --add == \-\-\a\p\p ]]
       + [[ --add =~ ^--.* ]]
       + flags=' --add'
       + next_index=3
       + [[ -z '' ]]
       ++ sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//'
       ++ echo -e ' --add'
       + export DOKKU_GLOBAL_FLAGS=--add
       + DOKKU_GLOBAL_FLAGS=--add
       + return 0
       + args=("$@")
       + skip_arg=false
       + [[ letsencrypt:cron-job =~ ^--.* ]]
       + has_tty
       + declare 'desc=return 0 if we have a tty'
       ++ LC_ALL=C
       ++ /usr/bin/tty
       + [[ /dev/pts/0 == \n\o\t\ \a\ \t\t\y ]]
       + return 0
       ++ id -un
       + [[ root != \d\o\k\k\u ]]
       + [[ ! letsencrypt:cron-job =~ plugin:* ]]
       + [[ letsencrypt:cron-job != \s\s\h\-\k\e\y\s\:\a\d\d ]]
       + [[ letsencrypt:cron-job != \s\s\h\-\k\e\y\s\:\r\e\m\o\v\e ]]
       ++ id -un
       + export SSH_USER=root
       + SSH_USER=root
       + sudo -u dokku -E -H /usr/bin/dokku letsencrypt:cron-job --add
       + export DOKKU_HOST_ROOT=/home/dokku
       + DOKKU_HOST_ROOT=/home/dokku
       + export DOKKU_DISTRO
       ++ . /etc/os-release
       ++ echo ubuntu
       + DOKKU_DISTRO=ubuntu
       + export DOCKER_BIN=docker
       + DOCKER_BIN=docker
       + export DOKKU_IMAGE=gliderlabs/herokuish:latest
       + DOKKU_IMAGE=gliderlabs/herokuish:latest
       + export DOKKU_LIB_ROOT=/var/lib/dokku
       + DOKKU_LIB_ROOT=/var/lib/dokku
       + export PLUGIN_PATH=/var/lib/dokku/plugins
       + PLUGIN_PATH=/var/lib/dokku/plugins
       + export PLUGIN_AVAILABLE_PATH=/var/lib/dokku/plugins/available
       + PLUGIN_AVAILABLE_PATH=/var/lib/dokku/plugins/available
       + export PLUGIN_ENABLED_PATH=/var/lib/dokku/plugins/enabled
       + PLUGIN_ENABLED_PATH=/var/lib/dokku/plugins/enabled
       + export PLUGIN_CORE_PATH=/var/lib/dokku/core-plugins
       + PLUGIN_CORE_PATH=/var/lib/dokku/core-plugins
       + export PLUGIN_CORE_AVAILABLE_PATH=/var/lib/dokku/core-plugins/available
       + PLUGIN_CORE_AVAILABLE_PATH=/var/lib/dokku/core-plugins/available
       + export PLUGIN_CORE_ENABLED_PATH=/var/lib/dokku/core-plugins/enabled
       + PLUGIN_CORE_ENABLED_PATH=/var/lib/dokku/core-plugins/enabled
       + export DOKKU_SYSTEM_GROUP=dokku
       + DOKKU_SYSTEM_GROUP=dokku
       + export DOKKU_SYSTEM_USER=dokku
       + DOKKU_SYSTEM_USER=dokku
       + export DOKKU_API_VERSION=1
       + DOKKU_API_VERSION=1
       + export DOKKU_NOT_IMPLEMENTED_EXIT=10
       + DOKKU_NOT_IMPLEMENTED_EXIT=10
       + export DOKKU_VALID_EXIT=0
       + DOKKU_VALID_EXIT=0
       + export DOKKU_PID=43297
       + DOKKU_PID=43297
       + export DOKKU_LOGS_DIR=/var/log/dokku
       + DOKKU_LOGS_DIR=/var/log/dokku
       + export DOKKU_EVENTS_LOGFILE=/var/log/dokku/events.log
       + DOKKU_EVENTS_LOGFILE=/var/log/dokku/events.log
       + export DOKKU_CONTAINER_LABEL=dokku
       + DOKKU_CONTAINER_LABEL=dokku
       + export 'DOKKU_GLOBAL_BUILD_ARGS=--label=org.label-schema.schema-version=1.0 --label=org.label-schema.vendor=dokku --label=dokku'
       + DOKKU_GLOBAL_BUILD_ARGS='--label=org.label-schema.schema-version=1.0 --label=org.label-schema.vendor=dokku --label=dokku'
       + export 'DOKKU_GLOBAL_RUN_ARGS=--label=org.label-schema.schema-version=1.0 --label=org.label-schema.vendor=dokku --label=dokku'
       + DOKKU_GLOBAL_RUN_ARGS='--label=org.label-schema.schema-version=1.0 --label=org.label-schema.vendor=dokku --label=dokku'
       + source /var/lib/dokku/core-plugins/available/common/functions
       ++ set -eo pipefail
       ++ [[ -n 1 ]]
       ++ set -x
       + parse_args letsencrypt:cron-job --add
       + declare 'desc=top-level cli arg parser'
       + local next_index=1
       + local skip=false
       + args=("$@")
       + local args
       + local flags
       + for arg in "$@"
       + [[ false == \t\r\u\e ]]
       + case "$arg" in
       + [[ false == \t\r\u\e ]]
       + [[ letsencrypt:cron-job == \-\-\a\p\p ]]
       + [[ letsencrypt:cron-job =~ ^--.* ]]
       + next_index=2
       + for arg in "$@"
       + [[ false == \t\r\u\e ]]
       + case "$arg" in
       + [[ false == \t\r\u\e ]]
       + [[ --add == \-\-\a\p\p ]]
       + [[ --add =~ ^--.* ]]
       + flags=' --add'
       + next_index=3
       + [[ -z --add ]]
       + return 0
       + args=("$@")
       + skip_arg=false
       + [[ letsencrypt:cron-job =~ ^--.* ]]
       + has_tty
       + declare 'desc=return 0 if we have a tty'
       ++ LC_ALL=C
       ++ /usr/bin/tty
       + [[ /dev/pts/0 == \n\o\t\ \a\ \t\t\y ]]
       + return 0
       ++ id -un
       + [[ dokku != \d\o\k\k\u ]]
       + [[ letsencrypt:cron-job =~ ^plugin:.* ]]
       + [[ letsencrypt:cron-job == \s\s\h\-\k\e\y\s\:\a\d\d ]]
       + [[ letsencrypt:cron-job == \s\s\h\-\k\e\y\s\:\r\e\m\o\v\e ]]
       + [[ -n '' ]]
       + dokku_auth letsencrypt:cron-job --add
       + declare 'desc=calls user-auth plugin trigger'
       + export SSH_USER=root
       + SSH_USER=root
       + export SSH_NAME=default
       + SSH_NAME=default
       ++ wc -l
       ++ find /var/lib/dokku/plugins/enabled/20_events/user-auth
       + [[ 1 == 1 ]]
       + return 0
       + case "$1" in
       + execute_dokku_cmd letsencrypt:cron-job --add
       + declare 'desc=executes dokku sub-commands'
       + local PLUGIN_NAME=letsencrypt:cron-job
       + local PLUGIN_CMD=letsencrypt:cron-job
       + local implemented=0
       + local script
       + argv=("$@")
       + local argv
       + case "$PLUGIN_NAME" in
       ++ readlink -f /var/lib/dokku/plugins/enabled/letsencrypt
       + [[ /var/lib/dokku/plugins/available/letsencrypt == *core-plugins* ]]
       + [[ -x /var/lib/dokku/plugins/enabled/letsencrypt:cron-job/subcommands/default ]]
       + [[ -x /var/lib/dokku/plugins/enabled/letsencrypt:cron-job/subcommands/letsencrypt:cron-job ]]
       + [[ -x /var/lib/dokku/plugins/enabled/letsencrypt/subcommands/cron-job ]]
       + [[ -n cron-job ]]
       + /var/lib/dokku/plugins/enabled/letsencrypt/subcommands/cron-job letsencrypt:cron-job --add
       ++ source /var/lib/dokku/core-plugins/available/common/property-functions
       +++ set -eo pipefail
       +++ [[ -n 1 ]]
       +++ set -x
       ++ source /var/lib/dokku/plugins/available/letsencrypt/internal-functions
       +++ source /var/lib/dokku/core-plugins/available/common/functions
       ++++ set -eo pipefail
       ++++ [[ -n 1 ]]
       ++++ set -x
       +++ source /var/lib/dokku/core-plugins/available/certs/functions
       ++++ set -eo pipefail
       ++++ [[ -n 1 ]]
       ++++ set -x
       ++++ source /var/lib/dokku/core-plugins/available/common/functions
       +++++ set -eo pipefail
       +++++ [[ -n 1 ]]
       +++++ set -x
       +++ source /var/lib/dokku/core-plugins/available/domains/functions
       ++++ source /var/lib/dokku/core-plugins/available/common/functions
       +++++ set -eo pipefail
       +++++ [[ -n 1 ]]
       +++++ set -x
       ++++ source /var/lib/dokku/plugins/available/config/functions
       +++++ set -eo pipefail
       +++++ [[ -n 1 ]]
       +++++ set -x
       +++++ source /var/lib/dokku/core-plugins/available/common/functions
       ++++++ set -eo pipefail
       ++++++ [[ -n 1 ]]
       ++++++ set -x
       ++++ set -eo pipefail
       ++++ [[ -n 1 ]]
       ++++ set -x
       +++ source /var/lib/dokku/core-plugins/available/nginx-vhosts/functions
       ++++ set -eo pipefail
       ++++ [[ -n 1 ]]
       ++++ set -x
       ++++ source /var/lib/dokku/core-plugins/available/common/functions
       +++++ set -eo pipefail
       +++++ [[ -n 1 ]]
       +++++ set -x
       ++++ source /var/lib/dokku/plugins/available/certs/functions
       +++++ set -eo pipefail
       +++++ [[ -n 1 ]]
       +++++ set -x
       +++++ source /var/lib/dokku/core-plugins/available/common/functions
       ++++++ set -eo pipefail
       ++++++ [[ -n 1 ]]
       ++++++ set -x
       ++++ source /var/lib/dokku/plugins/available/config/functions
       +++++ set -eo pipefail
       +++++ [[ -n 1 ]]
       +++++ set -x
       +++++ source /var/lib/dokku/core-plugins/available/common/functions
       ++++++ set -eo pipefail
       ++++++ [[ -n 1 ]]
       ++++++ set -x
       ++++ source /var/lib/dokku/plugins/available/ps/functions
       +++++ set -eo pipefail
       +++++ [[ -n 1 ]]
       +++++ set -x
       +++++ source /var/lib/dokku/core-plugins/available/common/functions
       ++++++ set -eo pipefail
       ++++++ [[ -n 1 ]]
       ++++++ set -x
       +++++ source /var/lib/dokku/plugins/available/config/functions
       ++++++ set -eo pipefail
       ++++++ [[ -n 1 ]]
       ++++++ set -x
       ++++++ source /var/lib/dokku/core-plugins/available/common/functions
       +++++++ set -eo pipefail
       +++++++ [[ -n 1 ]]
       +++++++ set -x
       ++++ source /var/lib/dokku/plugins/available/nginx-vhosts/internal-functions
       +++++ set -eo pipefail
       +++++ [[ -n 1 ]]
       +++++ set -x
       +++++ source /var/lib/dokku/core-plugins/available/common/functions
       ++++++ set -eo pipefail
       ++++++ [[ -n 1 ]]
       ++++++ set -x
       +++++ source /var/lib/dokku/core-plugins/available/common/property-functions
       ++++++ set -eo pipefail
       ++++++ [[ -n 1 ]]
       ++++++ set -x
       +++++ dirname /var/lib/dokku/plugins/available/letsencrypt/internal-functions
       ++++ cd /var/lib/dokku/plugins/available/letsencrypt
       ++++ pwd
       +++ source /var/lib/dokku/plugins/available/letsencrypt/config
       ++++ set -eo pipefail
       ++++ [[ -n 1 ]]
       ++++ set -x
       ++++ export LETSENCRYPT_IMAGE=goacme/lego
       ++++ LETSENCRYPT_IMAGE=goacme/lego
       ++++ export LETSENCRYPT_IMAGE_VERSION=v4.9.1
       ++++ LETSENCRYPT_IMAGE_VERSION=v4.9.1
       ++++ export PLUGIN_DISABLE_PULL=
       ++++ PLUGIN_DISABLE_PULL=
       ++++ export PLUGIN_DISABLE_PULL_VARIABLE=LETSENCRYPT_DISABLE_PULL
       ++++ PLUGIN_DISABLE_PULL_VARIABLE=LETSENCRYPT_DISABLE_PULL
       ++++ export PLUGIN_IMAGE=goacme/lego
       ++++ PLUGIN_IMAGE=goacme/lego
       ++++ export PLUGIN_IMAGE_VERSION=v4.9.1
       ++++ PLUGIN_IMAGE_VERSION=v4.9.1
       ++++ export LETSENCRYPT_CRON_CMD=/var/lib/dokku/plugins/available/letsencrypt/cron-job
       ++++ LETSENCRYPT_CRON_CMD=/var/lib/dokku/plugins/available/letsencrypt/cron-job
       ++++ export 'LETSENCRYPT_CRON_JOB=@daily /var/lib/dokku/plugins/available/letsencrypt/cron-job'
       ++++ LETSENCRYPT_CRON_JOB='@daily /var/lib/dokku/plugins/available/letsencrypt/cron-job'
       +++ set -eo pipefail
       +++ [[ -n 1 ]]
       +++ set -x
       ++++ dirname /var/lib/dokku/plugins/available/letsencrypt/command-functions
       +++ cd /var/lib/dokku/plugins/available/letsencrypt
       +++ pwd
       ++ source /var/lib/dokku/plugins/available/letsencrypt/config
       +++ set -eo pipefail
       +++ [[ -n 1 ]]
       +++ set -x
       +++ export LETSENCRYPT_IMAGE=goacme/lego
       +++ LETSENCRYPT_IMAGE=goacme/lego
       +++ export LETSENCRYPT_IMAGE_VERSION=v4.9.1
       +++ LETSENCRYPT_IMAGE_VERSION=v4.9.1
       +++ export PLUGIN_DISABLE_PULL=
       +++ PLUGIN_DISABLE_PULL=
       +++ export PLUGIN_DISABLE_PULL_VARIABLE=LETSENCRYPT_DISABLE_PULL
       +++ PLUGIN_DISABLE_PULL_VARIABLE=LETSENCRYPT_DISABLE_PULL
       +++ export PLUGIN_IMAGE=goacme/lego
       +++ PLUGIN_IMAGE=goacme/lego
       +++ export PLUGIN_IMAGE_VERSION=v4.9.1
       +++ PLUGIN_IMAGE_VERSION=v4.9.1
       +++ export LETSENCRYPT_CRON_CMD=/var/lib/dokku/plugins/available/letsencrypt/cron-job
       +++ LETSENCRYPT_CRON_CMD=/var/lib/dokku/plugins/available/letsencrypt/cron-job
       +++ export 'LETSENCRYPT_CRON_JOB=@daily /var/lib/dokku/plugins/available/letsencrypt/cron-job'
       +++ LETSENCRYPT_CRON_JOB='@daily /var/lib/dokku/plugins/available/letsencrypt/cron-job'
       ++ set -eo pipefail
       ++ [[ -n 1 ]]
       ++ set -x
       + set -eo pipefail
       + [[ -n 1 ]]
       + set -x
       + cmd-letsencrypt-cron-job letsencrypt:cron-job --add
       + declare 'desc=Add or remove a cron job that periodically calls auto-renew'
       + declare cmd=letsencrypt:cron-job
       + [[ letsencrypt:cron-job == \l\e\t\s\e\n\c\r\y\p\t\:\c\r\o\n\-\j\o\b ]]
       + shift 1
       + declare FLAG=--add
       + [[ --add == \-\-\a\d\d ]]
       + fn-letsencrypt-cron-job-add
       + declare 'desc=Add auto-renew cronjob to dokku user'\''s crontab'
       + touch /var/lib/dokku/data/letsencrypt/autorenew
       + fn-letsencrypt-cron-job-enabled
       + declare 'desc=Check if the cron plugin is available'
       + [[ ! -f /var/lib/dokku/plugins/available/cron/cron-write ]]
       + return 1
       ++ crontab -l
       + crons=
       ++ grep -v -F /var/lib/dokku/plugins/available/letsencrypt/cron-job
       + crons=
       + crontab -
       + printf '%s\n%s' '' '@daily /var/lib/dokku/plugins/available/letsencrypt/cron-job'
       new crontab file is missing newline before EOF, can't install.

**Comment by tsboh** [comment]
Probably the same problem. I followed the installation steps of the plugin and got with the last step:
```
$ dokku letsencrypt:cron-job --add 
no crontab for dokku
new crontab file is missing newline before EOF, can't install.
```

Now I still have to update manually :-(, that was the whole purpose of the plugin, right? ;-)

**Comment by jirubio** [comment]
Reverting back to 0.18.1 worked for us.

```
dokku plugin:uninstall letsencrypt
dokku plugin:install https://github.com/dokku/dokku-letsencrypt.git --committish 0.18.1
```

**Comment by josegonzalez** [comment]
This is fixed in newer versions of dokku. Please upgrade dokku, the version you are using is years out of date.

**Comment by fa11enangel** [comment]
I've hit that too. You don't need to reinstall a plugin. Update it like this:

```sh
dokku plugin:update letsencrypt
```
