### ISSUE TITLE
Broken as of dokku 0.30.0

### ISSUE THREAD

**Issue by tylercal** [dokku/dokku-letsencrypt#305]
## Description of problem
The dokku letsencrypt plugin is broken on newer versions of dokku. In dokku `0.20`, [proxy functions became deprecated](https://github.com/dokku/dokku/commit/954b2d9d34585afe900259fe1dda425d92b4983f). And in `0.30` they were removed.

Attempting to enable, disable, renew, etc with the letsencrypt plugin gives the following error
`/var/lib/dokku/plugins/enabled/redirect/nginx-pre-reload: line 7: /var/lib/dokku/plugins/available/proxy/functions: No such file or directory`

### How reproducible
Update to dokku 0.30 or later, attempt to enable letsencrypt

## Environment Information
`dokku version 0.30.3`
`letsencrypt 0.20.0`
`proxy 0.30.3`

**Comment by josegonzalez** [comment]
What version of the redirect plugin are you using?

**Comment by josegonzalez** [comment]
I think your version of the redirect plugin is out of date. Do you mind updating all your plugins?

**Comment by tylercal** [comment]
`redirect 0.7.1`

**Comment by tylercal** [comment]
yup, that was it. Now at `redirect 0.9.0` and everything is working fine again 😄 

I don't remember installing that plugin, any suggestion on how to monitor those / keep them up to date when they don't get upgraded with the main dokku?
