### ISSUE TITLE
Cloudflare DNS-01 howto

### ISSUE THREAD

**Issue by tyteen4a03** [dokku/dokku-letsencrypt#307]
Hi, is there a tutorial on how to setup DNS-01 with Cloudflare? I ran these commands:

```
dokku letsencrypt:set --global dns-provider-CLOUDFLARE_EMAIL=myemail@email.com
dokku letsencrypt:set --global dns-provider-CLOUDFLARE_API_KEY=MYKEY
```

But I am still getting:

```
2023/05/26 18:40:08 cloudflare: some credentials information are missing: CLOUDFLARE_EMAIL,CLOUDFLARE_API_KEY or some credentials information are missing: CLOUDFLARE_DNS_API_TOKEN,CLOUDFLARE_ZONE_API_TOKEN
```

**Comment by josegonzalez** [comment]
Can you include *all* of the information we ask for in our [issue template](https://github.com/dokku/.github/blob/master/ISSUE_TEMPLATE.md)? It is helpful for debugging problems. Thanks.

**Comment by josegonzalez** [comment]
Closing as the requested data was not provided. Feel free to comment with the requested information and a way to replicate, and we'll re-open the issue as appropriate.
