### ISSUE TITLE
Update to new template engine sigil

### ISSUE THREAD

**Issue by MorrisJobke** [dokku/dokku-letsencrypt#31]
See https://github.com/dokku/dokku/pull/1892

**Comment by sseemayer** [comment]
Thanks for the heads up :+1:

**Comment by MorrisJobke** [comment]
I just read the code and you don't use a template but simply place the cert files and use the logic of the cert plugin of the dokku core -> not an issue -> closing

**Comment by sseemayer** [comment]
Yes, but we use templating to fill in the temporary reverse proxy to the let's encrypt authenticator here: https://github.com/dokku/dokku-letsencrypt/blob/master/templates/letsencrypt.conf

Re-opening because I want to check if it makes sense to change templating for that.

**Comment by MorrisJobke** [comment]
Ah ... missed that one. I just searched for the ssl_cert_file stuff ;)
