### ISSUE TITLE
Can't Renew Ceritificate, returns Error: manifest for dokku/letsencrypt:0.1.0 not found:

### ISSUE THREAD

**Issue by pglibay** [dokku/dokku-letsencrypt#314]
## Description of problem
Hi there, i'm trying to renew my apps certificates, but it returns the following when running auto-renew:
```
=====> Auto-renewing all apps...
-----> appname.domain.com needs renewal
=====> Let's Encrypt appname.domain.com
-----> Updating letsencrypt docker image...
Error response from daemon: manifest for dokku/letsencrypt:0.1.0 not found: manifest unknown: manifest unknown
```

I then tried pulling the docker image using the default tag **latest** instead of the dokku/letsencrypt:0.1.0 but i'm still getting the same results.

### How reproducible
No response

### Steps to Reproduce
No response

#### Actual Results
No response

#### Expected Results
No response

## Environment Information
No response

**Comment by josegonzalez** [comment]
@pglibay you're running an ancient version of the plugin (and probably dokku) and should upgrade.

The image in question was accidentally deleted (due to some copy-pasta in another repo) so unless someone has a copy somewhere, I can't return it. It hasn't been in use since 2020, so I think its ~fine to say to folks to upgrade :)

**Comment by josegonzalez** [comment]
Note that we don't use that image _at all_ in the latest version of the plugin.

**Comment by UlTriX** [comment]
I also faced the same issue on an old instance I have running Dokku. 

On the schedule to be updated but in the meantime, I temporarily solved the issue by editing the image version on the config file:

located at /var/lib/dokku/plugins/enabled/letsencrypt/config

changing "0.1.0" to "0.1.1"

Then running letsencrypt:auto-renew app 

Hope this helps for a quick workaround.

**Comment by josegonzalez** [comment]
I pushed it but honestly ya'll need to upgrade.
