### ISSUE TITLE
set email for app is not possible

### ISSUE THREAD

**Issue by Zaniyar** [dokku/dokku-letsencrypt#316]
`user@server:~# dokku letsencrypt:set myApp email my.mail@gmail.com`

```
/var/lib/dokku/plugins/available/letsencrypt/command-functions: line 301: fn-in-array: command not found
Invalid key specified, valid keys include: dns-provider, dns-provider-*, email, graceperiod, server, lego-docker-args
```

I uninstalled letsencrypt and reinstalled, but problem stays. 

I can't enable it as well without setting an email, but it won't let me...
```
user@server:~# dokku letsencrypt:enable myApp
=====> Enabling letsencrypt for myApp
/var/lib/dokku/plugins/available/letsencrypt/internal-functions: line 390: fn-plugin-property-get-default: command not found
/var/lib/dokku/plugins/available/letsencrypt/internal-functions: line 383: fn-plugin-property-get-default: command not found
 !     ERROR: Cannot request a certificate without an e-mail address!
 !       please provide your e-mail address using
 !       dokku letsencrypt:set myApp email <e-mail>
```

dokku version 0.19.9

**Comment by josegonzalez** [comment]
You definitely need to upgrade dokku - or use an older version of the letsencrypt plugin - as that function is only available in newer versions of Dokku.

If you need help upgrading Dokku, please check out our [slack/discord](https://dokku.com/docs/getting-started/where-to-get-help/).
