### ISSUE TITLE
Name of environment variables

### ISSUE THREAD

**Issue by sseemayer** [dokku/dokku-letsencrypt#32]
yes = DOKKU_LE_EMAIL
no = LETSENCRYPT_EMAIL

**Comment by sseemayer** [comment]
Whoops, trying out GitPoll without realizing it would make an issue :)

**Comment by fruitl00p** [comment]
@sseemayer I'd go for 'DOKKU_LETSENCRYPT_EMAIL' Its not something that has to be entered alot but will be read a lot... This makes it clear ;)

**Comment by sseemayer** [comment]
I wanted to make a poll out of this but since it doesn't matter too much and there's no point in overcomplicating I'll use `DOKKU_LETSENCRYPT_` as the settings prefix. I guess it doesn't hurt to have this as explicit and non-colliding as possible.
