### ISSUE TITLE
Running on old dokku installation

### ISSUE THREAD

**Issue by unitrix0** [dokku/dokku-letsencrypt#320]
Unfortunately we are running a very old dokku installation here 0.8.0 to be precise on which we need to run your letsencrypt plugin. But if I install the latest version of the plugin we get the error: 

`/var/lib/dokku/plugins/available/letsencrypt/command-functions: line 3: /var/lib/dokku/core-plugins/available/common/property-functions: No such file or directory` 
which I assume is due to incompatibilities with our old dokku version. 

So I tried installing version 0.8.7 of the plugin but when I run the renewal process I get the error: `Error response from daemon: repository dokkupaas/letsencrypt-simp_le not found: does not exist or no pull access` 
which I guess is because it's old... 

Is there any version combination which could work with our old dokku installation?

**Comment by josegonzalez** [comment]
Try patching the plugin to reference dokku instead of dokkupaas.

If that doesn't work, you can sponsor work to make the plugin work for your version of dokku. Here is a doc outlining how that works: https://github.com/dokku/.github/blob/master/SPONSORING.md
