### ISSUE TITLE
Unable to set email address

### ISSUE THREAD

**Issue by cieux1** [dokku/dokku-letsencrypt#322]
Hi, I was trying to renew certificate manually because somehow auto-renewing stopped.  Then an erorr says I need to set email address to enable / auto-renew / revoke the certificate for the app.

$ sudo dokku letsencrypt:enable appname
=====> Enabling letsencrypt for appname
 !     ERROR: Cannot request a certificate without an e-mail address!
 !       please provide your e-mail address using
 !       dokku letsencrypt:set calcal email <e-mail>

But I am getting this error when I tried to set my email address so I can not go further.

$ sudo dokku letsencrypt:set appname email example@example.com
/var/lib/dokku/plugins/available/letsencrypt/command-functions: line 301: fn-in-array: command not found
Invalid key specified, valid keys include: dns-provider, dns-provider-*, email, graceperiod, server, lego-docker-args

Does anyone know how can I fix this?

$ dokku -v
dokku version 0.19.11

**Comment by josegonzalez** [comment]
The version of Dokku you are running is incompatible with the latest version of this plugin. You'll need to upgrade your Dokku installation for this to work.

**Comment by chillbert** [comment]
have the same error - but I was also not able to update dokku 
https://github.com/dokku/dokku/issues/6498
