### ISSUE TITLE
feature: Make it possible to enable letsencrypt by default

### ISSUE THREAD

**Issue by mstahv** [dokku/dokku-letsencrypt#323]
## Description of problem

I'm  deploying a dozen of examples and forgetting to enable letsencrypt for most of them. Would be great if I could for example call `dokku letsencrypt:enable --global` and if after that all new apps would have letsencrypt provided https on by default.

**Comment by josegonzalez** [comment]
I think this I'll need to close it. Ideally we could do it on `post-domains-update`, but there is an issue with order of operations that prevents us from doing so, and as such I had to disable the functionaltiy as shown [here](https://github.com/dokku/dokku-letsencrypt/pull/276).
