### ISSUE TITLE
get_available_port: command not found

### ISSUE THREAD

**Issue by Tashows** [dokku/dokku-letsencrypt#324]
Using dokku 0.32.3 and trying to run `dokku letsencrypt:enable app_name` returns `/var/lib/dokku/plugins/enabled/letsencrypt/subcommands/enable: line 138: get_available_port: command not found`

Did some digging and found out it was deprecated and recently removed, but its use doesn't seem to have been updated in this plugin. Relevant code seems to be here:
https://github.com/dokku/dokku-letsencrypt/blob/09fd749305ecd63947529f7682c318e14063d8b4/internal-functions#L83

In a previous dokku version `get_available_port` was replaced with `plugn trigger ports-get-available`. I would make a PR, but while I can read the code, I am not familiar enough to make educated changes.

EDIT: Updating the plugin fixed the issue. But maybe this old function reference should be replaced regardless? If not, feel free to close this.

**Comment by josegonzalez** [comment]
It only falls back to the old `get_available_port` if need be, otherwise it uses the plugn trigger. As you mentioned, you were using an old version of the plugin, hence the issue. Please ensure you update next time before reporting :)
