### ISSUE TITLE
Read-only File System Error when enabling for an app.

### ISSUE THREAD

**Issue by jbosse** [dokku/dokku-letsencrypt#330]
## Description of problem
I am honestly not sure where in the stack this problem lies, but since this is the only command that is failing this is where I will start.

### How reproducible
It is now happening for all my apps, including apps that have already been configured.

### Steps to Reproduce

1. run `dokku letsencrypt:enable reckless-embermine`

#### Actual Results
```
jbosse@server:~$ dokku letsencrypt:enable reckless-embermine
=====> Enabling letsencrypt for reckless-embermine
-----> Enabling ACME proxy for reckless-embermine...
-----> Setting temporary site
-----> Getting letsencrypt certificate for reckless-embermine via HTTP-01
        - Domain 'reckless-embermine.jobo.dev'
docker: Error response from daemon: error while creating mount source path '/var/lib/dokku/data/letsencrypt/reckless-embermine': mkdir /var/lib/dokku: read-only file system.
-----> Certificate retrieval failed!
-----> Disabling ACME proxy for reckless-embermine...
 !     Failed to setup letsencrypt
 !     Check log output for further information on failure
```
#### Expected Results
Certificate created successfully.

### `dokku report reckless-ember mine` output
[`dokku report reckless-ember mine` GIST](https://gist.github.com/jbosse/abb64c4980c0b9d83186ebc57f7cdd7d)

### How (deb/make) and where (AWS, VirtualBox, physical, etc.) was Dokku installed?:
`wget -NP . https://dokku.com/bootstrap.sh`
`sudo DOKKU_TAG=v0.34.4 bash bootstrap.sh`

### Additional information

- App container inspect output (if applicable) via [`dokku ps:inspect reckless-embermine` GIST](https://gist.github.com/jbosse/c01f0c713b173cb1170c69b210f0b170)
- The nginx configuration (if applicable) via [`dokku nginx:show-config reckless-embermine` GIST](https://gist.github.com/jbosse/d7f987f5b68e300c248562c2fb29bcbb)
- Link to the exact repository being deployed (if possible/applicable): N/A
- Output of failing Dokku commands after running [`dokku trace:on` GIST](https://gist.github.com/jbosse/8e849262cf5e75dae4bfaac02b9c3ea6)

**Comment by jbosse** [comment]
oh ffs. `sudo apt upgrade` resolved the problem.

**Comment by PapePathe** [comment]
Hey I am having the same issue here
