### ISSUE TITLE
Domains

### ISSUE THREAD

**Issue by crisward** [dokku/dokku-letsencrypt#37]
It's not clear from the readme which domains this gets certificates for. If I've added multiple domains to an app before running this, will it get a certificate to cover all the domains. If not, is there a way to specify which domain I want to get a certificate for (I've looked through the source code, and this doesn't look possible).

**Comment by sseemayer** [comment]
Hi Cris,

dokku-letsencrypt will get one certificate for all the domains listed in `dokku urls myapp` at the time of running `dokku letsencrypt myapp`. You can add and remove domains using the `dokku domains` command.

**Comment by crisward** [comment]
That's cool. Thanks for the clarification.
