### ISSUE TITLE
Command dokku letsencrypt:ls not working

### ISSUE THREAD

**Issue by Evlos** [dokku/dokku-letsencrypt#38]
Hi,

It seems command `dokku letsencrypt:ls` returns empty result.

Please have a look, thanks!

```
root@ubuntu:~/nginx/sites-enabled# dokku letsencrypt:auto-renew temp
       temp still has 59d, 22h, 55m, 36s days left before renewal
root@ubuntu:~/nginx/sites-enabled# dokku letsencrypt:ls
-----> App name           Certificate Expiry        Time before expiry        Time before renewal
root@ubuntu:~/nginx/sites-enabled# dokku letsencrypt:ls
-----> App name           Certificate Expiry        Time before expiry        Time before renewal
```

**Comment by sseemayer** [comment]
Hi Evlos,

This looks like the [check whether the certificate for temp was installed by letsencrypt fails](https://github.com/dokku/dokku-letsencrypt/blob/master/functions#L142-L161). You have to successfully run `dokku letsencrypt temp` at least once before the `letsencrypt:ls` and `letsencrypt:auto-renew` commands will work. Are you sure that the certificate for `temp` was originally installed using the `dokku letsencrypt temp` command?

To debug this, please let me know the following:

- The output of `dokku certs:info temp`
- The output of `ls -l ~dokku/temp/tls/server.crt`
- The output of `ls -l ~dokku/temp/letsencrypt/certs/current`
- In a gist or pastebin, the output of `dokku trace on; dokku letsencrypt:ls; dokku trace off`

Thanks!

**Comment by pmclanahan** [comment]
I saw this when I upgraded from `0.4.14` to `0.5.2`. Lots of odd errors with the letsencrypt plugin actually, so I downgraded dokku and things are okay again. Haven't had time to investigate or file issues, but this may be the issue here. Did you recently upgrade dokku @Evlos?

**Comment by Evlos** [comment]
@sseemayer 

Hi sseemayer,

I am sure `temp` was originally installed through command `dokku letsencrypt temp`, since as you can see from the log I posted before, command `dokku letsencrypt:auto-renew temp` works fine.

* The output of dokku certs:info temp
```
-----> Fetching SSL Endpoint info for temp...
-----> Certificate details:
=====> Common Name(s):
=====>    temp.eternalelf.com
=====>    temp.eternalelf.com
=====> Expires At: Jun 27 04:05:00 2016 GMT
=====> Issuer: C=US, O=Lets Encrypt, CN=Lets Encrypt Authority X3
=====> Starts At: Mar 29 04:05:00 2016 GMT
=====> Subject: CN=temp.eternalelf.com
=====> SSL certificate is self signed.
```
* The output of ls -l ~dokku/temp/tls/server.crt
```
lrwxrwxrwx 1 dokku dokku 56 Mar 29 01:05 /home/dokku/temp/tls/server.crt -> /home/dokku/temp/letsencrypt/certs/current/fullchain.pem
```
* The output of ls -l ~dokku/temp/letsencrypt/certs/current
```
lrwxrwxrwx 1 dokku dokku 75 Mar 29 01:05 /home/dokku/temp/letsencrypt/certs/current -> /home/dokku/temp/letsencrypt/certs/5d8917ed208f42ec5106df42cbd49ac7838a48ef
```
* In a gist or pastebin, the output of dokku trace on; dokku letsencrypt:ls; dokku trace off
[https://gist.github.com/Evlos/bec38436efacd30e5f4442a741f9e7fe](https://gist.github.com/Evlos/bec38436efacd30e5f4442a741f9e7fe)

@pmclanahan 

Yes, I have recently upgraded dokku to 0.5.2.

As I know, mostly commands of `dokku-letsencrypt` work fine except `dokku letsencrypt:ls`, since I have successfully applied SSL through command `dokku letsencrypt`, but I didn't use it long enough to test if auto-renew works or not :).

BTW, you guys are doing a great job. I didn't see any alternative on any SaaS platforms so far.

**Comment by sseemayer** [comment]
Thanks for the detailed information @pmclanahan and @Evlos !

I haven't updated to 0.5.2 myself yet so I'll be doing that and will try to fix things up. Things are a bit busy at the moment so it might take a few days for me to find the time. Thanks for your patience!

**Comment by sseemayer** [comment]
Hi all, thanks to @tobru this is fixed with #40 . I'll go through all functions on dokku 0.5.3 and will check if there are any other problems.

**Comment by sseemayer** [comment]
Any news on if this is working @Evlos @pmclanahan ?

**Comment by pmclanahan** [comment]
@sseemayer sorry for the delay in reporting back. it's been a busy time for me as well and I've not upgraded to Dokku 0.5.x again. I downgraded to the latest 0.4.x to get things working and am having to stick with that for the moment. I'll get back to you when I'm able to run the experiment again. Thanks for all of your work on this!!

**Comment by Evlos** [comment]
@sseemayer It works on 0.5.2! :+1:
