### ISSUE TITLE
Documentation: upgrade compatibilities

### ISSUE THREAD

**Issue by fruitl00p** [dokku/dokku-letsencrypt#45]
In response of all the great work you're doing for the new dokku 0.5 refactoring... 

Just a quick question regarding the new `dokku 0.5+` / `dokku-letsencrypt` compatibility matrix. Currently its not mentioned anywhere (neither your plugin nor `dokku` itself) on how to handle / check `dokku` compatibility with plugins... Without doing the ol' fingers-crossed-and-lets-see-what-it-does-in-production: `dokku plugin:update` Are you aware of any compatibility issues for `dokku-letsencrypt` with older `dokku` versions?

If not, it might be worthwhile to mention this in the `upgrading`-section of the [readme](/dokku/dokku-letsencrypt/blob/master/README.md#upgrading-from-previous-versions)

Thanks!

**Comment by haywirez** [comment]
I've run into multiple issues since blindly upgrading dokku + dokku-letsencrypt this morning, my advice would be to wait for a while until things are settled...

**Comment by sseemayer** [comment]
The API changes with the 0.5 update hit me at a busy time so I'm currently flailing to get everything working properly again. For some people 4.x and 5.x is working again now but I agree that an upgrade still might be risky if you're not willing to do some troubleshooting.

Through #33 there might be some backwards-compatibility breaking changes in the future but I'll definitely note any compatibility breaks that I'm aware of in the upgrade instructions / that issue and before implementing #33 the focus will be on bugfixing for a while.

**Comment by fruitl00p** [comment]
Whole heartily agree on all counts. Just wanted to give a heads up to unsuspecting other users as well ;)

**Comment by sseemayer** [comment]
But where will I take my guinea pigs from :stuck_out_tongue_winking_eye: ? 5338510 adds a warning message and hopefully some people will be brave enough to try things and report their experiences in #47 .
