### ISSUE TITLE
If the certificate is revoked, $APP_ROOT/letsencrypt needs to be removed manually

### ISSUE THREAD

**Issue by haywirez** [dokku/dokku-letsencrypt#46]
As requested in #19 - getting the following errors after having manually revoked my certificates:

```
6-04-11 09:04:12,559:INFO:requests.packages.urllib3.connectionpool:758: Starting new HTTPS connection (1): acme-v01.api.letsencrypt.org
2016-04-11 09:04:13,007:INFO:requests.packages.urllib3.connectionpool:758: Starting new HTTPS connection (1): acme-v01.api.letsencrypt.org
2016-04-11 09:04:13,339:INFO:requests.packages.urllib3.connectionpool:758: Starting new HTTPS connection (1): acme-v01.api.letsencrypt.org
2016-04-11 09:04:13,607:INFO:requests.packages.urllib3.connectionpool:758: Starting new HTTPS connection (1): acme-v01.api.letsencrypt.org
2016-04-11 09:04:13,957:INFO:requests.packages.urllib3.connectionpool:207: Starting new HTTP connection (1): my.app.url
2016-04-11 09:04:13,966:WARNING:__main__:1292: my.app.url was not successfully self-verified. CA is likely to fail as well!
2016-04-11 09:04:13,986:INFO:requests.packages.urllib3.connectionpool:758: Starting new HTTPS connection (1): acme-v01.api.letsencrypt.org
2016-04-11 09:04:14,246:INFO:__main__:1302: Generating new certificate private key
2016-04-11 09:04:16,148:INFO:requests.packages.urllib3.connectionpool:758: Starting new HTTPS connection (1): acme-v01.api.letsencrypt.org
2016-04-11 09:04:16,391:ERROR:__main__:1260: CA marked some of the authorizations as invalid, which likely means it could not access http://example.com/.well-known/acme-challenge/X. Did you set correct path in -d example.com:path or --default_root? Is there a warning log entry about unsuccessful self-verification? Are all your domains accessible from the internet? Failing authorizations: https://acme-v01.api.letsencrypt.org/acme/authz/g6pR4I21X1sUOpBnIAmZotZdGpVTP5882BX-v_L3q7w
Challenge validation has failed, see error log.
```
Full dokku trace (URLs & email changed):
https://gist.github.com/haywirez/726f8f916cfd33beea42191fa8968aca

**Comment by sseemayer** [comment]
Thanks for the trace! Can you also tell me the output (anonymizing URLs and e-mails is fine) of `dokku certs:info myapp` and `ls -l ~/dokku/myapp/letsencrypt/certs/ ~dokku/myapp/letsencrypt/certs/current` ?

**Comment by haywirez** [comment]
Sure:

`dokku certs:info myapp`
https://gist.github.com/haywirez/aecfc204c1e051d9323b8b2e9f0d1a27

`ls -l ~/dokku/myapp/letsencrypt/certs/ ~dokku/myapp/letsencrypt/certs/current`
```
lrwxrwxrwx  1 dokku dokku   87 Apr 11 04:46 /home/dokku/my.app.url/letsencrypt/certs/current -> /home/dokku/my.app.url/letsencrypt/certs/00b79f75e7bc83fdf46ac42d7a18a85cbbc299d7

/home/dokku/my.app.url/letsencrypt/certs:
total 8
drwxr-xr-x 2 dokku dokku 4096 Apr 11 04:48 00b79f75e7bc83fdf46ac42d7a18a85cbbc299d7
lrwxrwxrwx 1 dokku dokku   87 Apr 11 04:46 current -> /home/dokku/my.app.url/letsencrypt/certs/00b79f75e7bc83fdf46ac42d7a18a85cbbc299d7
```

**Comment by sseemayer** [comment]
OK my shell-fu was weak apparently - I wanted to see if the directory that `current` points to actually exists and has the keys in it :)

**Comment by haywirez** [comment]
I forgot to mention I'm on dokku v0.5.4, everything got messed up after upgrading this morning :smile:

**Comment by haywirez** [comment]
This is my nginx error log:

```
2016/04/11 06:39:34 [error] 17030#17030: *107 open() "/usr/share/nginx/html/.well-known/acme-challenge/gTGNOeOWNdWJzQXQB-VxyEAju1Elt_VFuMYchg5pS3k" failed (2: No such file or directory), client: 172.17.0.6, server: localhost, request: "GET /.well-known/acme-challenge/gTGNOeOWNdWJzQXQB-VxyEAju1Elt_VFuMYchg5pS3k HTTP/1.1", host: "my.app.url"
2016/04/11 06:39:34 [error] 17030#17030: *108 open() "/usr/share/nginx/html/.well-known/acme-challenge/gTGNOeOWNdWJzQXQB-VxyEAju1Elt_VFuMYchg5pS3k" failed (2: No such file or directory), client: 66.133.109.36, server: localhost, request: "GET /.well-known/acme-challenge/gTGNOeOWNdWJzQXQB-VxyEAju1Elt_VFuMYchg5pS3k HTTP/1.1", host: "my.app.url"
```

**Comment by haywirez** [comment]
Maybe worth mentioning that `$APP_ROOT/tls` doesn't seem to exist

**Comment by sseemayer** [comment]
Looks like the [temporary reverse proxy for ACME challenges](https://github.com/dokku/dokku-letsencrypt/blob/master/templates/letsencrypt.conf) is not working correctly which would explain why the validation fails. 

There was a bug in 0.5.3 that gave problems with including files from the nginx.conf.d folder. Can you show the content of `/home/dokku/my.app.url/nginx.conf`? What happens if you run `dokku nginx:build-config myapp` and then `dokku letsencrypt myapp`?

Since the let's encrypt validation currently fails, you're not getting a valid certificate that can be included in `$APP_ROOT/tls`.

**Comment by haywirez** [comment]
The app's nginx.conf:

```
server {
  listen      [::]:8641;
  listen      8641;
  server_name my.app.url; 
  access_log  /var/log/nginx/my.app.url-access.log;
  error_log   /var/log/nginx/my.app.url-error.log;

  location    / {

    gzip on;
    gzip_min_length  1100;
    gzip_buffers  4 32k;
    gzip_types    text/css text/javascript text/xml text/plain text/x-component application/javascript application/x-javascript application/json application/xml  application/rss+xml font/truetype application/x-font-ttf font/opentype application/vnd.ms-fontobject image/svg+xml;
    gzip_vary on;
    gzip_comp_level  6;

    proxy_pass  http://my.app.url-8641;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_set_header Host $http_host;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Forwarded-For $remote_addr;
    proxy_set_header X-Forwarded-Port $server_port;
    proxy_set_header X-Request-Start $msec;
  }
  include /home/dokku/my.app.url/nginx.conf.d/*.conf;
}

upstream my.app.url-8641 {
  server 172.17.0.3:8641;
}

server {
  listen      [::]:8641;
  listen      8641;
  server_name my.app.url; 
  access_log  /var/log/nginx/my.app.url-access.log;
  error_log   /var/log/nginx/my.app.url-error.log;

  location    / {

    gzip on;
    gzip_min_length  1100;
    gzip_buffers  4 32k;
    gzip_types    text/css text/javascript text/xml text/plain text/x-component application/javascript application/x-javascript application/json application/xml  application/rss+xml font/truetype application/x-font-ttf font/opentype application/vnd.ms-fontobject image/svg+xml;
    gzip_vary on;
    gzip_comp_level  6;

    proxy_pass  http://my.app.url-8641;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_set_header Host $http_host;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Forwarded-For $remote_addr;
    proxy_set_header X-Forwarded-Port $server_port;
    proxy_set_header X-Request-Start $msec;
  }
  include /home/dokku/my.app.url/nginx.conf.d/*.conf;
}

upstream my.app.url-8641 {
  server 172.17.0.3:8641;
}
```

After running commands, nothing changes, still getting the same `ERROR:__main__:1260: CA marked some of the authorizations as invalid, which likely means it could not access http://example.com/.well-known/acme-challenge/X. Did you set correct path in -d example.com:path or --default_root? Is there a warning log entry about unsuccessful self-verification? Are all your domains accessible from the internet? Failing authorizations: https://acme-v01.api.letsen `.

Thank you for these quick hints, highly appreciated!

**Comment by sseemayer** [comment]
It looks like nginx is listening on port 8641 instead of the expected 80 / 443. Is that intentional? In any case, that would be the reason why the ACME validation fails.

**Comment by haywirez** [comment]
Yes, the docker image of the app itself is exposing 8641. Dokku's nginx configs should proxy this port automatically, maybe something has changed regarding this in the routing structures?

**Comment by sseemayer** [comment]
To clarify: Do you want your app's **public-facing** IPs to be myapp.com:8641, or myapp.com:80 and myapp.com:443 ?

It looks like some configuration setting currently makes your app listen on port 8641 publicly which is why the letsencrypt validation connecting on port 80 (where your app isn't listening) fails.

**Comment by haywirez** [comment]
Public facing should be 443/80

**Comment by sseemayer** [comment]
Then there is a general (configuration?) problem with your app that causes all of it to be reachable at the wrong port. What does `dokku config myapp` say?

**Comment by haywirez** [comment]
These are the relavant `dokku confi myapp` fields:
```
DOKKU_APP_RESTORE:       1
DOKKU_APP_TYPE:          dockerfile
DOKKU_DOCKERFILE_PORT:   8641
DOKKU_DOCKERFILE_PORTS:  8641
DOKKU_NGINX_PORT:        80
DOKKU_NGINX_SSL_PORT:    443
```

**Comment by haywirez** [comment]
Perhaps related to this?
https://github.com/dokku/dokku/issues/2028

**Comment by sseemayer** [comment]
Ah, a dockerfile deploy - there might be a problem with these currently. Does removing the `DOKKU_DOCKERFILE_*` settings change the port in the nginx config file? If so, you could re-try running the validation.

**Comment by haywirez** [comment]
It did validate the certs now! :fireworks: App still doesn't fully work but I think this was the main culprit,I'll keep playing around :sweat_smile:

**Comment by sseemayer** [comment]
I'm glad that helped - and thanks for pointing out dokku issue 2028 which helps me out too!

**Comment by haywirez** [comment]
Confirming that it was due to the port config changes mentioned in dokku/dokku#2028, if anyone has a similar issue try removing the `EXPOSE` lines in your Dockerfile. The apps/nginx.conf *inside* the container still needs to listen to the default port 5000.
