### ISSUE TITLE
What configurations are currently working?

### ISSUE THREAD

**Issue by sseemayer** [dokku/dokku-letsencrypt#47]
After the dokku 0.5 upgrade debacle, It would be helpful to know what is currently working from a broad user base both for troubleshooting and for having a list of known-good configurations to make upgrading less scary/surprising. Please let me know the following:

- Your current dokku version and dokku-letsencrypt commit hash (go to `/var/lib/dokku/plugins/available/letsencrypt` and run `git rev-parse HEAD`)
- Your operating system + version (`cat /etc/isue`)
- What are you deploying?
- Is `letsencrypt myapp` working?
- Is `letsencrypt:ls` working?
- Is `letsencrypt:auto-renew` working?

**Comment by sseemayer** [comment]
I'll start:

- dokku 0.5.4 with dokku-letsencrypt 15d4a7fb047f00ec302279f29e1f0e3fbc686353
- Ubuntu 14.04 LTS
- Deploying both `Dockerfile` and herokuish apps.
- `letsencrypt myapp` working
- `letsencrypt:ls` working
- `letsencrypt:auto-renew` working

**Comment by benjohnson** [comment]
Dokku: 0.5.4
Dokku-Letsecrypt: 15d4a7f
Ubuntu 14.04.4 LTS
Just Herokuish apps
`letsencrypt myapp` working
`letsencrypt:ls` working
`letsencrypt:autorenew` working

**Comment by drale2k** [comment]
* Dokku v0.5.5
* Dokku-Letsencrypt: `35750c3f6a2ad1673ba0e0bbb043555cfd322d46`
* Ubuntu 14.04.4 LTS
* Herokuish (rails)
* `letsencrypt myapp` working
* `letsencrypt:ls` **not** working (shows zero apps)
* `letsencrypt:autorenew` working
