### ISSUE TITLE
OCSP Stapling

### ISSUE THREAD

**Issue by enjikaka** [dokku/dokku-letsencrypt#52]
Add

```
ssl_trusted_certificate {{ .DOKKU_ROOT }}/{{ .APP }}/letsencrypt/certs/current/fullchain.pem;
```

in nginx config for apps with Lets Encrypt enabled.

This plugin should do this since it's not possible to handle effectively yourself because:
- You can't add stuff to you repo that end up in `<dokku_app>/nginx.conf.d/`
- `<dokku_app>/nginx.conf` cannot be extended. And creating a nginx.cong.sigil thats identical to the default with the only difference being the staplin', ain't a good solution.

**Comment by sseemayer** [comment]
This is an issue for the main dokku project since dokku-letsencrypt does not handle configuring the nginx server. I see you have a discussion already going on in dokku/dokku#2138 so I'm closing the one here.

**Comment by sseemayer** [comment]
Hang on, I think I found a way to do this without changing dokku - If I understand the chain of nginx.config.sigil imports correctly, we have:

https://github.com/dokku/dokku/blob/master/plugins/nginx-vhosts/templates/nginx.conf.sigil
```
{{ if .RAW_TCP_PORTS }}
{{ include "tcp.server.config" . }}
{{ else if .SSL_INUSE }}
{{ include "nossl.server.config" . }}
{{ include "ssl.server.config" . }}
{{ include "upstream.config" . }}
{{ else }}
{{ include "nossl.server.config" . }}
{{ include "upstream.config" . }}
{{ end }}
```

https://github.com/dokku/dokku/blob/master/plugins/nginx-vhosts/templates/ssl.server.config
```
server {
  listen      [::]:{{ .NGINX_SSL_PORT }} ssl spdy;
  listen      {{ .NGINX_SSL_PORT }} ssl spdy;
  {{ if .SSL_SERVER_NAME }}server_name {{ .SSL_SERVER_NAME }}; {{ end }}
  {{ if .NOSSL_SERVER_NAME }}server_name {{ .NOSSL_SERVER_NAME }}; {{ end }}
{{ include "log.config" . }}
  ssl_certificate     {{ .APP_SSL_PATH }}/server.crt;
  ssl_certificate_key {{ .APP_SSL_PATH }}/server.key;

  keepalive_timeout   70;
  add_header          Alternate-Protocol  {{ .NGINX_SSL_PORT }}:npn-spdy/2;
{{ include "location.config" . }}
}
```

https://github.com/dokku/dokku/blob/master/plugins/nginx-vhosts/templates/location.config
```
  location    / {

    gzip on;
    gzip_min_length  1100;
    gzip_buffers  4 32k;
    gzip_types    text/css text/javascript text/xml text/plain text/x-component application/javascript application/x-javascript application/json application/xml  application/rss+xml font/truetype application/x-font-ttf font/opentype application/vnd.ms-fontobject image/svg+xml;
    gzip_vary on;
    gzip_comp_level  6;

    proxy_pass  http://{{ .APP }};
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_set_header Host $http_host;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Forwarded-For $remote_addr;
    proxy_set_header X-Forwarded-Port $server_port;
    proxy_set_header X-Request-Start $msec;
  }
  include {{ .DOKKU_ROOT }}/{{ .APP }}/nginx.conf.d/*.conf;
```

**Note the `include` in the last line!**

In an example SSL app, this should expand to:

```
server {
  listen      [::]:80;
  listen      80;
  server_name test.semicolonsoftware.de; 
  access_log  /var/log/nginx/test-access.log;
  error_log   /var/log/nginx/test-error.log;

  return 301 https://$host:443$request_uri;

}

server {
  listen      [::]:443 ssl spdy;
  listen      443 ssl spdy;
  server_name test.semicolonsoftware.de; 
  server_name test.semicolonsoftware.de; 
  access_log  /var/log/nginx/test-access.log;
  error_log   /var/log/nginx/test-error.log;

  ssl_certificate     /home/dokku/test/tls/server.crt;
  ssl_certificate_key /home/dokku/test/tls/server.key;

  keepalive_timeout   70;
  add_header          Alternate-Protocol  443:npn-spdy/2;
  location    / {

    gzip on;
    gzip_min_length  1100;
    gzip_buffers  4 32k;
    gzip_types    text/css text/javascript text/xml text/plain text/x-component application/javascript application/x-javascript application/json application/xml  application/rss+xml font/truetype application/x-font-ttf font/opentype application/vnd.ms-fontobject image/svg+xml;
    gzip_vary on;
    gzip_comp_level  6;

    proxy_pass  http://test;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_set_header Host $http_host;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Forwarded-For $remote_addr;
    proxy_set_header X-Forwarded-Port $server_port;
    proxy_set_header X-Request-Start $msec;
  }
  include /home/dokku/test/nginx.conf.d/*.conf;

}


upstream test {
  server 172.17.0.9:5000;
}
```

Now the important part: note that the `include` statement is on the same hierarchy level as the other `ssl_certificate` statements. If you want to enable OCSP stapling, you can do so by simply adding a new file into the `nginx.conf.d` directory of the app containing nothing but the `ssl_trusted_certificate` line in the original issue.

Let me know if this works for you.

**Comment by enjikaka** [comment]
Adding a file manually into nginx.conf.d is how I solved it for my sites atm. Is it possible for this plugin to put files there too?

**Comment by sseemayer** [comment]
Thanks for the heads-up! 

Yes, it would be possible for the plugin to place the config there but I still want to discuss possible side effects that could arise from other plugins / changing certs using the `dokku certs:*` family of commands. 

Suggestions and / or code welcome! :+1:

**Comment by josegonzalez** [comment]
Note: as of 0.6.x, we do not recommend calling the dokku binary directly. If there are functions that need to be exposed/sourced, we should open issues for those directly.

**Comment by fruitl00p** [comment]
@josegonzalez In order to 'close' this issue: would you like me to add something to the [docs concerning OCSP](http://dokku.viewdocs.io/dokku/configuration/ssl/) ?

Currently the following conf could be added to the `nginx.conf.d`:
```
ssl_stapling on;
ssl_stapling_verify on;
resolver 8.8.8.8 8.8.4.4 216.146.35.35 216.146.36.36 valid=300s;
resolver_timeout 5s;
```
This uses the [Google DNS](https://developers.google.com/speed/public-dns/) and the [Dyn Internet Guide DNS](https://dyn.com/labs/dyn-internet-guide/)

I'll also include links to the [Mozilla TLS guide](https://mozilla.github.io/server-side-tls/ssl-config-generator/) with a 'current' best practice example... ? (which currently is additionally setting the following:
```
    ssl_session_tickets off;
    ssl_protocols TLSv1.2;
    ssl_ciphers 'ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256';

    # HSTS (ngx_http_headers_module is required) (15768000 seconds = 6 months)
    add_header Strict-Transport-Security max-age=15768000;
```
Just as a reference ofcourse ;)

Should i make the PR (and reference this issue from there?)

**Comment by josegonzalez** [comment]
Related is https://github.com/dokku/dokku/pull/2678. I wonder if we should just make ssl stapling default? Anyone have any reason why that would be a bad idea?

**Comment by fruitl00p** [comment]
As far as i know stapling only lowers the SSL connection times due to the extra data that can be fetched from the server directly... AFAIK there are no downsides to stapling ...

**Comment by josegonzalez** [comment]
I'm closing this issue. If we want to make OCSP stapling the default, then it should be done upstream in Dokku, as that is where we handle the nginx configuration. If anyone want to open an issue for that specifically, please do so.
