### ISSUE TITLE
Stopped working

### ISSUE THREAD

**Issue by Alexwijn** [dokku/dokku-letsencrypt#53]
Hello,

Today I tried to update one of my apps but it stopped at "Enabling ACME". I also tried updating the plugin and removing the TLS folder but without success. 

Here is the log:
=====> Let's Encrypt youtrack...
-----> Updating letsencrypt docker image...
latest: Pulling from dokkupaas/letsencrypt-simp_le
420890c9e918: Already exists
e4a2ae244258: Pull complete
5c6ac6d1c950: Pull complete
Digest: sha256:18a19b34beceba79dd5be458abe7e132fc7486da1da19cc4d0395ad4578031ef
Status: Downloaded newer image for dokkupaas/letsencrypt-simp_le:latest
       done
-----> Enabling ACME proxy for youtrack...

**Comment by Alexwijn** [comment]
Never mind, few minutes later with the same command it works. It's still weird, no errors what so ever.

**Comment by sseemayer** [comment]
That's strange - the log you posted is the beginning of how a letsencrypt run should look like but it's just missing the bottom part indicating that the script was waiting for something (reloading nginx to complete?) Anyways, let me know if it happens again!

**Comment by Alexwijn** [comment]
It was not waiting for anything, the script just stopped without any error at that point. But I'll post again if it happens again, thanks.
