### ISSUE TITLE
Cert generation fails for apps with multiple domains

### ISSUE THREAD

**Issue by mattfloat** [dokku/dokku-letsencrypt#56]
When requesting certs for apps with more than one vhost, simp_le fails.

```
-----> Enabling ACME proxy for my-app...
-----> Getting letsencrypt certificate for my-app...
        - Domain 'sub1.myapp.tld
sub2.myapp.tld'
darkhttpd/1.11, copyright (c) 2003-2015 Emil Mikulic.
listening on: http://0.0.0.0:80/
simp_le.py: error: unrecognized arguments: sub2.myapp.tld
-----> Certificate retrieval failed!
```

A dokku trace confirms that it's due to a malformed call to `simp_le.py`: dokku-letsencrypt parses the domains as a single string with newlines, hence fails to split them into separate "-d" arguments.

**Comment by sseemayer** [comment]
Thanks for the bug report and sorrt for the trouble! I introduced this bug in the refactoring yesterday. Can you update and tell me if 87f3a2d fixed things for you?

**Comment by mattfloat** [comment]
Amazing response time, thanks!
Tested, worked.

**Comment by sseemayer** [comment]
You're welcome! Glad that fixed things :+1:
