### ISSUE TITLE
letsencrypt not updating nginx config

### ISSUE THREAD

**Issue by terrarum** [dokku/dokku-letsencrypt#58]
I have just updated dokku from 0.4 to 0.5.6 and updated the letsencrypt plugin. When I run letsencrypt on a new site I have pushed to my dokku box, it claims to finish successfully, but it cannot be accessed via https, I just get 502 Bad Gateway nginx. 

I have looked at the nginx.conf file for the new site, and it has nothing in it regarding ssl certs. The other sites that I had already been running are working fine over SSL, and letsencrypt auto-renew worked fine for them (one of the sites was about to expire).

Here is the output from running dokku letsencrypt:

```
=====> Let's Encrypt www.example.com
-----> Updating letsencrypt docker image...
latest: Pulling from dokkupaas/letsencrypt-simp_le

420890c9e918: Already exists
e4a2ae244258: Already exists
5c6ac6d1c950: Already exists
Digest: sha256:18a19b34beceba79dd5be458abe7e132fc7486da1da19cc4d0395ad4578031ef
Status: Image is up to date for dokkupaas/letsencrypt-simp_le:latest
       done updating
-----> Enabling ACME proxy for www.example.com...
-----> Getting letsencrypt certificate for www.example.com...
        - Domain 'www.example.com'
darkhttpd/1.11, copyright (c) 2003-2015 Emil Mikulic.
listening on: http://0.0.0.0:80/
2016-05-15 19:22:37,824:INFO:requests.packages.urllib3.connectionpool:758: Starting new HTTPS connection (1): acme-v01.api.letsencrypt.org
2016-05-15 19:22:38,063:INFO:requests.packages.urllib3.connectionpool:758: Starting new HTTPS connection (1): acme-v01.api.letsencrypt.org
2016-05-15 19:22:38,305:INFO:requests.packages.urllib3.connectionpool:758: Starting new HTTPS connection (1): acme-v01.api.letsencrypt.org
2016-05-15 19:22:38,564:INFO:requests.packages.urllib3.connectionpool:758: Starting new HTTPS connection (1): acme-v01.api.letsencrypt.org
2016-05-15 19:22:38,924:INFO:requests.packages.urllib3.connectionpool:207: Starting new HTTP connection (1): www.example.com
2016-05-15 19:22:38,975:INFO:__main__:1305: www.example.com was successfully self-verified
2016-05-15 19:22:38,992:INFO:requests.packages.urllib3.connectionpool:758: Starting new HTTPS connection (1): acme-v01.api.letsencrypt.org
2016-05-15 19:22:39,251:INFO:__main__:1313: Generating new certificate private key
2016-05-15 19:22:40,083:INFO:requests.packages.urllib3.connectionpool:758: Starting new HTTPS connection (1): acme-v01.api.letsencrypt.org
2016-05-15 19:22:40,345:INFO:requests.packages.urllib3.connectionpool:758: Starting new HTTPS connection (1): acme-v01.api.letsencrypt.org
2016-05-15 19:22:40,652:INFO:requests.packages.urllib3.connectionpool:758: Starting new HTTPS connection (1): acme-v01.api.letsencrypt.org
2016-05-15 19:22:40,911:INFO:__main__:391: Saving fullchain.pem
2016-05-15 19:22:40,912:INFO:__main__:391: Saving chain.pem
2016-05-15 19:22:40,913:INFO:__main__:391: Saving cert.pem
2016-05-15 19:22:40,913:INFO:__main__:391: Saving key.pem
-----> Certificate retrieved successfully.
-----> Symlinking let's encrypt certificates
-----> Configuring www.example.com...(using built-in template)
-----> Creating https nginx.conf
-----> Running nginx-pre-reload
       Reloading nginx
-----> Disabling ACME proxy for www.example.com...
       done
```

I gather from reading other issues here that there have been some problems recently with changes to dokku, but I haven't been able to find anything that would help me solve this problem. Is this a bug, or am I doing something wrong?

Edit: running `dokku domains appname` returns `www.example.com`, running `dokku urls appname` returns `https://www.example.com`.

**Comment by sseemayer** [comment]
That indeed looks like certificate validation went through successfully and something else went wrong with the proxying of the app.

Can you please let me know the following:

- Your dokku-letsencrypt version (go to /var/lib/dokku/plugins/available/letsencrypt and run git rev-parse HEAD)
- The output of `dokku urls yourapp`
- The output of `dokku certs:info yourapp`
- The content of `/home/dokku/yourapp/nginx.conf`
- If you curl the upstream URL for your app as defined in the app `nginx.conf` file's `upstream` section at the end of the config file, do you reach the app?

**Comment by terrarum** [comment]
Cool. I'll be able to get all that when I'm home, so about ten hours from now.

**Comment by terrarum** [comment]
dokku-letsencrypt version

`b56450f590d1c7f6292ba9bf74f8937543cc6d79`

dokku urls

`https://www.helm108.com:80`

dokku certs:info

```
-----> Fetching SSL Endpoint info for www.helm108.com...
-----> Certificate details:
=====> Common Name(s): 
=====>    www.helm108.com
=====>    www.helm108.com
=====> Expires At: Aug 13 18:23:00 2016 GMT
=====> Issuer: C=US, O=Lets Encrypt, CN=Lets Encrypt Authority X3
=====> Starts At: May 15 18:23:00 2016 GMT
=====> Subject: CN=www.helm108.com
=====> SSL certificate is self signed.
```

nginx.conf

```
server {
  listen      [::]:80;
  listen      80;
  server_name www.helm108.com; 
  access_log  /var/log/nginx/www.helm108.com-access.log;
  error_log   /var/log/nginx/www.helm108.com-error.log;

  location    / {

    gzip on;
    gzip_min_length  1100;
    gzip_buffers  4 32k;
    gzip_types    text/css text/javascript text/xml text/plain text/x-component application/javascript application/x-javascript application/json application/xml  application/rss+xml font/truetype application/x-font-ttf font/opentype application/vnd.ms-fontobject image/svg+xml;
    gzip_vary on;
    gzip_comp_level  6;

    proxy_pass  http://www.helm108.com-80;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_set_header Host $http_host;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Forwarded-For $remote_addr;
    proxy_set_header X-Forwarded-Port $server_port;
    proxy_set_header X-Request-Start $msec;
  }
  include /home/dokku/www.helm108.com/nginx.conf.d/*.conf;
}

upstream www.helm108.com-80 {
  server 172.17.0.4:80;
}
```

docker inspect

`"IPAddress": "172.17.0.4"`

curl upstream from dokku host

If I curl `www.helm108.com-80` it can't find the host, but `www.helm108.com` works fine.

**Comment by sseemayer** [comment]
Could it be that this is a Dockerfile deployment? If so, be aware that the way Dockerfile apps work [changed starting from dokku 0.5](http://dokku.viewdocs.io/dokku/deployment/dockerfiles/#exposed-ports) in that that the app will be hardwired to listen on the port in the EXPOSE statement which causes problems with ACME validation. Since you seem to have an `EXPOSE 80` statement in your Dockerfile, your app will be listening on port 80 for SSL connections instead of the correct port 443.

You have two options (see also dokku/dokku#2028):

1. Remove all `EXPOSE` statements from your Dockerfile and 
    1. make your app listen on port 3000 or 
    2. even better, honor the `$PORT` environment variable

2. Create a custom nginx.conf.sigil template.

After you re-deploy, the port 80 should be gone from `dokku urls yourapp` and then validation should work. If not, be sure to remove any leftover `DOKKU_DOCKERFILE_PORTS` entries from `dokku config yourapp`.

**Comment by terrarum** [comment]
That was it! I destroyed the dokku app, removed the `EXPOSE` statement from the Dockerfile and redeployed it. It is now working over https.

**Comment by knksmith57** [comment]
Heads up that you'll want to listen on port `5000`, not `3000`. Other than that, this thread was perfect!

http://dokku.viewdocs.io/dokku/deployment/dockerfiles/#exposed-ports

**Comment by terrarum** [comment]
My express server is set to `app.set('port', (process.env.PORT || 5000));` and everything is working fine, so that covers the honouring of the PORT variable as well as listening to `5000`.

**Comment by sseemayer** [comment]
Whoops, sorry about the wrong port number and thanks a lot @knksmith57 for correcting me - I guess that's what happens if I recall magic numbers from memory instead of looking into the documentation :see_no_evil: 

I'm glad that things are working now - and using `process.env.PORT || 5000` is even doubly correct :grinning:
