### ISSUE TITLE
Enabling letsencrypt certificate does nothing

### ISSUE THREAD

**Issue by hellojere** [dokku/dokku-letsencrypt#60]
I've successfully used this great plugin on few servers running dokku, but now one simply does nothing when running the following: 

    dokku letsencrypt <myapp>

It doesn't give any error messages whatsoever. Any suggestions what could be causing this?

**Comment by sseemayer** [comment]
That's strange - is there no output whatsoever? Can you please also provide more detail on:

- Your distribution and version
- Your dokku version
- Your dokku-letsencrypt version (go to `/var/lib/dokku/plugins/available/letsencrypt` and run `git rev-parse HEAD`)

**Comment by hellojere** [comment]
Sure. And no output whatsoever indeed. All the other dokku commands for dokku itself and other plugins seem to be working normally. 

Distribution and version: 

    DISTRIB_ID=Ubuntu
    DISTRIB_RELEASE=14.04
    DISTRIB_CODENAME=trusty
    DISTRIB_DESCRIPTION="Ubuntu 14.04.4 LTS"
    NAME="Ubuntu"
    VERSION="14.04.4 LTS, Trusty Tahr"
    ID=ubuntu
    ID_LIKE=debian
    PRETTY_NAME="Ubuntu 14.04.4 LTS"
    VERSION_ID="14.04"

Dokku version gives: 
    
    0.4.14

Going to `/var/lib/dokku/plugins/available/letsencrypt` and running `git rev-parse HEAD` gives: 

     4887fa683d2ae1d2261e2f11e53e102c306a4d33

**Comment by sseemayer** [comment]
Ah, there's the problem - you've updated dokku-letsencrypt to a version that will only support dokku 0.5 or later. You have two options:

 - Upgrade dokku
 - Downgrade dokku-letsencrypt [to the last version supporting dokku 0.4](https://github.com/dokku/dokku-letsencrypt#upgrading-from-previous-versions)

**Comment by hellojere** [comment]
Cheers! Will do the former. Sorry for the trouble.

**Comment by sseemayer** [comment]
No worries, glad to help! Plus, you are the first to report this issue so I'm sure that you'll be helping people out that will be using the search function in the future :+1:

**Comment by sseemayer** [comment]
Just to be sure, let me also preemptively make you aware of the fact that the mechanism for Dockerfile deploys has changed in dokku 0.5 upwards - see e.g. the [0.5 migration guide](https://github.com/dokku/dokku/blob/master/docs/appendices/0.5.0-migration-guide.md), dokku/dokku#2028 and #58 .
