### ISSUE TITLE
Dokku 0.6.x support?

### ISSUE THREAD

**Issue by henry40408** [dokku/dokku-letsencrypt#63]
## Problem

I have upgrade Dokku to `0.6.1`, then `nginx` doesn't start properly, which make my every application offline. Log tells me that nginx configuration file does not pass test because nginx cannot find `tls/server.crt` and `tls/server.key` in application directory.

## Workaround

I need to remove `https:443:5000` from configuration `DOKKU_PROXY_PORT_MAP` of every application, then `nginx` would work again.

**Comment by henry40408** [comment]
After manually do the workaround on broken applications, it's strange that `dokku-letsencrypt` works again.

**Comment by sseemayer** [comment]
Hi @henry40408 , glad you got things working by yourself. I just wanted to point out #64 and #65 to you and that any leftover problems might get solved by updating to the newest dokku-letsencrypt in case there should be more problems
