### ISSUE TITLE
Fix auto-renew and ls after dokku 0.6.x upgrade

### ISSUE THREAD

**Issue by sseemayer** [dokku/dokku-letsencrypt#65]
`letsencrypt:auto-renew` and `letsencrypt:ls` are broken after #64 changed the way Let's Encrypt certificates are installed to be more compatible with dokku.

The problem is the [detection of let's encrypt-secured apps by checking for the server certificate being a symlink into the let's encrypt folder](https://github.com/dokku/dokku-letsencrypt/blob/master/functions#L90-L95).

This check needs to be replaced with something else since the certificate is now a copy of the certificates, not a symlink. Suggestion would be to use `openssl` to check for the certificate issuer instead (should support both real LE and the fake CA for testing)

**Comment by josegonzalez** [comment]
You could check that the contents are the exact same?

**Comment by sseemayer** [comment]
Guess that should work, too.
