### ISSUE TITLE
documentation improvements required

### ISSUE THREAD

**Issue by samuelcolvin** [dokku/dokku-letsencrypt#68]
not sure if this is just because dokku-letsencrypt doesn't work with `dokku 0.6.5` or because documentation is missing.

If it's the latter a prominent message saying which version of dokku the plugins works with would be very helpful.

I had a pretty frustrating time setting up letsencrypt and SSL generally. The initial `dokku letsencrypt <app>` when fine. But there was no comment or documentation saying a custom `nginx.conf.sigil` file was required.

The nginx.conf file which was generated after `dokky letsencrypt <app>` (don't know how it looked before) had two errors in it which took me some time to find and fix:

```
server {
  listen      [::]:443;
  listen      443;
  server_name timecruncher.com; 
  access_log  /var/log/nginx/timecruncher-access.log;
  error_log   /var/log/nginx/timecruncher-error.log;

  location    / {

    gzip on;
    gzip_min_length  1100;
    gzip_buffers  4 32k;
    gzip_types    text/css text/javascript text/xml text/plain text/x-component application/javascript application/x-javascript application/json application/xml  application/rss+xml font/truetype application/x-font-ttf font/opentype application/vnd.ms-fontobject image/svg+xml;
    gzip_vary on;
    gzip_comp_level  6;

    proxy_pass  http://timecruncher-443;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_set_header Host $http_host;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Forwarded-For $remote_addr;
    proxy_set_header X-Forwarded-Port $server_port;
    proxy_set_header X-Request-Start $msec;
  }
  include /home/dokku/timecruncher/nginx.conf.d/*.conf;

}

server {
  listen      [::]:80;
  listen      80;
  server_name timecruncher.com; 
  access_log  /var/log/nginx/timecruncher-access.log;
  error_log   /var/log/nginx/timecruncher-error.log;

  return 301 https://$host:$request_uri;

}

upstream timecruncher-443 {

  server 172.17.0.2:443;
}

upstream timecruncher-80 {

  server 172.17.0.2:80;
}
```

problems:
* ssl is missing from the listen directive
* the ssl certs directives `ssl_certificate` and `ssl_certificate_key` aren't included.
* (not important) `timecruncher-80` isn't used

I'm not sure which of these problems are `dokku` and which `dokku-letsencrypt`, happy to re-post on dokku if that makes more sense

**Comment by sseemayer** [comment]
dokku-letsencrypt should work fine on dokku 0.6.5 without providing a custom nginx config file. It seems like you are having the same problem as #69 so I'll try to debug things with @MichaelSp and you there :+1:
