### ISSUE TITLE
Validation fails when a rewrite directive is present in a custom nginx.conf.sigil

### ISSUE THREAD

**Issue by justinsacbibit** [dokku/dokku-letsencrypt#72]
I'm not too familiar with nginx, but I am 95% sure that a rewrite directive was causing my ACME validation to fail.

My hypothesis is that that the URLs were being rewritten and thus the ACME validation requests were going to my application rather than to the dokku-letsencrypt plugin.

Below is part of my custom nginx.conf.sigil.

```nginx
server {
  ...

  rewrite ^(.*)$ /a$1 break;

  include {{ .DOKKU_ROOT }}/{{ .APP }}/nginx.conf.d/*.conf;
}
```

It would be cool if this was documented in some sort of "gotchas/troubleshooting" section, with suggested fixes. Or, if it's even possible, a code change that fixes this issue!

Once I get around to finding a fix myself, if you guys think that the plugin could benefit from documenting this, I could definitely try to push up a PR that documents this issue.

**Comment by sseemayer** [comment]
The dokku-letsencrypt plugin validates domains by catching requests to 
`/.well-known/acme-request` using an nginx `location` directive that is 
included by placing a file into `nginx.conf.d`. Adding a rewrite rule on 
the `server` level in a custom config can definitely affect the ACME 
validation.

I'd be happy to accept a PR e.g. to the readme if you'd like to write 
something up.

**Comment by sseemayer** [comment]
A suggestion on how to fix this would be to move the rewrite directive to the location block since it will only affect requests coming to your app but not dokku-letsencrypt.

**Comment by sseemayer** [comment]
Closing since the question was answered. @justinsacbibit I'd still be happy to accept a PR to the README if you would like to contribute one :+1:
