### ISSUE TITLE
SHA256 hash of the TOS has changed (URGENT)

### ISSUE THREAD

**Issue by madshargreave** [dokku/dokku-letsencrypt#73]
I get the following error when running `dokku letsencrypt myapp`. I'm on Dokku 0.7.0 

Looks like it is related to 

[SHA256 hash of the TOS has changed](https://github.com/kuba/simp_le/issues/114)

```
root@resend:~# dokku letsencrypt production
=====> Let's Encrypt production...
-----> Updating letsencrypt docker image...
latest: Pulling from dokkupaas/letsencrypt-simp_le
420890c9e918: Already exists 
e4a2ae244258: Already exists 
5c6ac6d1c950: Already exists 
Digest: sha256:18a19b34beceba79dd5be458abe7e132fc7486da1da19cc4d0395ad4578031ef
Status: Image is up to date for dokkupaas/letsencrypt-simp_le:latest
       done
-----> Enabling ACME proxy for production...
-----> Getting letsencrypt certificate for production...
        - Domain 'production.resend.io'
        - Domain 'resend.io'
        - Domain 'ws.resend.io'
        - Domain 'www.resend.io'
darkhttpd/1.11, copyright (c) 2003-2015 Emil Mikulic.
listening on: http://0.0.0.0:80/
2016-08-01 22:34:32,324:INFO:__main__:1211: Generating new account key
2016-08-01 22:34:38,247:INFO:requests.packages.urllib3.connectionpool:758: Starting new HTTPS connection (1): acme-staging.api.letsencrypt.org
2016-08-01 22:34:38,593:INFO:requests.packages.urllib3.connectionpool:758: Starting new HTTPS connection (1): acme-staging.api.letsencrypt.org
2016-08-01 22:34:38,754:INFO:requests.packages.urllib3.connectionpool:758: Starting new HTTPS connection (1): acme-staging.api.letsencrypt.org
2016-08-01 22:34:39,294:INFO:requests.packages.urllib3.connectionpool:758: Starting new HTTPS connection (1): letsencrypt.org
TOS hash mismatch. Found: 6373439b9f29d67a5cd4d18cbc7f264809342dbf21cb2ba2fc7588df987a6221.

Debugging tips: -v improves output verbosity. Help is available under --help.
-----> Certificate retrieval failed!
-----> Disabling ACME proxy for production...
       done

```

**Comment by drbraden** [comment]
The LetsEncrypt Terms of Service recently changed, resulting in a different hash for the file.

As a work-around until the simple_le LetsEncrypt client is updated, you can pass the correct hash as a command-line option.  In the file ```/var/lib/dokku/plugins/available/letsencrypt/subcommands/default```, locate the "letsencrypt_acme ()" function and edit the "docker run" command to include the new hash using the "--tos_sha256" option.

Here is the replacement that works for me:
```bash
  docker run --rm \
    -p "$acme_port:80" \
    -v "$config_dir:/certs" \
    dokkupaas/letsencrypt-simp_le:latest \
    -f account_key.json \
    -f fullchain.pem -f chain.pem -f cert.pem -f key.pem \
    --valid_min "${graceperiod}" \
    --tos_sha256 6373439b9f29d67a5cd4d18cbc7f264809342dbf21cb2ba2fc7588df987a6221 \
    "${config[@]}"
```

**Comment by madshargreave** [comment]
@drbraden after a few hours of panic, you saved my ass, 

Much appreciated!

**Comment by sseemayer** [comment]
Once kuba/simp_le is updated and the corresponding Docker image [dokku/docker-letsencrypt-simp_le](https://github.com/dokku/docker-letsencrypt-simp_le) is updated, this will go away by itself.

For the time being, I've added the `--tos_sha256` parameter to the simp_le configuration in f541f1e95fc469daf0478d60a52eb418e907cc48. After updating dokku-letsencrypt to 0.8.5, things should work normally again. 

I'd suggest to keep the issue open for others encountering the problem and will close it once kuba/simp_le#114 is solved.

**Comment by drbraden** [comment]
@madshargreave You're very welcome, glad to have helped!  After a couple of weeks of testing, I finally moved a production site off of Linode and onto my Dokku box, only to be hit by the hash change after changing DNS and generating the new certs.  So, you could say I was a bit motivated as well :)

**Comment by kachkaev** [comment]
ToS diff (if any one is interested in what they sign):
https://letsencrypt.org/documents/LE-SA-v1.0.1-v1.1.1-diff.docx
https://letsencrypt.org/repository/

**Comment by tonyspiro** [comment]
I'm hitting this issue, upgraded the plugin, but no luck.  Is there a dokku command to fix this?

**Comment by sseemayer** [comment]
@tonyspiro f541f1e should fix this already. Can you please provide a log (as a gist)  of your dokku letsencrypt run with `dokku trace on` enabled

**Comment by tonyspiro** [comment]
Thanks @sseemayer here's the gist https://gist.github.com/tonyspiro/83e3aed4b1d56b5b5cbcb17dc916a85f

**Comment by sseemayer** [comment]
@tonyspiro [this line in the gist](https://gist.github.com/tonyspiro/83e3aed4b1d56b5b5cbcb17dc916a85f#file-gistfile1-txt-L1137) is the simp_le run that is being started. Expanded to several line, it looks like this:

```
docker run --rm -p 24824:80 \
    -v /home/dokku/goraines/letsencrypt/certs/2dbb4c9bfcf05b27855b0f7d90044978f8bd91d9:/certs \
    dokkupaas/letsencrypt-simp_le:latest \
        -f account_key.json -f fullchain.pem -f chain.pem -f cert.pem -f key.pem \
        --valid_min 2592000 --server https://acme-v01.api.letsencrypt.org/directory \
        --email tspiro@tonyspiro.com \
        -d goraines.cosmicapp.co \
        -d goraines.com -d goraines.com -d www.goraines.com -d goraines.com -d www.goraines.com
```

Note that the `--tos_sha256` parameter added with f541f1e is missing. Can you confirm what dokku and dokku-letsencrypt version you are running?

**Comment by tonyspiro** [comment]
thanks @sseemayer 
dokku 0.4.12
letsencrypt 0.7.3

**Comment by tonyspiro** [comment]
@sseemayer is this an issue with the versions I'm running?

**Comment by crisward** [comment]
I've found updating to dokku v7 then updating letencrypt fixed this for me. v4 letsencrypt plugin didn't seem to have been patched. (as of last week). Not sure if this has changed. Updating dokku does cause downtime though.

**Comment by sseemayer** [comment]
Apologies about the slow response times, I've started a new job recently and things are still settling.

@crisward is correct in that the dokku-0.4 branch of dokku-letsencrypt hadn't been updated with the TOS hash. I've added this with 2b91351 but would still strongly encourage you to upgrade to a recent dokku version.

**Comment by tonyspiro** [comment]
Ok, I'll update dokku.  Congrats on the new job @sseemayer 👍  Thanks @sseemayer and @crisward!

**Comment by tonyspiro** [comment]
@sseemayer @crisward I've upgraded to dokku 0.7.0 and dokku letsencrypt 0.7.3.  But I'm still getting the  TOS hash mismatch error https://gist.github.com/tonyspiro/8a7fc8c81f9beec66024c4c1cae753cb  Any more help on this is greatly appreciated!

**Comment by tonyspiro** [comment]
@sseemayer @crisward I figured out the issue. Just updating the plugin didn't work.  I needed to uninstall then reinstall dokku-letsencrypt and it then updated to 0.8.5. Thanks again for the help!

**Comment by chrisnew** [comment]
@tonyspiro Your trick did it for me as well! Thank you!

**Comment by sseemayer** [comment]
@tonyspiro @chrisnew for the record, if you upgrade from dokku 0.4 to dokku >= 0.5, the dokku-letsencrypt plugin stays on the [dokku-0.4 branch](https://github.com/dokku/dokku-letsencrypt/tree/dokku-0.4 branch) by default. Uninstalling and reinstalling works, but you can also switch to the master branch by running:

```
dokku plugin:update letsencrypt master
```

**Comment by jbothma** [comment]
I had to make the change in /var/lib/dokku/plugins/available/letsencrypt/functions

**Comment by mrusa** [comment]
For me, currently running Dokku 0.5.7, i had to `cd` into the plugins directory (/var/lib/dokku/plugins/available/letsencrypt) and then run `git pull`. Everything works fine again.

Thank you all :)

**Comment by sseemayer** [comment]
@jbothma @mrusa your problems should also be fixable by simply making sure that you are on the current version using [the official update instructions](https://github.com/dokku/dokku-letsencrypt/blob/master/README.md#upgrading-from-previous-versions). Glad you got things working though!

**Comment by sseemayer** [comment]
Closing since we are now maintaining our own simp_le fork

**Comment by Kinzi** [comment]
I'm getting this error as well today. Yesterday it seems to work fine. Adding `--tos_sha256`didn't help. Any ideas?

**Comment by brudil** [comment]
It looks like they've just updated the TOS's to v1.2 today.

Changing the hash value in `/var/lib/dokku/plugins/available/letsencrypt/functions` to `f33c27745f2bd87344be790465ef984a972fd539dc83bd4f61d4242c607ef1ee` allowed me to successfully issue a cert until a release with the new hash.

**Comment by MattLuk112** [comment]
I had to set the hash in ```/var/lib/dokku/plugins/available/letsencrypt/functions``` to ```cc88d8d9517f490191401e7b54e9ffd12a2b9082ec7a1d4cec6101f9f1647e7b```

**Comment by dps** [comment]
cc88d8d9517f490191401e7b54e9ffd12a2b9082ec7a1d4cec6101f9f1647e7b in /var/lib/dokku/plugins/available/letsencrypt/functions also worked for me.

**Comment by fronbasal** [comment]
Does not seem to work.
The hash ```cc88d8d9517f490191401e7b54e9ffd12a2b9082ec7a1d4cec6101f9f1647e7b``` is not valid anymore. It throws following error: ```TOS hash mismatch. Found: cc88d8d9517f490191401e7b54e9ffd12a2b9082ec7a1d4cec6101f9f1647e7b.```

**Comment by gauravmehla** [comment]
Having the same issue. `cc88d8d9517f490191401e7b54e9ffd12a2b9082ec7a1d4cec6101f9f1647e7b` this isn't working anymore...

```
2017-11-20 09:51:13,566:INFO:__main__:1211: Generating new account key
TOS hash mismatch. Found: cc88d8d9517f490191401e7b54e9ffd12a2b9082ec7a1d4cec6101f9f1647e7b.
Debugging tips: -v improves output verbosity. Help is available under --help.
-----> Certificate retrieval failed!
-----> Disabling ACME proxy for api...
       done
```

**Comment by fronbasal** [comment]
Yip. You need to change the hash in both files, `default` *and* `functions`.

**Comment by chgad** [comment]
+1 Will there be an Update somewhere soon?

**Comment by xtrasimplicity** [comment]
For anyone who may have had trouble locating the correct line in `/var/lib/dokku/plugins/available/letsencrypt/functions`, it will look something like this:
```
LETSENCRYPT_CONFIG="--server $LETSENCRYPT_SERVER --email $LETSENCRYPT_EMAIL --tos_sha256 <SOME_HASH> $DOMAIN_ARGS"
``` 
where `<SOME_HASH>` is the TOS hash.

Simply change the hash to `cc88d8d9517f490191401e7b54e9ffd12a2b9082ec7a1d4cec6101f9f1647e7b` as per @MattLuk112 's recommendation above.

```
LETSENCRYPT_CONFIG="--server $LETSENCRYPT_SERVER --email $LETSENCRYPT_EMAIL --tos_sha256 cc88d8d9517f490191401e7b54e9ffd12a2b9082ec7a1d4cec6101f9f1647e7b $DOMAIN_ARGS"
```
