### ISSUE TITLE
http aside https

### ISSUE THREAD

**Issue by ilk** [dokku/dokku-letsencrypt#74]
When enable letsencrypt all http traffic will be redirected to http**s**. 

Is there a way to you both protocols? I need to offer https but no exclusively.

**Comment by sseemayer** [comment]
dokku-letsencrypt only handles certificate installation and uses the default dokku mechanism for nginx configuration. The correct place to ask about how to override the default behavior would be the main dokku project but I'll try to help anyways :smile: 

From the [dokku docs on SSL configuration](http://dokku.viewdocs.io/dokku/configuration/ssl/#ssl-and-multiple-domains):

> Note that with the default nginx template, requests will be redirected to the https version of the domain. If this is not the desired state of request resolution, you may customize the nginx template in use. For more details, see the [nginx documentation](http://dokku.viewdocs.io/dokku/configuration/nginx/).

You'd have to create a custom nginx configuration that includes a server block for http and https that will proxy requests on both protocols to your app.

**Comment by ilk** [comment]
Many thanks!

**Comment by sseemayer** [comment]
Glad to help! :+1:
