### ISSUE TITLE
Cron-job removal doesn't seem to be working correctly

### ISSUE THREAD

**Issue by natanrolnik** [dokku/dokku-letsencrypt#79]
Hi! 

First, thanks for this incredible plugin for Dokku. Second, I may be doing something wrong, but:

I repeated by mistake `dokku letsencrypt:cron-job --add`, and now when trying to remove, I always get a list of 4 cron jobs, and then the message `Removed cron job from dokku's crontab.` If I run `sudo -u dokku crontab -l`, the same equal 4 cron jobs appear, doesn't matter how many times I run `dokku letsencrypt:cron-job --remove`.

Dokku version: 0.7.1
letsencrypt plugin: 0.8.5

**Comment by sseemayer** [comment]
It could be that the reverse grep (`grep -v`) doesn't correctly detect the cronjob entry and thus won't filter it out.

Can you please post your crontab for the dokku user (`sudo crontab -u dokku -l`)?

For reference, on my system it contains this line:
```
@daily /var/lib/dokku/plugins/available/letsencrypt/cron-job
```

If you are in a hurry to remove the cronjob, you can use `sudo crontab -u dokku -e` to manually edit your crontab and remove all lines you don't want. I would appreciate if you posted the contents of your crontab here to help me figure out what went wrong, though :smile:

**Comment by natanrolnik** [comment]
Hey @sseemayer thanks for your reply.
I'm definitely not in a hurry, I prefer to wait for a new release and checking that it worked, than to edit manually - it's a development instance, not my production one, and I activated only one domain in that machine.

Here is what `sudo crontab -u dokku -l` returns:

```
@daily /var/lib/dokku/plugins/available/letsencrypt/cron-job
@daily /var/lib/dokku/plugins/available/letsencrypt/cron-job
@daily /var/lib/dokku/plugins/available/letsencrypt/cron-job
@daily /var/lib/dokku/plugins/available/letsencrypt/cron-job
```

**Comment by sseemayer** [comment]
I actually was able to reproduce this on my own system, too - not sure what changed since this was working before :confused: 

Anyways, 007323e fixed things on my side, let me know if it works for you, too! :smile:

**Comment by natanrolnik** [comment]
Indeed, fixed 😃
Now it also avoids adding duplicates. Good job!
