### ISSUE TITLE
SAN (Subject Alternative Name) config

### ISSUE THREAD

**Issue by chasd00** [dokku/dokku-letsencrypt#82]
Want to secure both example.com and www.example.com. It seems letsencrypt certs are capable of this but I don't see anywhere in the docs how to do this. Am I missing something or is it the feature not there yet?

**Comment by sseemayer** [comment]
You can simply use `dokku domains:add` to make sure that all domains that you want to request a certificate for are configured in your dokku app. Once you're happy with the `dokku domains <yourapp>` output, you can  run `dokku letsencrypt <yourapp>` to request a certificate for all domains.

**Comment by sseemayer** [comment]
I'm assuming that this is resolved for lack of activity. Let me know if you have any further questions 👍

**Comment by chasd00** [comment]
Sorry about that. Yes, issue resolved.
