### ISSUE TITLE
cron-job command not working on dokku 0.4.12

### ISSUE THREAD

**Issue by the21st** [dokku/dokku-letsencrypt#84]
I installed dokku-letsencrypt plugin for dokku 0.4 and set up the certificate, but when attempting to run

`$ dokku letsencrypt:cron-job --add`

I get:

`App name must begin with lowercase alphanumeric character`

**Comment by sseemayer** [comment]
The `letsencrypt:cron-job` command is only supported starting from the plugin version 0.8.2 which only works with Dokku 0.5 or later. If you want to automatically install cronjobs, you'd have to upgrade 😞

**Comment by the21st** [comment]
Thanks for the info!

I created a PR adding this requirement to Readme.

**Comment by sseemayer** [comment]
Thanks for the PR! Wishing you a successful dokku upgrade should you decide to upgrade :+1:
