### ISSUE TITLE
Cert. Company Name

### ISSUE THREAD

**Issue by drxos** [dokku/dokku-letsencrypt#86]
Hello.

How can I see the other information belong to the certificate like *Company Name, Department ...* ?

**Comment by sseemayer** [comment]
You can check more information contained in the certificate by running `sudo openssl x509 -in /home/dokku/yourapp/tls/server.crt -text`, replacing `yourapp` with the name of your app. For LE-issued certificates, I'd expect `Issuer: C=US, O=Let's Encrypt, CN=Let's Encrypt Authority X3` to be the issuer information in every case, though.

**Comment by drxos** [comment]
Ok. Thanks. But I cannot modify this file in order to supply the owner informations.

**Comment by sseemayer** [comment]
Let's Encrypt only gives out certificates proving the identity of a **domain name** and you cannot modify a certificate after it has been signed. If you want to associate an identity with your certificate, you will have to buy an [Extended Validation](https://en.wikipedia.org/wiki/Extended_Validation_Certificate) certificate.

**Comment by drxos** [comment]
Thanks.
