### ISSUE TITLE
Recommended way to enforce https only?

### ISSUE THREAD

**Issue by henrik** [dokku/dokku-letsencrypt#88]
I want http://example.com to redirect to https://example.com. Is there a recommended way to do that within Dokku (e.g. by having Dokku modify nginx rules)? Could it be within the scope of this plugin?

**Comment by henrik** [comment]
Oh, actually, I guess this already happens automatically. At least I seem to see this behaviour.

**Comment by sseemayer** [comment]
Hi Henrik, thanks for your interest in the plugin!

you already answered your question yourself correctly but let me point you [to the dokku documentation on SSL](http://dokku.viewdocs.io/dokku/configuration/ssl/#ssl-and-multiple-domains)

> Note that with the default nginx template, requests will be redirected to the https version of the domain. If this is not the desired state of request resolution, you may customize the nginx template in use. For more details, see the nginx documentation.

While not done by dokku by default, you can also consider configuring [HSTS](https://en.wikipedia.org/wiki/HTTP_Strict_Transport_Security) for your app to automatically enforce https for recurring visitors.

**Comment by henrik** [comment]
Stefan, thank you! I may make a PR later to try to clarify these points further in the plugin docs.
