### ISSUE TITLE
Wrong directory fields

### ISSUE THREAD

**Issue by slava-vishnyakov** [dokku/dokku-letsencrypt#90]
I'm getting a weird error on one of the domains: `DeserializationError: Deserialization error: Wrong directory fields`. Googling produces nothing.

I have other domains with letsencrypt on this server and they work fine. 

Any ideas?

    root@dokku ~ # dokku config:set --no-restart exampleapp.com DOKKU_LETSENCRYPT_EMAIL=myemail@provider.com
    -----> Setting config vars
           DOKKU_LETSENCRYPT_EMAIL: myemail@provider.com
    
    root@dokku ~ # dokku letsencrypt exampleapp.com
    =====> Let's Encrypt exampleapp.com
    -----> Updating letsencrypt docker image...
    latest: Pulling from dokkupaas/letsencrypt-simp_le
    420890c9e918: Already exists
    e4a2ae244258: Already exists
    5c6ac6d1c950: Already exists
    Digest: sha256:18a19b34beceba79dd5be458abe7e132fc7486da1da19cc4d0395ad4578031ef
    Status: Image is up to date for dokkupaas/letsencrypt-simp_le:latest
           done updating
    -----> Enabling ACME proxy for exampleapp.com...
    -----> Getting letsencrypt certificate for exampleapp.com...
            - Domain 'exampleapp.com'
    darkhttpd/1.11, copyright (c) 2003-2015 Emil Mikulic.
    listening on: http://0.0.0.0:80/
    2016-12-09 08:06:47,751:INFO:__main__:1211: Generating new account key
    2016-12-09 08:06:48,554:INFO:requests.packages.urllib3.connectionpool:758: Starting new HTTPS connection (1): acme-v01.api.letsencrypt.org
    Traceback (most recent call last):
      File "/simp_le-master/simp_le.py", line 1401, in main
        return main_with_exceptions(cli_args)
      File "/simp_le-master/simp_le.py", line 1386, in main_with_exceptions
        persist_new_data(args, existing_data)
      File "/simp_le-master/simp_le.py", line 1282, in persist_new_data
        client = registered_client(args, existing_data.account_key)
      File "/simp_le-master/simp_le.py", line 1224, in registered_client
        client = acme_client.Client(directory=args.server, key=key, net=net)
      File "/usr/lib/python2.7/site-packages/acme/client.py", line 63, in __init__
        self.net.get(directory).json())
      File "/usr/lib/python2.7/site-packages/acme/messages.py", line 169, in from_json
        raise jose.DeserializationError(str(error))
    DeserializationError: Deserialization error: Wrong directory fields
    
    Unhandled error has happened, traceback is above
    
    Debugging tips: -v improves output verbosity. Help is available under --help.
    -----> Certificate retrieval failed!
    -----> Disabling ACME proxy for exampleapp.com...
           done

**Comment by andyjeffries** [comment]
I'm getting the same problem here... Apparently simp_le is now unmaintained, someone else commented they've moved to acme.sh https://github.com/kuba/simp_le/issues/114

**Comment by andyjeffries** [comment]
@sseemayer pinging you as you seem to be the main committer to this plugin, thanks for any help you can provide.

**Comment by kamidev** [comment]
Yes, I also get the same problem. I have a server where I, until recently, could create and revoke  certificates as needed.

**Comment by DebauchedSloth** [comment]
Same problem here.  It would appear that it just started within the last couple of days.

**Comment by SAGV** [comment]
Same problem…

**Comment by sseemayer** [comment]
As a heads up, I'm traveling this weekend with limited connectivity and won't be able to troubleshoot. 

I've seen in https://github.com/kuba/simp_le/issues/118 that a PR is mentioned as a fix which might be a workaround in the short term. 

Since simp_le seems abandoned a long term fix should be to migrate to a maintained acme client like e. g. acme.sh

**Comment by dotcypress** [comment]
FIY: https://github.com/dokku/docker-letsencrypt-simp_le/pull/1

**Comment by emveeoh** [comment]
Until this issue is fixed, here are step-by-step instructions on how you MANUALLY add Let's Encrypt certificates with Dokku:

https://words.mxbry.com/http-2-let-s-encrypt-dokku-how-to-do-all-three-7de94a0028fb#.hggceynj0

You can enable the auto-updating of certificate renewals:
```
$certbot_github_directory/certbot-auto renew --renew-hook "service nginx restart"
```

**Comment by joshmanders** [comment]
As stated in https://github.com/dokku/docker-letsencrypt-simp_le/pull/1#issuecomment-266548938 I have fixed this. Just waiting for Jose to be available and we can get it all formally fixed and an upgrade on the plugin will be available after that.

**Comment by matthewmueller** [comment]
ping @josegonzalez :-)

**Comment by joshmanders** [comment]
He's busy with his day job and is aware I am working on this. No need to ping him. :)

**Comment by josegonzalez** [comment]
Thanks @joshmanders for jumping in and fixing this, much appreciated!

**Comment by andyjeffries** [comment]
Working for me now! Many thanks!

**Comment by pascalw** [comment]
Confirming that it works for me too, thanks @joshmanders

**Comment by sseemayer** [comment]
Thanks @joshmanders @josegonzalez and everyone else for your help on this and sorry for my limited availability. I'm glad things are working normally again.

**Comment by UlTriX** [comment]
I am on dokku version 0.4.9 using dokku-letsencrypt pre 0.5. 
Is there any way I can fix this without upgrading?

**Comment by fruitl00p** [comment]
This should fix it ;)

--- a/functions
+++ b/functions
@@ -142,7 +142,7 @@ letsencrypt_is_active() {
   APP=$1
 
   # check if SSL is enabled on per-app level
-  if [[ "$(is_ssl_enabled $APP)" ]]; then
+  if [[ "$(is_ssl_enabled $APP)" != "app" ]]; then
     return 1
   fi

**Comment by UlTriX** [comment]
My functions file already has that 
if [[ "$(is_ssl_enabled $APP)" != "app" ]];
but I countinue to get the same error

**Comment by fruitl00p** [comment]
@UlTriX hmmmz... then i'm out of ideas... this is our only change vs the regular dokku-letsencrypt (we're using #b2788c7c8e5ee32d7b7b73aa0004bf570362abb2 with the aforementioned patch

**Comment by UlTriX** [comment]
From what I understand the fix was applied on a fork of docker-letsencrypt-simp_le
How should I point to that?

**Comment by josegonzalez** [comment]
You're going to need to upgrade.

**Comment by UlTriX** [comment]
@josegonzalez I sure need too but it is a critical machine where downtime is not possible at this time.

I have updated all references to the dokkupaas/letsencrypt-simp_le container and the certificate renewal worked.
