### ISSUE TITLE
ERR: Root / default domain SSL certificate error + multiple apps

### ISSUE THREAD

**Issue by emveeoh** [dokku/dokku-letsencrypt#91]
I have a Dokku instance with multiple apps. 

For example:
site1.mydomain.com
site2.mydomain.com
site3.mydomain.com

Each has its own subdomain.
Each subdomain has its own SSL certificate installed using dokku-letsencrypt.
Each subdomain works great via HTTPS://

However, when I go to the root domain address (mydomain.com or www.mydomain.com), I get the following error:

**This server could not prove that it is www.mydomain.com; its security certificate is from mydomain.mydomain.com. This may be caused by a misconfiguration or an attacker intercepting your connection**

Help please. I'm not sure what is causing this.

**Comment by sseemayer** [comment]
If none of the domains configured by the dokku apps matches with the selected URL, the nginx server will still proxy to one of the running apps (if I remember correctly, the first in alphabetic order) and present the certificate of that app even if it doesn't match the requested URL. 

You can configure what domains a dokku app matches to using `dokku domains`. When you re-run `dokku letsencrypt`, one certificate for all configured domains will be requested

**Comment by emveeoh** [comment]
@sseemayer  Thank you for your response!

Per your suggestion, I added the domains using Dokku's command:
```
dokku domains:add mydomain mydomian.com
```

Then, I tried to re-run dokku-letsencrypt to grab a new certaificate and I get the error below:

```
dokku letsencrypt mydomain
```

It started off well. It tried to generate a certificate for all three variants of the domain name:

```
-----> Getting letsencrypt certificate for mydomain...
        - Domain 'mydomain.mydomain.com'
        - Domain 'mydomain.com'
        - Domain 'www.mydomain.com'
```

However, the certificate retrieval fails with the an error. Full output below:

```
=====> Let's Encrypt mydomain
-----> Updating letsencrypt docker image...
latest: Pulling from dokkupaas/letsencrypt-simp_le

420890c9e918: Already exists 
e4a2ae244258: Already exists 
5c6ac6d1c950: Already exists 
Digest: sha256:18a19b34beceba79dd5be458abe7e132fc7486da1da19cc4d0395ad4578031ef
Status: Image is up to date for dokkupaas/letsencrypt-simp_le:latest
       done updating
-----> Enabling ACME proxy for mydomain...
-----> Getting letsencrypt certificate for mydomain...
        - Domain 'mydomain.mydomain.com'
        - Domain 'mydomain.com'
        - Domain 'www.mydomain.com'
darkhttpd/1.11, copyright (c) 2003-2015 Emil Mikulic.
listening on: http://0.0.0.0:80/
2016-12-10 20:37:59,280:INFO:__main__:1211: Generating new account key
2016-12-10 20:38:00,094:INFO:requests.packages.urllib3.connectionpool:758: Starting new HTTPS connection (1): acme-v01.api.letsencrypt.org
Traceback (most recent call last):
  File "/simp_le-master/simp_le.py", line 1401, in main
    return main_with_exceptions(cli_args)
  File "/simp_le-master/simp_le.py", line 1386, in main_with_exceptions
    persist_new_data(args, existing_data)
  File "/simp_le-master/simp_le.py", line 1282, in persist_new_data
    client = registered_client(args, existing_data.account_key)
  File "/simp_le-master/simp_le.py", line 1224, in registered_client
    client = acme_client.Client(directory=args.server, key=key, net=net)
  File "/usr/lib/python2.7/site-packages/acme/client.py", line 63, in __init__
    self.net.get(directory).json())
  File "/usr/lib/python2.7/site-packages/acme/messages.py", line 169, in from_json
    raise jose.DeserializationError(str(error))
DeserializationError: Deserialization error: Wrong directory fields

Unhandled error has happened, traceback is above

Debugging tips: -v improves output verbosity. Help is available under --help.
-----> Certificate retrieval failed!
-----> Disabling ACME proxy for mydomain...
       done
```

I'm not sure how to interpret this error. Any ideas?

**Comment by sseemayer** [comment]
Your configuration looks good so far, now you're running into #90

**Comment by emveeoh** [comment]
Gotcha... THANKS! I'll watch #90 for updates. Mucho appreciative for the help!
