### ISSUE TITLE
nginx: [emerg] BIO_new_file("/home/dokku/tls/server.crt") failed

### ISSUE THREAD

**Issue by epiqueras** [dokku/dokku-letsencrypt#94]
After running dokku letsencrypt <myapp> ngninx fails with these error messages:

    -----> Enabling ACME proxy for tpos...
    Job for nginx.service failed because the control process exited with error code. See "systemctl
    status nginx.service" and "journalctl -xe" for details.

    nginx: [emerg] BIO_new_file("/home/dokku/tls/server.crt") failed (SSL: error:02001002:system
    library:fopen:No such file or directory:fopen('/home/dokku/tls/server.crt','r') error:2006D080

###### Update
I think the problem was that the app wasn't deployed yet. I deleted the custom nginx.conf and deployed. Now this happens:

    CA marked some of the authorizations as invalid, which likely means it could not access
    http://example.com/.well-known/acme-challenge/X. Did you set correct path in -d
    example.com:path or --default_root? Is there a warning log entry about unsuccessful self
    verification? Are all your domains accessible from the internet?

I can access the myapp.domain.com url on my browser and I checked that there is no port number after the url when I run `dokku urls myapp`.

**Comment by glogiotatidis** [comment]
@epiqueras your second problem is https://github.com/dokku/dokku/issues/2535

You can inspect the nginx.conf template of your app and remove the extra `:` to fix the issue while the dokku folks fix the issue for everyone

**Comment by joshmanders** [comment]
Closing as the bug fix is in dokku core.
