### ISSUE TITLE
Add support for verbose mode for debugging

### ISSUE THREAD

**Issue by OmgImAlexis** [dokku/dokku-letsencrypt#96]
I'm currently trying to debug why I can't get a cert to be issues but I can't just add `-v` to the line for this plugin as it doesn't do anything. It'd be great if there was a way you could pass that through to simp_le.

**Comment by cromulus** [comment]
Same issue.

**Comment by joshmanders** [comment]
PR's are welcome.

**Comment by josegonzalez** [comment]
Closing as there is a pull request open.
