### ISSUE TITLE
Failed to connect to port 443: Operation timed out

### ISSUE THREAD

**Issue by pawelad** [dokku/dokku-letsencrypt#97]
Hiya,

I was playing around with `dokku` for the first, everything went great but went I tried to add SSL via `dokku-letsnecrypt` the site stopped working and started timing out on all requests.
I didn't do any custom configuration, and it was fully working without HTTPS so decided to ask here for help debugging it.

The site is a Django (Python) application, served via gunicorn. Server is on Digital Ocean, DNS is done via CloudFlare.

I tried renewing the certificate (`dokku letsencrypt fakester`), restarting and rebuilding the app (`dokku ps:restart fakester` and `dokku ps:rebuild fakester`), restarting Nginx and the whole server. The site still times out:

```
$ curl -I https://fakester.pawelad.xyz
curl: (7) Failed to connect to fakester.pawelad.xyz port 443: Operation timed out
```

Both Nginx and dokku logs are empty. Port 443 is open and in dokku config.
I looked through the actual Nginx files but couldn't see any errors.

I know the issue is very broad, but does anyone have any idea what could be the problem? Thanks in advance.

**Comment by larose** [comment]
It looks like your website is now working with https. Would you mind sharing what you did to solve your issue to help others and close this issue?

**Comment by pawelad** [comment]
Ah, I completely forgot to close this after I resolved the issue - sorry!

I don't really know what fixed it, but I think that the issue was on the server side, as doing the exact same thing on a clean droplet/system worked.

**Comment by joshmanders** [comment]
> Ah, I completely forgot to close this after I resolved the issue - sorry!

No worries, saw that your https was working and you never responded, so I handled it. :)
